### ISSUE TITLE
[Bug]: Incorrect loan limit amount - other than what the player selected

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10077]
### Version of OpenTTD

since 1.11.0-beta1, related to #8386, the bug is also present in the JGRPP version

### Expected result

Full title:
The loan limit is always a multiple of £ 50,000, despite the possibility to enter a different value. Setting a loan limit below £ 50,000 gives you a limit of 0 which makes it impossible to start the game.

The report de facto concerns two related errors:
1. The loan limit value entered by the player is not used in the game - I don't know since when the problem exists, the loan setting in the window is available from 0.3.4
2. The entered value of the loan limit below £ 50,000 in the game is reduced to £ 0 - the problem appeared with #8386
Solving one of the problems will most likely affect the other, so I attach both of them in one report.

**Three main possibilities:**
1. Enabling the player to actually choose any loan limit, which in the game will be as much as the player entered in the setting. If a player chooses £ 10,000, there will be £ 10,000 in play. If £ 5,492, there will be £ 5,492 in game.
2. The visible loan limit, after entering any amount in the settings window, will be automatically rounded up to a multiple of £ 50,000 or another amount, eg £ 10,000; The description should contain appropriate information regarding the rounding of the amount.
3. Removal of the possibility to enter any loan amount - the selected amount will always be a multiple, although selecting larger amounts will be cumbersome. Then adding the Ctrl+click or (and) Alt+click function, which will give a click x10 (x100) effect (also useful in other cases)

### Actual result

The loan limit is always a multiple of £ 50,000, which the player cannot see in the settings window. The value entered by the player, although visible in the settings window, is not valid in the game. In fact, a multiple of 50,000 will be used, always less than or equal to the one entered. As of 1.11.0 a problem with this is that setting a loan limit below £ 50,000 gives you a limit of 0 which prevents you from starting the game without cheating.

In my opinion, setting a low or very low limit can be an interesting challenge for players ("from rags to riches"), which is currently impossible.

### Steps to reproduce

1. If you set a loan limit of £ 49,999 or less in the settings window, it will be £ 0 in game.
2. If you set a loan limit of £ 50,000 or a multiple of this in the settings window, the game will use that limit exactly.
3. If you set a loan limit above £ 50,000 in the settings window, but other than a multiple of that amount, it will be rounded down to that multiple in the game. So, for example, instead of £ 90,000 it will be £ 50,000.

**Comment by maincomputer** [comment]
Given that the loan amounts are some variety of integer. I believe the problem is with integer division.

In the file Economy,cpp @ line 765
`_economy.max_loan = ((uint64)_settings_game.difficulty.max_loan * _economy.inflation_prices >> 16) / 50000 * 50000;`

Consider that _economy.inflation_prices value starts as 65536 and multiplication and division have a higher precedence than the shift operator.

**Case 1: If you set a loan limit of £ 49,999 or less in the settings window, it will be £ 0 in game.**
(49999 * 65536) =  3276734464
(49999 * 65536) >> 16 = 49999
49999 / 50000 = 0 since neither the numerator or denominator is a float  the result of the division will be zero.

putting it together
(49999 * 65536 >> 16)/ 50000 * 50000 = 0

**Case2: If you set a loan limit of £ 50,000 or a multiple of this in the settings window, the game will use that limit exactly.**

(100000 * 65536) = 6553600000
6553600000 >> 16 = 100000
100000 / 50000 = 20

putting it together
(100000 * 65536 >> 16)/ 50000 * 50000 = 100000

**Case3: If you set a loan limit above £ 50,000 in the settings window, but other than a multiple of that amount, it will be rounded down to that multiple in the game. So, for example, instead of £ 90,000 it will be £ 50,000.**

(90000 * 65536 >> 16) / 50000 = 1   
1 * 50000 = 50000

(210000 * 65536 >> 16) / 5000 = 4
4 * 50000 = 200000


There is another line with same issue in the file company_cmd.cpp @ line 560
`c->money = c->current_loan = (std::min<int64>(INITIAL_LOAN, _economy.max_loan) * _economy.inflation_prices >> 16) / 50000 * 50000;
`

**Comment by nielsmh** [comment]
You're saying that the code does what the code is written to do. Yes, the code as written rounds the maximum loan (after inflation) _down_ to the nearest multiple of 50,000. So I see this ticket as a _feature request_ to modify the loan limit to work in increments of 10,000 or even not have increments at all.

It says so right here:
https://github.com/ldpl/OpenTTD/blob/fa5e2ca276de55233ff4f5f72f7eb4ba752e1ee5/src/table/settings/difficulty_settings.ini#L101-L103
Interval: 50,000

**Comment by maincomputer** [comment]
The configuration file might mention the interval but the code in those two instance still uses a magic number.  Any way I am still new at trying to contribute.

**Comment by krysclarke** [comment]
The `/ 50000 * 50000` bits are what's causing this.
Why are they there?

If nothing else, the explanatory text needs to state that the value entered will be rounded down to the nearest multiple of 50k (or 10k) GBP (in the user's selected currency, of course), AND value should also be dropped to that multiple.

**Comment by fastFox2** [comment]
This issue is still free to take? If so, I personally would allow 10k intervals and tell the user that it will be rounded down.

**Comment by LC-Zorg** [comment]
Good news. :) Personally, I would prefer the ability to set any amount, but intervals of 10,000 won't be bad either. :) However, I would have two remarks about rounding:
1. What if a player enters less than 10,000? Will it be rounded to 0? It won't be good. You could then set 10,000 as the minimum loan, although it wouldn't be possible to create scenarios where a player couldn't borrow money. Probably very rare use, but currently possible.
2. What will a player see after entering an amount other than a multiple of 10,000? It is worth considering that not every player reads descriptions. So if he enters 25,000 and only sees during the game that the limit is 20,000, he may consider it an error. If you use a currency other than British Pound, the amounts you enter are always automatically corrected to multiples of the pound. For example, using DKK after entering 100,000 you will get 99,990. I think it would be good for the game to round the loan amount as you enter it.

**Comment by fastFox2** [comment]
I don't think free input for the loan is necessary because you take loans in intervals anyway. Therefore I would prefer to set the intervals to the steps in which you can take loans (I don't remember that right now).
About rounding:I would change the calculations to float and then use a round function afterwards to get it back to int.
Since I don't have a lot if CPP experience I don't know how to go about displaying the correct number, but if I find that out I would definitely always show the rounded number in the input field.
