### ISSUE TITLE
[Bug]: SDL2 / Wayland: Move viewport with mouse position locked does not lock mouse

### ISSUE THREAD

**Issue by tomec-martin** [OpenTTD/OpenTTD#10140]
### Version of OpenTTD

1.12 Fedora

### Expected result

When moving map/viewport, mouse should stay on fixed position.

### Actual result

During move, mouse is rendered on fixed position, but after move finish, mouse "jumps" to new position.
It is issue with SDL2 library - pull request is created.

### Steps to reproduce

Set viewport scroll behaviour to "...mouse position locked"
Move the map (with right button).
Mouse should stay on fixed position.

**Comment by TrueBrain** [comment]
This problem has been more annoying than I would like. A recap so far:
- We discovered that with the X11 backend it works fine; it is the wayland backend that is causing trouble.
- In the history of SDL you can see that they had trouble getting a grip on this too. Several versions had some problems and some fixes caused other problems. This makes debugging this problem harder than it has to be; but bugs happens.
- In 2.24 and 2.26 several things are changed in SDL which might or might not help more in this problem. In #10470 some reports the problem is gone with 2.26, others not. But this might be related that what backend is used, isn't always as clear.

To add to the issues, most of us either run X11 or use WSLg (which runs Wayland just fine, but .. changing the mouse position is out of the question, on both X11 and Wayland; similar to a remote desktop). So that adds to the problem of testing solutions.

There is a new `SDL_HINT_VIDEO_WAYLAND_EMULATE_MOUSE_WARP` hint that might help out there, but from my understanding the biggest issue is simply that Wayland doesn't support mouse wrapping. This happens on more targets, and our general advise is to select the 3rd option of the `Viewport scroll behaviour`: `Move map with RMB`. This mode works best on basically everything. We even select it by default on some targets (like the webbased version). For those using WSLg it is also the advised mode, as mouse wrapping simply doesn't work there.

That leaves us in a bit of a "meh" for this issue. I see a few ways out:
- Someone delves into this problem who has an actual native Linux with X11 and Wayland
- We make `Move map with RMB` default for Linux; people can try out the `mouse position locked` mode on their own
- We try to detect when mouse locking fails, and fall back to the `Move map with RMB` mode automatically

I am not sure here yet. I do know that what looks like a simple issue, is in fact a lot more complicated due to the many environments the game can run.

I am open for suggestions; in fact, I welcome them!

**Comment by TrueBrain** [comment]
Okay, I prepared two fixes which both might address this issue, and both in different ways. Together they might solve it completely. But I need feedback!

#10919 should solve the weird stuttering people have been reporting. It now should be a smooth movement, although on Wayland it will be a bit weird: the further your real cursor gets away from the on-screen, the faster you scroll.

There is where #10920 comes in. I suspect that Wayland simply doesn't handle WarpMouse requests, causing all the issues. This PR changes the game so it detects that the backend doesn't actually support it, and changes the game into another mouse mode that will work.

Both PRs work on their own, but also combined. I would like to ask anyone able to test this out, on both X11 and Wayland backends, and reports back if this actually solves anything. Be mindful: #10920 changes your `Viewport scroll behaviour`. So you might want to toggle that around a bit to see how it behaves.

Tnx a lot!

**Comment by ghisvail** [comment]
Happy to test them in the Flatpak build for OpenTTD. Do you think I should include both patches?

**Comment by TrueBrain** [comment]
Ideally first the one, then the other, then both :) If it isn't too much work. Otherwise both for sure :) Tnx!

**Comment by ghisvail** [comment]
I can make test builds for all 3 combinations if that helps?

**Comment by ghisvail** [comment]
- Test build with patch #10919: https://github.com/flathub/org.openttd.OpenTTD/pull/106

- Test build with patch #10920: https://github.com/flathub/org.openttd.OpenTTD/pull/107

**Comment by ghisvail** [comment]
@TrueBrain both patches seem to work on the Flatpak builds for X11 and Wayland. I just launched a new game and tried scrolling the map in all 4 directions.

**Comment by TrueBrain** [comment]
Awesome, thank you so much! The second one still needs a bit of work, but the first one already will help a ton :D

**Comment by ghisvail** [comment]
Ok then I'll provide the first one for the Flatpak build since I got a few requests from people running on X11.

**Comment by ghisvail** [comment]
Feel free to ping me if you need another test run once the second patch is ready.

**Comment by TrueBrain** [comment]
@ghisvail we finalized the solution for 10920. Mostly it means that existing users really should change their `Viewport Scroll Behaviour` to `Move map with RMB`. This is now the default for all Linux users, so all new users won't have this issue. I think it would be good if you add this to flatpak too, as it makes the game easier to navigate.

That should round up this bug, finally. It has been a few months, but I think the solution is pretty solid for both X11 and Wayland users :)

Tnx again for the help!

**Comment by ghisvail** [comment]
> I think it would be good if you add this to flatpak too, as it makes the game easier to navigate.

Done :+1:
