### ISSUE TITLE
[Bug]: Permissive local authorities - inconsistent reactions in relation to the assessment of the company

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10183]
### Version of OpenTTD

13.0-beta1

### Expected result

If my or another company's rating is low, I expect possibilities are limited. The new setting corresponds to what players know about the game and its mechanics.

Several possibilities:
- The rating in this setting never drops below 400 (lowest rating: good (201-400)), which corresponds to what the player can do in the game; possible name change to: acquiescent / favorable / friendly
- Companies ratings are invisible, rename setting to "None"
- Really fix the local authority element and make the individual settings really different from each other, because with this change it will still be a poor choice between: 0, 1000, 1001 and 1002

### Actual result

What a player can do in the game in no way corresponds to their rating. This in no way relates to the previous behavior. It's completely inconsistent (at least for me).

### Steps to reproduce

n/a

**Comment by 2TallTyler** [comment]
The local authority attitude setting changes the required minimum rating for removing roads, tunnels, or bridges. (Removing houses is set per house in both base game and NewGRF, and building stations is hardcoded to require at least Very Poor no matter the setting — probably a legacy TTD design choice). The setting does not affect how much the rating changes, just what the town will allow at a certain rating. To remain consistent with this behavior, #9833 extended that concept to the new setting.

I can see the case for hiding the rating text in the town window when the local authority allows everything, but there's a counterargument that this would be less consistent (because the setting is an attitude scale, not an on/off switch).

In any case, this is an intentional design choice and not a bug. I'd be happy to discuss a different design choice in a Pull Request implementing such a different design. 🙂

**Comment by LC-Zorg** [comment]
> The setting does not affect how much the rating changes, just what the town will allow at a certain rating.
> 
The differences between the current settings are practically nonexistent and everywhere a low rating means limiting the possibilities, so what you write, although it is formally true, has nothing to do with practical reception. Low rating = no opportunities, but here it has nothing to do with what players know about the game.

> I can see the case for hiding the rating text in the town window when the local authority allows everything, but there's a counterargument that this would be less consistent (because the setting is an attitude scale, not an on/off switch).

But this arrangement, as it stands, is a local authority exclusion. This is the same as in the case of vehicle breakdowns. It doesn't make sense to show a drop in reliability when breakdowns are disabled, because it doesn't affect the game at all. It only misleads less versed players. The same will be true of the company's evaluation. It will be even worse, because the players have already got used to the drop in reliability. Now they'll get used to another broken thing. :/

> In any case, this is an intentional design choice and not a bug. I'd be happy to discuss a different design choice in a Pull Request implementing such a different design. 

This is a bug because the design itself is flawed.
