### ISSUE TITLE
[Bug]: MILLISECONDS_PER_TICK should be 27, not 30

### ISSUE THREAD

**Issue by PeterN** [OpenTTD/OpenTTD#10205]
### Version of OpenTTD

All of them

### Expected result

Running TTD(Patch) and OpenTTD side-by-side should result in the game time progressing at roughly the same rate.

TTD and TTDPatch both appear to run at approximately 27 ms per tick, which results in 37 ticks per second. This puts a game day of 74 ticks at exactly 2 seconds. A game year is 12m10s.

### Actual result

Running TTD(Patch) and OpenTTD side-by-side, the TTD(Patch) game runs faster. After one month, OpenTTD is behind by around 3 days, 2 months it is behind by approximately 6 days.

OpenTTD actually uses 30 ms per tick, resulting in 33.333 ticks per second. A game day of 74 ticks is 2.466 seconds. A game year is 15 minutes.

### Steps to reproduce

1. Start TTD.
2. Start OpenTTD.
3. Compare the dates (easier with TTDPatch).

🤷

**Comment by ldpl** [comment]
Are you sure TTD even has a stable tick rate and not just speeding up on a better hardware? I remember OpenTTD behaving like that some years ago.
Anyway IMO it's better to just keep the speed as it is, it works fine and everybody is used to it.

**Comment by James103** [comment]
> A game day of 74 ticks is 2.466 seconds

This is incorrect; a game day of 74 ticks at 30 mspt = 74 * 30 = 2220 ms or 2.22 seconds per tick. A game year is then 13 minutes and 30.3 seconds.

**Comment by PeterN** [comment]
Oh yeah, I remember reading it was 2.5 sec and assumed that was roughly correct.

**Comment by nielsmh** [comment]
That's funny, this is exactly one of the first changes I made to my "NoCalendar" (or whatever I was calling it) anti-daylength branch. Matching game time progression up to wall clock time in an easier to measure way makes it easier to talk about in-game things in terms of wall clock time, like "this industry produced 208 cargo per minute" (instead of per month), and then you can decouple many game economy things from the calendar time progression.

Anyway, I wonder if the reason may also be related to the PC BIOS by default running the hardware timer at about 55 ms intervals, and if you double the speed of that you get 27.5 ms. Making the game run at a multiple of the default hardware timer makes it possible to just invoke the original timer routine every second tick.

For another speed-mismatch ticket, see #9814.

**Comment by DefinitelyNotRau117** [comment]
If tick=30ms is familiar to everyone and does not cause objective problems in our game, can it even be called a bug?
Making the game 10% faster by-default is a pretty massive change for the players.

**Comment by LC-Zorg** [comment]
> Running TTD(Patch) and OpenTTD side-by-side

Who runs OTTD and TTD at the same time today??? Does changing a very important element of the game for very rare, individual cases make any sense?
In addition to the matter of habit, there is also the issue of game performance, which is especially important in online games - many players will have to say goodbye to playing together sooner. 
I think it would be wrong to consider it a bug.

**Comment by nielsmh** [comment]
One cool thing about fixing this will also be that the release announcement can contain the line: "We made the game run faster!"

**Comment by andythenorth** [comment]
"Snappier"

**Comment by ldpl** [comment]
> One cool thing about fixing this will also be that the release announcement can contain the line: "We made the game run faster!"

How about making the game actually run faster instead of screwing it for silly announcements? :p
