### ISSUE TITLE
[Bug]: blue tint with hardware acceleration on

### ISSUE THREAD

**Issue by nitricware** [OpenTTD/OpenTTD#10251]
### Version of OpenTTD

12.2, macOS 13.0

### Expected result

Game should be playable normally without a blue tint.

### Actual result

Game starts up normally but has a blue tint.

~Terminal window throws the following error: `dbg: [driver] Could not change to foreground application. Error -50`~ (unrelated to the issue)

Running with `Intel Iris Plus Graphics 655 1536 MB`

### Steps to reproduce

1. install openTTD via `brew`
2. run `openTTD` from Terminal

### Solution

Turn hardware acceleration off

**Comment by michicc** [comment]
The debug message is expected when launching from the Terminal instead of the app bundle. This is some OS limitation that has no practical consequences.

No idea about the blue tint, except to try toggling hardware acceleration in the game options.

**Comment by nitricware** [comment]
Yes, thanks that did the trick. I thought the tint and the message were related.

**Comment by owen** [comment]
I can confirm, but for me it happens only when the game starts _without_ hardware acceleration.

With the driver reported as `cocoa` the screen has the blueish tint:
<img width="400" alt="OpenTTD launch page, blue tint" src="https://user-images.githubusercontent.com/784413/217029284-5a1828a9-7454-41a5-be64-bedbb2680f44.png">

When the driver is reported as `cocoa-opengl (Apple M1, 4.1 Metal - 83)`, everything looks as expected.

OpenTTD installed from Brew (OpenTTD 13.0) on a M1 MacBook Pro running MacOS 13.2

**Comment by TrueBrain** [comment]
Did a lot of experimental investigation into this. Turns out that for some reason the color space is not `RGBA` but `GRAB`. I never ever seen `A` not at the end, so something is pretty odd here. Will need further investigation.

**Comment by TrueBrain** [comment]
Right, this is only noticed by people installing via Brew, as it seems this was introduced in 12+. Seems Apple changed `kCGBitmapByteOrder32Host` from being a define to being an enum. As we had some code to still support old old MacOS, we changed the byte-order of our buffer from the correct 32-bit LE into the incorrect 16-bit BE (which seems to be the default, from "back in the day").

Which makes me to believe this only happens when people custom build their version and forget to set the OSX SDK to 10.13 (like we do for releases). And the reports in this topic seems to confirm that. In other words: if you use the 10.13 SDK, all is fine. If you use a 12+ SDK, things break.

We will fix this shortly :)
