### ISSUE TITLE
[Bug]: It is impossible to fit farms and forests on small sub-arctic maps

### ISSUE THREAD

**Issue by acanthite1855** [OpenTTD/OpenTTD#10337]
### Version of OpenTTD

12.2 (Windows 11, Mac M1 with BigSur 11.7.1), 12.1 (Android 9)

### Expected result

The game should be able to generate maps small (up to 256x256 size) with forest and farms in sub-arctic landscape style.

### Actual result

It is impossible to generate sub-arctic map of 64x64 size that contains forests and farms. Most of the time the issue is same for 128x128 maps. Rarely, but still reproducible for 256x256 maps. I haven't generate many maps bigger than 256, but for 512x512 or bigger maps it seems to be OK.

For example, on this map, there is clearly enough space to fit a farm and a forest, but none of them is there.
![image](https://user-images.githubusercontent.com/52529496/211840096-133a9971-f028-4beb-a894-bb6a851e7d1e.png)
I mean, look at how tight those industries can fit on a temperate climate map. It should not be a problem for sub-arctic maps as well.
![image](https://user-images.githubusercontent.com/52529496/211840596-c6117cec-c8df-4fa9-a2fc-5087b4973ac4.png)

### Steps to reproduce

1. Start the game
2. Go to Settings
3. Click Reset all values
4. Close Settings
5. Go to New Game
6. Set map dimensions to 64x64 or 128x128)
7. Click Generate

**Comment by LC-Zorg** [comment]
This problem has several causes:
1. Farms cannot be built on grass just below snow level (not visible with OpenGFX)
2. Forests can only be built on tiles that are completely snow-covered, although looking at trees that are covered with snow like forests, they could also be built 1 level lower than currently.
3. Terrain on small maps is very rough when set to high variety, even when the smoothness setting is specified as very smooth.

Solutions?
1. Allow the farm to be built 1 level higher if the attempt fails.
2. Allow the construction of a forest 1 level lower if the attempt fails.
2B. Allow forest to be built even lower, even on grass, if there is no snowy terrain available (keep preference for snowy and high terrain)
3. Adjust the smoothness setting to the size of the map so that the smooth option gives the result as it is named (rough is rough, smooth is smooth).

**Comment by 2TallTyler** [comment]
Even using the original landscape generator (as opposed to the newer TerraGenesis -- you can select in Settings), I can't get farms to generate on a 64x64 subarctic map with the default 40% snow coverage. I think your assumption that the game can use every economy at every size at default settings is understandable, but not necessarily true. If someone wants to open a PR to make this possible I'd be interested to see it, but I don't think this is a bug.
