### ISSUE TITLE
[Bug]: Ships loading at a dock block ships from leaving a depot on the adjacent tile

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#10490]
### Version of OpenTTD

13.0, Windows 11 Pro

### Expected result

White ships inside depot can leave.

### Actual result

White ships inside depot can't leave, because blue ships are full loading on the exit tile.

### Steps to reproduce

![Unnamed, 1989-12-11](https://user-images.githubusercontent.com/43006711/219754175-a8a5369f-98a0-405d-9de0-8f4d254b147d.png)

**Comment by 2TallTyler** [comment]
This is not restricted to competitors' ships. It also happens when the loading ship belongs to the same company.

**Comment by LC-Zorg** [comment]
This is not any bug! At least it's not a game bug. :) This is a feature that allows you to set spacing between ships without using the burdensome "auto-separation" feature. All ships do not leave the port at the same moment, but always at appropriate intervals. The same can be done for articulated vehicles (set depot before drive-through stop and set loading time) - very handy for city transport. Personally, I use it very often. Changing this would remove a useful feature.

The problem described here is mostly, if not exclusively, with one AI (AAAHogEx) which is pretty good but often does stupid things, and this is just one example. Generally, this AI has an annoying tendency to build too close to other companies. He often builds up entire quays with his harbours, shipyards and buoys, or raises the ground to build yet another harbour, and thus sometimes even blocks out other companies. So if anything should be changed it's the AI code, not the game.

Two another examples of what AAAHogEx AI does...
![AAAHogEx - spamming by the shipyards, buoys and docks](https://user-images.githubusercontent.com/67662046/219881156-dfd1500e-9459-460d-840f-dc7d8e49f01d.png)

![AAAHogEx - blocking the harbor](https://user-images.githubusercontent.com/67662046/219881244-4fcd5592-ccba-4b9c-b43c-d753d1eea0f6.png)

**Comment by LC-Zorg** [comment]
For ships, this is useful for fishing, for example. You can sail around many fisheries in turn by making loops with one larger vessel instead of many small for each fishery separately. Of course, not with one ship. However, spacing needs to be established. The method with the shipyard next to the dock works very well here. If new fisheries appear and more frequent trips are needed, all you have to do is change the stopover time in the first port and buy the appropriate number of ships.

**Comment by 2TallTyler** [comment]
Ah, a classic [xkcd: Workflow](https://xkcd.com/1172/).

The restriction of "don't leave the depot if a ship is already on the tile" is to avoid lots of ships calling the pathfinder simultaneously ([the code itself](https://github.com/OpenTTD/OpenTTD/blob/master/src/ship_cmd.cpp#L359-L361) says so).

Road vehicles blocking each other in depots is consistent with road vehicles taking up space. Ships, however, do not collide or take up any space, so this bug is inconsistent with how players expect ships to behave.

We previously fixed a related bug where ships stopped by a player would block depots, in #8578.

This one is a bug, not a feature, in my view. The correct way to space out ships is using timetables. (And to be clear, I want autoseparation as much as anybody; the current timetable system is horrible. But at least ships never get delayed by other traffic so timetabling is a bit easier.)

**Comment by glx22** [comment]
The "don't leave the depot if a ship is already on the tile" is just not explicit enough as it doesn't ignore ships owned by someone else.

**Comment by 2TallTyler** [comment]
I'd actually argue that it should check for ships that are currently loading (or maybe even broken-down), rather than just checking ownership.

**Comment by PeterN** [comment]
This is a bug, the intention is only that ships don't leave the depot while another ship is leaving the depot.

These blocking ships are not leaving the depot, therefore they should not block further ships leaving.
