### ISSUE TITLE
[Crash]: using make on debian to install most recent update crashes cmake

### ISSUE THREAD

**Issue by SackMathen** [OpenTTD/OpenTTD#10589]
### Version of OpenTTD

1.13 Debian 11

### Steps to reproduce

Following steps for Debian on this page:
https://wiki.openttd.org/en/Archive/Compilation%20and%20Ports/Compiling%20on%20GNU%E2%88%95Linux%20and%20%F0%9F%9F%89BSD#debian-package

### Upload crash files

i dont have crash files as it is a ssh server and It is difficult to access the files

**Comment by SackMathen** [comment]
i do have screenshots though:
![image](https://user-images.githubusercontent.com/75157855/229243023-40b59f85-0c5c-4703-a59d-d0b0a9a455bf.png)

**Comment by rubidium42** [comment]
It's not crashing cmake, but it is rather the compiler that is crashing. In any case, one of those tools crashing is almost always a bug in the tool, as the expectation of those tools is to give an error message of what is wrong instead of straight up crashing.
On the other hand does it crash, or does it just hang without progressing for a really long time? As "killed signal" seems to me like someone or something issues a "kill signal".

Regardless, neither cmake nor the compile should crash or hand indefinitely. And since the code got compiled by at least 3 different compilers and multiple versions of those compilers and none had an issue, it's unlikely to be a problem with the source code itself but rather a bug in the specific compiler your system has.
Or maybe it's a lack of memory and it's really slow compiling due to a lot of swapping?

**Comment by LordAro** [comment]
Going to close this as it's not likely an issue we can do anything about
