### ISSUE TITLE
[Bug]: Localisation settings - misleading tab title that specifies measurement units not localisation

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10595]
### Version of OpenTTD

13.0 (old bug)

### Expected result

The title of the tab refers to what the options contained therein refer to, i.e. the settings of measurement units.

### Actual result

![Localisation](https://user-images.githubusercontent.com/67662046/229589121-073e3fa4-5364-4e72-a6c4-854ea33ef3d5.png)

The title is unnecessarily confusing and can make it difficult to find the options that the player is looking for. For me, the current title still causes some consternation despite many years of knowing this window. Localisation? But the localisation of what? Gameplay localisation? It has nothing to do with it. This refers to the units of measurement used by the player or scenario author, but it does not mean that he used those that would be appropriate for the region presented in the scenario.

This isn't a major issue, but I'm reporting it by the occasion of other changes in this area (#10594).

### Steps to reproduce

n/a

**Comment by 2TallTyler** [comment]
Localisation refers to the player's perspective, not that of the game map/scenario. From [this article](https://www.babbel.com/en/magazine/what-is-localization) about localisation (emphasis mine):

> If you were to draw a Venn diagram of localization and translation, there would be a large amount of overlap. While the two aren’t exactly the same, localization almost always requires some amount of translation. And for its part, translation also requires some degree of localization for it to make sense.
> 
> The boundaries between these two concepts are hazy. To simplify it a bit, translation deals solely with the language part of the equation. Localization is about everything else, including cultural references, systems of measurement, currencies, regional terms, character names and more. The two work hand in hand to make for the most fluid experience for whoever encounters the media or product.

I could make the argument that currency should be part of this section, but whether and how to merge our separate Settings and Options windows is a different conversation.

In any case, localisation is an appropriate name for this section, since it also includes date format, which is typically a regional choice. Maybe there's a better name, and feel free to open a PR proposing such a change, but the current name is not a bug.
