### ISSUE TITLE
[Bug]: Console Doesn't Close on multiplayer games

### ISSUE THREAD

**Issue by dingolingo112** [OpenTTD/OpenTTD#10646]
### Version of OpenTTD

1.30/1.31

### Expected result

Usually the console has no issues opening or closing on my main pc which runs windows 10

### Actual result

The Console on my ASUS Laptop which runs windows 11 seem to have issues requiring to press the key to open it twice and then getting stuck requiring you to restart the game. not sure if this is an operating system issue or some other issue I have not tested to see to it happens on singleplayer.

### Steps to reproduce

Go into a multiplayer server
Press the ~ key or whatever key you use to open the console then try pressing it again.
trying pressing said button again to see if it closes.

**Comment by TrueBrain** [comment]
You can always close the console via the menu (under the question-mark, all the way to the right, `Toggle Console`.

I have the exact same issue, just never bothered to look into it; for me, it has to do with the dead-keys on Windows, meaning that you can type ` followed by an e to get è. If I switch to a keyboard layout that doesn't have dead-keys, it works fine.

**Comment by rubidium42** [comment]
As TrueBrain says it's very likely due to the so-called [dead keys].(https://en.wikipedia.org/wiki/Dead_key)

You can probably see the same behaviour here in your browser. If you press the \` once, it will not appear but if you press it another time likely two appear, so it might be that due to receiving two \`s OpenTTD closes and then reopens the console within the same drawing cycle. By pressing the \` and then pressing the spacebar you can likely get single \`s. If that works, then that's the way to close the console in OpenTTD.

OpenTTD itself cannot do anything about dead keys. The operating system handles the physical keyboard, and the operating system sends OpenTTD what keys have been pressed, however if a dead key is pressed it does not send anything to OpenTTD. It will send the (potentially) combined key when the next key is pressed, making it look like (to OpenTTD) that the keyboard has more keys than it physically has.

**Comment by 2TallTyler** [comment]
Closing this as there's nothing we can do about it, and players experiencing this problem can toggle the console via the GUI.
