### ISSUE TITLE
[Bug?]: Pristine company with no assets and no cash on hand still has expenses

### ISSUE THREAD

**Issue by ketsuban** [OpenTTD/OpenTTD#11256]
### Version of OpenTTD

13.4, Windows 11

### Steps to reproduce

1. Start a new game.
2. Open the finances window.
3. Unpause.
4. Immediately pay off the initial £100,000 loan, leaving a company with no assets, no income and no cash on hand.
5. Wait.

### Expected result

No expenses. The company remains at zero dollars in the bank with zero outstanding loans and zero infrastructure.

### Actual result

The company goes into debt to the tune of £25 per month in the "other" category and a small "loan interest" of approximately £30 p.a. The former seems like it could be intentional, but I couldn't find where in the code it's applied to document it on the wiki; the latter seems more likely to be a bug.

**Comment by James103** [comment]
This line is here (in various forms) since svn r1 and likely before, most likely to preserve original TTD behavior and ensure inactive companies eventually go bankrupt.
https://github.com/OpenTTD/OpenTTD/blob/7e544180222d6c19441c3b4c7ef3bfe821e671b7/src/economy.cpp#L852

If removed from the code, it can easily be re-added with a Game Script.

**Comment by TrueBrain** [comment]
As @James103 pointed out; a company always has "some" expensive .. call it paying your bookkeeper. And this is the price of 1/4th of a station tile. Just a random number. Comes down to 25 pound a month.

And as you slip in to negative money, you also start having to pay loan over that. After all ... someone is bankrolling you when you go negative. That bookkeeper is being paid by someone. And that someone you have to pay some interest. So slowly the interest starts to build up. It is only 3 pound the first year. It takes a few years before it is 30. And it will keep on increasing :)

This is fully intentional / by design. So I disagree with your expected result :) I expect it to be impossible to have 0 expenses a year; let alone you having free money (as in, negative bank balance). Things cost money in this world! OpenTTD isn't an exception :D

(and yes, the game-design reason behind this is to make sure when you do absolutely nothing, you still go bankrupt; you have to do something in this game)

Hope that clear it up! Let me know if you want other things cleared up :)
