### ISSUE TITLE
[Bug]: Vehicle max age in years calculated incorrectly

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#11270]
### Version of OpenTTD

e4fd99a

### Expected result

Vehicle max ages shown in years, in the buy menu and vehicle details windows, are correct.

### Actual result

![Droddown_End_Transport_1967-03-01](https://github.com/OpenTTD/OpenTTD/assets/55058389/9b239960-a2d7-4ef6-af51-31b35ac37213)

The max age is one less than it should be.

### Steps to reproduce

I broke this in #11174. Oops.

It's also affected by #11173.

**Comment by PikkaBird** [comment]
I know 2TT knows what he meant and intends to fix this bug himself, but for the avoidance of confusion this bug concerns the displayed vehicle lifespan / "maximum age", rather than "current age".

**Comment by TrueBrain** [comment]
And to add what I wrote about this on Discord: depending on where you look in the game, a year had 365, 366 or "depends on the year" amount of days. This most likely is caused because one end multiplies it with 365, the other divides it with 366, giving an "off by one" for these values. If you would have a max-age of like 1600, it might be off by 2. So it isn't just a simple "+ 1" or something. I think. :)
