### ISSUE TITLE
[Bug]: ships don't collide with each other

### ISSUE THREAD

**Issue by hylloo** [OpenTTD/OpenTTD#11365]
### Version of OpenTTD

13.4 Windows 10

### Expected result

If ships collide, they should either crash or choose a new path.

### Actual result

Ships pass through other ships without collision, unlike other vehicles.

### Steps to reproduce

Create two ships and put them on a route where they collide.

**Comment by hylloo** [comment]
Fixing this can be done by adding collision to ships or force ships to find new route if going to collide.

**Comment by TrueBrain** [comment]
This is not a bug, and fully intentional.

Imagine a single-tile channel, and two ships entering from both sides. They will meet up, and ... have to turn around. This will be rather frustrating to play. This, and a few technical reasons, are the reason we allow ships to pass through each other. It just makes for a better game.

**Comment by 2TallTyler** [comment]
I had a PR that made ships yield when passing through each other, like trains in Railroad Tycoon 3. The idea was to incentivize players to route ships around each other using buoys, but the ship pathfinder is so imprecise (a ship considers a buoy reached if it gets within a few tiles) that it was mostly just frustrating. Players can still set up such routing schemes if they want, we don't need to force them. 

https://github.com/OpenTTD/OpenTTD/pull/8574
