### ISSUE TITLE
[Bug]: Code contains 3rdparty software without simple opt-out

### ISSUE THREAD

**Issue by pemensik** [OpenTTD/OpenTTD#11403]
### Version of OpenTTD

master, 7b4ecb52415f16fd4c776559e75729a2ddad7909

### Expected result

[Fedora Packaging guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling) contains a rule about bundling libraries. If they can be omitted, they should be omitted. After looking into src/3rdparty directory, I have found quite a lot of bundled libraries.

Problem is they cannot be avoided when the same library is present on the system. Such as when it is packaged in linux distribution. At least I haven't found simple way to do it.

### Actual result

If the system can provide appropriate libraries, they should be used from the system.

Fedora has packages for:
- fmt
- json (nlohmann/json.hpp)
- squirrel (modified)

From what I have understood it is not possible to use vanilla squirrel language, but it should be possible for fmt and json to use system library. If it needs specific version, CMake can solve it. I think 3rdparty should be used only when system does not provide them.

### Steps to reproduce

- remove src/3rdparty/fmt and src/3rdparty/nlohmann
- remove references to them from src/3rdparty/CMakeLists.txt
- the game should build if json-devel and fmt-devel are installed.

**Comment by TrueBrain** [comment]
I am happy to read that Fedora has a packaging guide, but honestly .. we want to make it as easy as possible for as many people as possible to get going in OpenTTD. We do not tailor to a single distribution. And this means we sometimes vendor libraries, just because it is more practical for most people; not just a select few.

Vendoring a library is always a balance, and a discussion. First off, we only vendor libraries that are mandatory for building OpenTTD. All optional libraries are (on Linux anyway) using system libraries. This because if you have a library that is too old on your system, you can still compile the game; just without that optional library. lzma is a nice example of this: although you really want this, and it is almost considered required, we still don't vendor it, as you can build without. And if you don't have it, building just works. With a big fat warning you really want lzma, but the game will run fine without .. except for loading most savegames :P

So for the required libraries, we always first try to use vcpkg (for MacOS and Windows) and system libraries (for Linux). But sometimes this just isn't practical. Popular distros tend to lag behind in terms of what version they ship; and you can't expect us to support version (insert one from 3 years ago), just because there is a popular distro that doesn't ship with anything more recent.

So for those cases we vendor the library. And always after discussion.

- `squirrel`, as you noted, is a heavily modified version. Fedora doesn't have this variant, nor will they ever have this variant. It is called `squirrel`, but really, by now, it is neither Squirrel 2 nor Squirrel 3. It became its own thing. It is only still in `3rdparty` because there is nothing better. But this is not a vendored library. This is a heavily modified library.
- `fmt` and `nlohmann` are both required to build OpenTTD. But most Linux distros do not have a version that is recent enough for them to be useful. Additionally, `nlohmann` on vcpkg isn't doing what we expected in all cases. So what we are left with is vendoring it. Further more, as these are both header-only, there is far less of an issue. And we tend to update the version more often than most distros do.

So in short, although I appreciate Fedora Packaging has a guide to tell people what they should and shouldn't do, in reality, they only have themselves to blame that we vendor libraries. Most distros, Fedora no exception but also not the only one, simply don't update these kind of libraries often enough to be useful for normal software development. Expecting software to support some ancient version of a library is just not efficient, and a total waste of time on our side of the table :) Especially for header-only libraries like `fmt` and `nlohmann` :)

In your words: "I think 3rdparty should be used only when system does not provide them." Exactly this is what is happening. Just our scope is bigger than just Fedora :)

Don't take this the wrong way, I understand the "purity" of the argument. But we have to be practical. We only have so much resources available to work on this awesome game. Fighting distros, and what they do and don't like, isn't high on the priority list. Making sure anyone who drops by can clone the code and "just" build it however, is. As that results in more contributions, and a better game for all.

I hope you understand :)

PS: a really long story of saying: sorry, not going to address this issue :)
PPS: even if you have `fmt` or `nlohmann` installed on your system, it will still pick our version. So there is never a conflict. And as a bonus, our version is most likely newer than the distros anyway!

**Comment by pemensik** [comment]
It is possible to choose the system package only if it is recent enough. CMake's ``find_package()`` makes it simple enough. I am pretty sure other linux distributions have similar rules. If the package can use something packaged already, it has to  use it. It makes overall less duplications and possible fixing on multiple places.

[fmt](https://src.fedoraproject.org/rpms/fmt) package is recent enough on upcoming Fedora 39 and onwards. It is not header-only library by default anymore. I don't ask to make build unfriendly to users. But for example bundled Catch2 is old version 2, where version 3 [is available](https://src.fedoraproject.org/rpms/catch) (and incompatible).

I kind of understand working with unchanging version is easier for you. Let me provide some implementation to review.

**Comment by TrueBrain** [comment]
Although I respect the effort you put into this, the problem with an approach like your PR, it adds technical debt for us, which we have to maintain, where it only adds "value" for a very very small amount of people. This is not a good balance to strike. It cannot be that we have to spend more time maintaining things over a policy of a single distro.

To put it in an example, we currently use fmt 10. fmt 10 is only (!) available on upcoming Fedora 39 and Arch Linux. Ubuntu doesn't have it. Debian doesn't. No other rpm-based distro has it. Further more, it is likely that if fmt 11 lands, we will update. And at that point Fedora also won't have it anymore.

So the amount of time the system library can actually be used, is in such rare cases, that supporting that for us is impractical. We tend to not have code we don't test ourselves, so we would need to setup a CI that creates a situation where the system library would be used. And that again pushes the maintenance burden to us.

And then you have to ask, what does it actually solve? For a library we dynamically link to, arguments can be made. The distro can update it without updating the game, etc etc. But for a header-only library this argument simply doesn't fly. As the code is already compiled into the binary. So what does it solve to use the system library over our vendored one? Except for more surface problems can arise from, and more places we have to delve into when reports arrive.

This is just to re-iterate what I wrote above: we have limited resources and have to balance what works. Adding code to create a possibility for a single distro to possibly, maybe, sometimes, use a system library over our vendored, just isn't a balance that is fair. And even more, if the distro decide to change that library for what-ever reason (and they do that from time to time), we will get the complaints. This simply isn't a good idea. Especially as there is nothing wrong with vendoring header-only libraries in the first place.

I think someone summarized this nicely yesterday: this PR (and ticket) is about a theoretical purity point. It isn't practical, nor does it actually solve anything. So again, I do appreciate the effort, but it is simply not worth our resources.
