### ISSUE TITLE
[Bug]: Articulated parts of a locomotive don't use locomotive company colours

### ISSUE THREAD

**Issue by Brickblock1** [OpenTTD/OpenTTD#11438]
### Version of OpenTTD

Current master, windows

### Expected result

The colour of the articulated part of the locomotive matches that set in the company colour settings 

### Actual result

It uses wagon colour instead
![image](https://github.com/OpenTTD/OpenTTD/assets/100433052/aaee4894-c1b3-4f7f-9ad5-51bfba3d19ef)

### Steps to reproduce

1) Start a new game with the provided newgrf
2) Buy the MZ II and refit it to "2CC" 
3) Change the company colour of the wagons to something different than the one for locomotives.
[openttd_bugs.zip](https://github.com/OpenTTD/OpenTTD/files/13257557/openttd_bugs.zip)

**Comment by krysclarke** [comment]
Isn't the choice of which livery option is used for each vehicle something the author of the NewGRF makes?
In other words, has the author of the NewGRF you're using chosen to make the MZ II use the Diesel passenger coach livery colours instead of the Diesel Engine ones?

**Comment by Brickblock1** [comment]
This isn't possible to change while still conforming to the spec

**Comment by PikkaBird** [comment]
The usual way to encode articulated locomotives is to use the same ID for all parts, using callbacks to set the vehicle length and visual effect as required. Most other stats (eg power and weight) are automatically set to 0 for articulated parts.

Alternatively, you might try giving your second part some power, so it is recognised by the game as a locomotive rather than a wagon. When built as an articulate the power stat will automatically be 0ed.

**Comment by Brickblock1** [comment]
I guess the nml wiki is wrong then since it says it should be set to zero

**Comment by Brickblock1** [comment]
It doesn't work when I set it to 1 either tho so I can't get the articulated part to use the locomotive 2CC at all which isn't ideal. The grf spec should probably be extended to allow this unless the behavior is changed so that all articulated parts are considered locomotives but that has its own problems.

**Comment by PikkaBird** [comment]
As discussed on Discord, a rail vehicle is a wagon for CC purposes if its power property = 0, and a locomotive otherwise. This applies whether the vehicle is built as part of an articulated set or individually, and allows maximum flexibility for newgrf authors.

Since power, and most other stats, are automatically 0ed when a vehicle is an articulated part, the simplest solution for the newgrf author is to use the same vehicle ID for every part of an articulated locomotive, and use a position_in_articulated_veh switch to set the graphics (and, if necessary, the length and exhaust effect) for each part.

**Comment by ldpl** [comment]
NewGRF spec is totally non-ambiguous and states in "should be zero" which is clearly not true in this case.

**Comment by PikkaBird** [comment]
> NewGRF spec is totally non-ambiguous and states it "should be zero" which is clearly not true in this case.

But what does "should be 0" mean? And if those stats are automatically 0ed for articulated parts, what's the difference between "should be 0" and "no"?

As I said on Discord, if people are _determined_ that the spec says only wagons are allowed to be used as articulated parts, they shouldn't be surprised that all their articulated parts are wagons. If you want your articulated part to be coloured as a locomotive, code it as a locomotive - it's simple, it makes sense, and it's how grfs have been coded for years. 

There is no bug here. If changes are required to align the game behaviour and the information on the newgrf wiki, the wiki is where they should be made.

**Comment by ldpl** [comment]
I don't see any other way to interpret "should be 0" on [this page](https://newgrf-specs.tt-wiki.net/wiki/Action0/Vehicles/Trains) than "this property should be set to 0 in Action 0". I do agree though that it's probably wiki that should be changed in this case, not the game.

**Comment by Eddi-z** [comment]
"Should be 0" is specs-lingo for "this is intentionally left open for future extensions"

**Comment by PikkaBird** [comment]
Well, in this case it's been "left open for future extensions" for about 20 years, and it's already the case that, in the case of power at least, not setting it to 0 has an effect. So the documentation definitely needs updating. :)

**Comment by Eddi-z** [comment]
I'm not a big fan of treating the spec as "this is what's happening in the current implementation". there's a bigger discussion to be had here.

for example, there once was a suggestion to handle dual-power engines by having two articulated parts having different powered railtype (and their accociated power contribution). that possibility would be erased if you simply specified "non-zero values will be zeroed by the game."

i'd be more favouring a separate (new) flag indicating which category the vehicle will be put in (engine, wagon, multiple unit, ...) instead of relying on such an auto-detection and weird corner cases like "powered wagons" and other complications which more look like a fractal of hacks upon hacks.

**Comment by PikkaBird** [comment]
Perhaps. I think the spec might be more *useful* to newgrf authors if it reflected reality, rather than someone's decade-old wishful thinking.

In any case, the point is this is not a bug per se and should be closed. If someone wants to open a PR for manual livery categories, dual-power articulates, or whatever else in the future, they can.

**Comment by ldpl** [comment]
Game behaving differently from the spec is a bug and should be resolved one way or another.

**Comment by Eddi-z** [comment]
"unspecified behavior" is something very different from a "bug"

**Comment by andythenorth** [comment]
Is this a duplicate of #10146 ?

**Comment by Brickblock1** [comment]
Yes, it is

**Comment by Brickblock1** [comment]
Yes, it is
