### ISSUE TITLE
[Bug]: Error while creating bundle on macOS

### ISSUE THREAD

**Issue by Zollerboy1** [OpenTTD/OpenTTD#11476]
### Version of OpenTTD

git master branch, macOS 13.4.1

### Expected result

I'm trying to install OpenTTD from source using cmake/make. I expected to build and install the app without errors.

### Actual result

When I'm running make install, I'm getting the following error:

```
-- fixup_bundle
--   app='/PATH/TO/CLONED/OpenTTD/build/install/../MacOS/openttd'
--   libs=''
--   dirs=''
--   ignoreItems=''
-- fixup_bundle: preparing...
-- fixup_bundle: copying...
-- 1/6: *NOT* copying '/PATH/TO/CLONED/OpenTTD/build/install/../MacOS/openttd'
-- 2/6: copying '/usr/local/opt/libpng/lib/libpng16.16.dylib'
-- 3/6: copying '/usr/local/opt/lzo/lib/liblzo2.2.dylib'
-- fixup_bundle: fixing...
-- 4/6: fixing up '/PATH/TO/CLONED/OpenTTD/build/install/../MacOS/openttd'
-- 5/6: fixing up '/PATH/TO/CLONED/OpenTTD/build/Frameworks/libpng16.16.dylib'
  exe_dotapp_dir/='/PATH/TO/CLONED/OpenTTD/build/install/../MacOS/'
  item_substring='/PATH/TO/CLONED/OpenTTD/build/Frameworks/libpng'
  resolved_embedded_item='/PATH/TO/CLONED/OpenTTD/build/Frameworks/libpng16.16.dylib'

Install or copy the item into the bundle before calling fixup_bundle.
Or maybe there's a typo or incorrect path in one of the args to fixup_bundle?

CMake Error at /usr/local/Cellar/cmake/3.27.6/share/cmake/Modules/BundleUtilities.cmake:851 (message):
  cannot fixup an item that is not in the bundle...
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.27.6/share/cmake/Modules/BundleUtilities.cmake:983 (fixup_bundle_item)
  cmake_install.cmake:109 (fixup_bundle)
```

### Steps to reproduce

After installing the dependencies (`brew install xz libpng lzo`) try to build and install OpenTTD like this:

```
git clone https://github.com/OpenTTD/OpenTTD.git
cd OpenTTD
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=./install ..
make
make install
```

**Comment by TrueBrain** [comment]
Sorry for the late reply; I think it is mostly because only a few of us every compile on MacOS, and never ran into this problem. Our CI create MacOS binaries daily, and I never seen this issue popup there.

The text you copy don't actually show an error, and everything appears to work as expected. The files are copied, and then fixup is ran over them. Seems fine by the looks.

What we don't test with however, is `brew`. We found out that [vcpkg](https://github.com/microsoft/vcpkg/) is much easier to deal with. Maybe give that a try?

Otherwise, you are a bit on your own here. You will have to dig in a bit and see what breaks. Let us know what you find out!

**Comment by TrueBrain** [comment]
Going to close this for now. If you discover anything new, do let us know!
