### ISSUE TITLE
[Bug]: Storybook duplicates some words when wrapping

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#11485]
### Version of OpenTTD

13.4

### Expected result

When using a Game Script like Renewed Village Growth, the storybook text wraps properly.

### Actual result

![wrap_double](https://github.com/OpenTTD/OpenTTD/assets/55058389/e4169654-e2b0-40f4-b7dc-453a3fc3298b)

The word "faster" is repeated on the next line, when it is the last word in the row and is near the edge of the window. This requires resizing the window.

Oddly, no other words in this window seem to do this.

The [string in question](https://github.com/F1rrel/RenewedVillageGrowth/blob/master/lang/english.txt#L42):
```
STR_SB_WELCOME_CARGO     :Economy {SILVER}{STRING}{BLACK} consists of {SILVER}{NUM} categories{BLACK}. To fulfill a category, deliver one or more of the category specific cargos to a {ORANGE}station near the town which accepts that cargo type{BLACK}. Fulfill the requirements above {SILVER}{NUM}%{BLACK} to {ORANGE}make the towns grow faster{BLACK}. More information about cargo categories are shown in the {ORANGE}Cargo categories story book page{BLACK}.
```

### Steps to reproduce

1. Start a new game with the "Renewed Village Growth 9.2" game script.
2. Wait for the Story Book window to open.
3. Change the width of the window until the word "faster" is duplicated on two lines of text.

**Comment by PeterN** [comment]
It happens with "list" in "Goal list" too, and other places.

The trigger seems to be when the line is wrapped at a colour change instead of a space.

**Comment by TrueBrain** [comment]
As @PeterN already mentioned, but maybe a bit more insight to it:

If I remember correctly, and the code seems to support that, every colour (and font) change is considered a breakable point. Which works excellent for most of OpenTTD's provided strings, as we don't do the kind of things you are doing here :) It is basically meant to keep coloured words on a single line when possible, and sentences in OpenTTD itself rarely end with a dot, so that works out perfectly for us. Not for you :P

The reason I mention this, as although I am sure we are fully capable of fixing this bug, it can result in another issue where the dot ends up on the next line :P As there is a transition in colour, which is seen as a breakable point. So this behaviour might need a bit of reconsidering, or maybe even special-casing.

For reference, the culprit:

https://github.com/OpenTTD/OpenTTD/blob/c5a292c0df0a2fc916991c87d29b2fff2eaefa75/src/gfx_layout.cpp#L110
