### ISSUE TITLE
[Bug?](WIN): KERNEL32.dll Problem that makes OpenTTD stop working

### ISSUE THREAD

**Issue by ghost** [OpenTTD/OpenTTD#11529]
### Version of OpenTTD

OpenTTD Version 13.4 on (Windows Vista Starter x86 [NT6.0] Build 6003: Service Pack 2)

### Expected result

OpenTTD will open up, downloading some extra files before proceeding into the menu

### Actual result

After pressing continue, an error appears
Window: openttd.exe - Entry Point Not Found
Msg: The proedure entry point TryAcquireSRWLockExclusive could not be located in the dynamic link library KERNEL32.dll

#### 2.5- The first try will be without installing all of the available updates.
- In my case, it is with all of the Updates installed (including the Windows Server 2008 and Platform Update ones)
### 6- The error appears with the forced Windows Classic appearance (openttd.exe - Entry Point Not Found)
![image](https://github.com/OpenTTD/OpenTTD/assets/77538136/ff306659-c549-4d27-b58f-23e751ffda46)

#### 6.5 - No crash or save files have been created, _but this is listened in the Windows Event Viewer_:
 _Faulting application openttd.exe, version 13.4.0.45642, time stamp 0x64c59d58, faulting module KERNEL32.dll!TryAcquireSRWLockExclusive, version 6.0.6003.20555, time stamp 0x5cefed6b, exception code 0xc0000139, fault offset 0x00009fad, process id 0xf18, application start time 0x01da2543988f36d0._
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
 <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2023-12-02T17:19:10.000Z" /> 
  <EventRecordID>955</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>NicoDM-Starter</Computer> 
  <Security /> 
  </System>
<EventData>
  <Data>openttd.exe</Data> 
  <Data>13.4.0.45642</Data> 
  <Data>64c59d58</Data> 
  <Data>KERNEL32.dll!TryAcquireSRWLockExclusive</Data> 
  <Data>6.0.6003.20555</Data> 
  <Data>5cefed6b</Data> 
  <Data>c0000139</Data> 
  <Data>00009fad</Data> 
  <Data>f18</Data> 
  <Data>01da2543988f36d0</Data> 
  </EventData>
  </Event>
```

**Comment by TrueBrain** [comment]
Windows Vista has been EoL for over 11 years. This means two things:

1) we (as developers) don't test on OSes that are that far EoL.
2) very few users still use it to play the game.

Although we tend to not deliberately break compatibility with such old OSes, when they break, solving it is nearly impossible for us. The breaking most of the time happens because MSVC (the compiler from Microsoft) produces binary that use calls that are no longer supported by an OS like Vista.

As we don't test for those OSes, and very few people play on it, it can take years before a report reaches us mentioned it is no longer working. So honestly, I couldn't tell you if it broke last month, of 6 years ago. Sadly for you, our solution is to no longer mention we support Vista.

The best course of action for you is either of two things:

- Update to an OS that hasn't been out of support for more than 11 years ;) And, if not practical:
- Download a (much) older version of OpenTTD. You will have to use trial&error to figure out what the last working version was.

Sorry, but it is just not reasonable for us to spend a our limited resources on an OS that is that old, and used by that few people.

**Comment by NicoBR333** [comment]
> Windows Vista has been EoL for over 11 years. 

Actually it's been EoL for 6 or (very close) to 7 years, **but close enough**

Despite that, thanks for the clarification. 
It seems like the issue might have happened since the last version from Windows XP, but maybe I can test it to see

**Comment by NicoBR333** [comment]
_I have just tested_ and its latest version working on Windows Vista is **version 13.0-beta2**, or **12.2 for the stable build**
