### ISSUE TITLE
[Bug]: SDL_default_v:  Failing to get window surface under Wayland

### ISSUE THREAD

**Issue by M3Henry** [OpenTTD/OpenTTD#11714]
### Version of OpenTTD

13.4 archlinux-aarch64 / 06a5fa6239a116f1fd616048b9e0d69493f2a1c8

### Expected result

SDL video driver is expected to work

### Actual result

> $ openttd -v sdl
> Error: SDL2: Couldn't get window surface:

Game does not run

> $ openttd -v sdl-opengl

Game runs, albeit slowly

### Steps to reproduce

Running under Wayland (sway) on a PineTab2 (aarch64).

Removing Framebuffer acceleration hint allows the game to run with the standard `sdl` video driver.

```
src/video/sdl_v.c:511
-        SDL_SetHint(SDL_HINT_FRAMEBUFFER_ACCELERATION, "0");
```

Performance is interesting:
sdl-opengl manges 10FPS, most of which is spent on Rendering.
sdl manages 40FPS, most of which is spent in Video Output.

**Comment by TrueBrain** [comment]
We hint `SDL_HINT_FRAMEBUFFER_ACCELERATION`, as we don't need 3D acceleration. That it causes the SDL driver to not be able to find a window surface, almost sounds more like an SDL issue than an OpenTTD issue. Removing that line causes other people to have SDL issues.

So the question is: what is the problem below this problem. And sadly, without access to an aarch64 device, that might be hard to track down.

There are several SDL versions where things were a bit broken in regards to `SDL_HINT_FRAMEBUFFER_ACCELERATION` and `-v sdl`. So I guess the main question is: what SDL version is this with, and can you try to update the SDL and see if the problem still exists?

**Comment by M3Henry** [comment]
SDL version is 2.28.5, which is the latest available.
That said, things did work previously. So it may be a regression in SDL.
I have previously had the following SDL versions:

2.26.5 <- untested, I don't have this package in my cache any more. It definitely worked with OTTD 13.1 at the time.
2.28.0 <- tested: not working
2.28.1 <- tested: not working
2.28.2 <- tested: not working
2.28.3 <- tested: not working
2.28.4 <- tested: not working

**Comment by TrueBrain** [comment]
Did some digging, as the `SDL_HINT_FRAMEBUFFER_ACCELERATION` was not sitting well with me.

Turns out, about 2 years ago they made a change in SDL how `SDL_HINT_FRAMEBUFFER_ACCELERATION` is processed. My SDL is slightly older (2.20), and when I compile with a newer version, I get the same issue. I have yet to delve into what they actually changed what that hint is doing. To be continued.

**Comment by TrueBrain** [comment]
Long deep searching later, I couldn't find the commit in SDL that would actually have broken it. But also, the hint is no longer required because we also run OpenGL in the same code (which does need a hardware accelerated surface). So I am 90% sure we already fixed the issues that caused that hint to be there. So indeed, a solution seems to be to just remove the hint. Tnx for mentioning it in your issue, it really saved a lot of time on my end :)
