### ISSUE TITLE
[Bug]: River graphics for mars?

### ISSUE THREAD

**Issue by NastyFlytrap** [OpenTTD/OpenTTD#11718]
### Version of OpenTTD

13.4 Win10 64gbit

### Expected result

Canals not looking out of place

Would it be possible for someone to create martian canal graphics and autoload it when the conversion is loaded? Even without the error its a bit ugly

### Actual result

Temperate canals on toyland with martian conversion

### Steps to reproduce

Install toyland2mars
(get error)
look at canals

**Comment by reldred** [comment]
That's a bug for toyland2mars to resolve, not for OpenTTD...

(For what it's worth, that .grf was made for TTDpatch before Canals or OpenTTD even existed...)

**Comment by EmperorJake** [comment]
The canals in toyland2mars work fine though (see my screenshot - toyland2mars is the only GRF loaded). The NewGRF complains with an error message for some reason, probably TTDPatch related. There are no river graphics though, since this was created long before rivers existed. 
<img width="596" alt="image" src="https://github.com/OpenTTD/OpenTTD/assets/68182631/722c5a4b-c418-4690-bf3c-bc68cdccf344">

**Comment by TrueBrain** [comment]
This bugtracker is about issues with OpenTTD itself, not with third party content or feature requests. Please contact the author of the content to make this request.

Alternatively, you can check out the forums (https://tt-forums.net) to see if someone can help you out, or alternatively out Discord.
