### ISSUE TITLE
[Bug]: Inflation continues if the calendar is set back, even if 170 years of it have been applied.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#11969]
### Version of OpenTTD

bc4ed9085d on Windows 10, 64-bit (via Steam)

### Expected result

When the calendar is set back, one of two things should happen if inflation is turned on:
* Inflation is recalculated to match the new calendar date.
* Inflation is paused until the calendar catches back to the date from which it was set back.

### Actual result

When the calendar is set back, the level of inflation remains the same and continues to increase if the new calendar date is between 1920 and 2090. This can cause inflation to be applied for more than 170 years.

### Steps to reproduce

1. Start a new game in 2090 with inflation enabled, ideally on a small map.
2. Notice 170 years worth of inflation are immediately applied.
3. Use the sandbox options to set the calendar date to 1920.
4. Fast forward several years (calendar time).
5. Notice inflation continues to be applied, even though 170 years of it have already been applied.

**Comment by TrueBrain** [comment]
If you shoot yourself in your foot it tends to hurt.

Best I can offer you that we add this to known bugs. But inflation is for several reason a rather broken mechanism that can only be fixed by replacing it completely.

So tnx for the report, but this is what it is. Years between 1920 and 2090 generate inflation, no matter how you got there. So if you keep jumping back, you will get to some amazingly huge numbers :)
