### ISSUE TITLE
[Bug]: Show vehicles order (the window is very wide)

### ISSUE THREAD

**Issue by Ufiby** [OpenTTD/OpenTTD#11983]
### Version of OpenTTD

20240203

### Expected result

![GIF 04 02 2024 14-09-52](https://github.com/OpenTTD/OpenTTD/assets/46504018/bc282259-822b-4d76-b682-7480c49caae1)

### Actual result

![GIF 04 02 2024 14-17-21](https://github.com/OpenTTD/OpenTTD/assets/46504018/45c95870-991f-40b6-aa90-ea8bc2355bbd)

### Steps to reproduce

NewGRF: eGRVTS 2.1, Mop ERV 9.3.0

**Comment by rubidium42** [comment]
This might be caused by the same underlying issue that was solved with #11973.

The problem solved with #11973 is that some string parameter isn't initialised correctly when getting the minimum size of the widgets for this window. This means that another "random" string might be used, and that could conceivably cause such an issues. It's hard to know for certain though.

It would be interesting to know if you still can reproduce it with the nightly that should have been created in about 8 hours.

**Comment by Ufiby** [comment]
This is just my outdated saved game. I started a new game and nothing happened. All right
