### ISSUE TITLE
[Bug]: #11959 "easy/medium/hard" AI setting randomisation is being applied to GS configuration

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#12182]
### Version of OpenTTD

Since #11959

### Expected result

It should be possible to configure GS parameter values.

### Actual result

It doesn't seem to be possible to configure GSs without randomised offsets being added.

### Steps to reproduce

Add and configure a GS which uses parameters
e.g. "Renewed Village Growth" or Villages Is Villages"

**Comment by glx22** [comment]
Expected, since easy/medium/hard are now replaced with default.
The conversion is basically `default = medium` and `deviation = hard - easy`.

**Comment by TrueBrain** [comment]
As mentioned, but with a bit more words: this is not actually a bug, and the result of two changes (not only the one mentioned in OP).

Before 14.0, when a GS author would set a deviation, it would not be shown to the user. Instead, they would only see the mean value, and on game-start, it would apply the deviation, showing a totally different number. This is very confusing to the user, and as such, now a range is shown between which the value will be after starting a game. This is a much more informative way to tell about the mean/deviation (instead of only the mean).

Secondly, we finally removed the last bits of "difficulty", often called AI difficulty, which was also applied to GSes. Before 14.0, a GS could set an easy/medium/hard value to be applied when that difficulty was used. With 14.0, this is changed into a deviation, with `medium` as mean, and `hard - easy` as deviation. And that is what you now see with most GSes, as they actually set different values for easy/medium/hard.

So by no means the reported issue is a bug, as it is fully intentional. However, if it is wanted behaviour, that is a bit of a different story. The thing that is currently a bit annoying, that the user cannot change the deviation, but only the mean value. That might be worth adding, that you can also change the deviation to something different. But interface-wise that would become crowded really quick.

Of course completely open for different ideas / approaches.

**Comment by TheMowgliMan** [comment]
Idea: one bool setting, which enables/disables random deviation. You could
also add a second bool setting to enable/disable it for just GS.
