### ISSUE TITLE
[Crash]: during pathfinding with ships

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#12236]
### Version of OpenTTD

OpenTTD 20240308-master-g5806c2aba4 (custom build)

### Steps to reproduce

I left the game with some AIs running, and it crashed.

### Upload crash files

[crash20240308161842.zip](https://github.com/OpenTTD/OpenTTD/files/14540585/crash20240308161842.zip)

**Comment by TrueBrain** [comment]
This appears to be a custom build binary, and not actually the above mentioned version. Please, if you use custom build, do the work and show a traceback etc. This crash-dump is totally useless to us.

Anyway, the issue seems to be:

`Assertion failed at line 266 of D:\\OpenTTD\\OpenTTD GitHub\\OpenTTD\\src\\pathfinder\\yapf\\yapf_ship.cpp: !path_cache.empty()`

**Comment by SamuXarick** [comment]
This was not a custom build.

**Comment by TrueBrain** [comment]
Are you willing to put any money on that? Let's see ...

Build path: `D:\\OpenTTD\\OpenTTD GitHub\\OpenTTD`
Our nightlies use: `D:\a\OpenTTD\OpenTTD`

Build time: `Mar  8 2024 15:56:18`
Our nightlies build at 0600

Besides the fact we don't have the symbol file on record .. I am like 99.99% sure this is a custom build. Which so happened to be of the same version as the nightly. Doesn't make it not a custom build.

**Comment by Kuhnovic** [comment]
[ship_cond_order_13.1.zip](https://github.com/OpenTTD/OpenTTD/files/14542634/ship_cond_order_13.1.zip)

Here's an isolated case with a single ship on a 64x64 map. Use this one :)

**Comment by glx22** [comment]
At least, being a custom build, the decoded call stack in JSON is usable.
