### ISSUE TITLE
[Bug]: Won't launch if installed in /opt/ and added to $PATH

### ISSUE THREAD

**Issue by AustrianLinuxMemer** [OpenTTD/OpenTTD#12349]
### Version of OpenTTD

OpenTTD 13.4 Generic Linux

### Expected result

The game launches like any other binary in `$PATH`

### Actual result

The program ends with: `Error: No available language packs (invalid versions?)`

### Steps to reproduce

1. Install the OpenTTD binary from [the OpenTTD download page](https://www.openttd.org/downloads/openttd-releases/latest) into the `/opt/` directory.
2. Adding `/opt/openttd-13.4-linux-generic-amd64/` to `/etc/bash.bashrc`
3. with the new bashrc loaded, running `openttd` on the command line

**Comment by TrueBrain** [comment]
OpenTTD uses many ways to detect where the language packs are. This is the most difficult on Linux, because of the many ways a Linux OS can be setup.

For example, if you would install the game in `/usr/local/share/games/openttd`, it will detect the language packs fine, and run in the way you describe. Or if you run OpenTTD via `/opt/openttd-13.4-linux-generic-amd64/openttd` yourself, it will work fine too.

However, putting it in a folder yourself, and adding that to the `PATH`, does not. Easiest solution for this is, instead of adding it to your path, creating an alias for it, where you use the full path to launch the game. That way you can just type `openttd` anywhere, and it will launch the game.

Lastly, the alternative distros like Ubuntu, RedHat, etc pick, is to compile OpenTTD manually with FHS support enabled, after which it is install in `/usr/share/games`. There too, starting `openttd` will work. But that does require a custom compile of the game (or installing OpenTTD via your distro, instead of using the generic linux build we prepare.

Hopefully this helps you out!

**Comment by TrueBrain** [comment]
Between devs we have talked this over in various of ways, but in the end, we will not be supporting this workflow. It is too specific (niche) for your setup, and the code required to support it is not in comparison to the gain it gives.

As mentioned above, our suggestion is to either follow FHS or to use an alias.

Sorry about this outcome, but I hope you understand :)
