### ISSUE TITLE
[Bug]: Cost of hostile takeover appears to include two years of expenses, not just two years of profits

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#12818]
### Version of OpenTTD

88e53dbdc8 on Windows 10, 64-bit (via Steam)

### Expected result

> In a hostile takeover of [company name], you will purchase all assets, pay off all loans, and pay two years worth of profits.

The above message should be changed to reflect that one also needs to pay two years worth of operating expenses, or operating expenses need to be ignored or subtracted from the cost.

### Actual result

In a hostile takeover of [company name], you will purchase all assets, pay off all loans, and pay two years worth of profits **and expenses**, even though the message says you only need to "... pay two years worth of profits" without mentioning expenses.

This may be caused by subtracting `expenses` where `expenses` is a negative number.
![image](https://github.com/OpenTTD/OpenTTD/assets/37945304/440304f3-996d-42d1-9496-6097d1fd404e)
https://github.com/OpenTTD/OpenTTD/blob/88e53dbdc8b196c18d8354b31d7bda7ab8b28544/src/economy.cpp#L187

### Steps to reproduce

1. Download, install, and start an IdleMoreMore AI.
2. Give it hundreds of millions in cash.
3. Switch to the AI company.
4. As the AI company, build a ship depot.
5. Buy a ship, and tell it to repeatedly refit to Goods then Iron Ore and back.
6. Start the ship.
7. Watch the expenses skyrocket (10 million pounds a year/period).
8. Switch back to the human company, and try to execute a hostile takeover.
9. Notice the price is over 20 million pounds.

Alternatively, load the attached save and execute a hostile takeover of the blue company.
[Money-Sink Ships, 2102-05-26.zip](https://github.com/user-attachments/files/15987466/Money-Sink.Ships.2102-05-26.zip)

**Comment by TrueBrain** [comment]
Defining profit as "income - expenses" doesn't sound weird to me? If you have a negative expense, you made profit.

For example, if I sell all my trains in a year, I made a lot of profit that year. That is fully what I would expect.

So I am missing something, but what is exactly the issue with this way of calculating profit, and the way it is worded? Profit isn't just income (otherwise we would have written: incoming). So I am just a bit confused what you are seeing :)

**Comment by TrueBrain** [comment]
Ah, couldn't make that up from your text, but when looking more closely to your image, I think what you are trying to say is:

Profit should be `income - expenses`, but it is `income + expenses`.

This is because apparently internally "expenses" is a negative value. That is unexpected, I have to say, but it also means the profit calculation is doing the wrong thing here ;)
