### ISSUE TITLE
[Crash]: Not Compatible With Alpine Linux

### ISSUE THREAD

**Issue by rughinnit** [OpenTTD/OpenTTD#12827]
### Version of OpenTTD

OpenTTD 14.1, Alpine_Linux_3_19

### Steps to reproduce

1. Download OpenTTD from this link: https://cdn.openttd.org/openttd-releases/14.1/openttd-14.1-linux-generic-amd64.tar.xz
2. Launch the openttd executable
3. Can not execute openttd (openttd not found)
4. Realizing that Alpine is musl
5. Installing libc6-compat
6. Execute the bin again
7. Error (detail on crash below)

### Upload crash files

Error relocating /home/seith20/openttd-14.1-linux-generic-amd64/lib/libgomp.so.1: pthread_attr_setaffinity_np: symbol not found
Error relocating /home/seith20/openttd-14.1-linux-generic-amd64/lib/libp11-kit.so.0: fcntl64: symbol not found
Error relocating /home/seith20/openttd-14.1-linux-generic-amd64/lib/libgmp.so.10: obstack_vprintf: symbol not found
Error relocating /home/seith20/openttd-14.1-linux-generic-amd64/openttd: fcntl64: symbol not found

**Comment by TrueBrain** [comment]
It seems `libc6-compat` isn't as compatible as the name suggests :) `fcntl64` really is part of libc, or at least, should be. So that is an odd issue.

Our generics are indeed targeted at libc. I guess easiest would be to recompile OpenTTD yourself with musl; that should, in theory, "just work". Not sure anyone tried, I have to admit :)

Too bad the latest version of OpenTTD in Alpine is a bit old (13.4, at the time of writing). That would be even easier.

Either way, something we actually might want to look into.

**Comment by krpdtmnt** [comment]
Well, I did compile openttd. Its working, but the size is 300mb. How to make it small?

**Comment by TrueBrain** [comment]
`strip` the binary! Or run `make install` :)

```bash
strip openttd
```

**Comment by glx22** [comment]
Also make sure it's not a debug build (use `-DCMAKE_BUILD_TYPE=RelWithDebInfo` or `-DCMAKE_BUILD_TYPE=Release`)

**Comment by krpdtmnt** [comment]
Thanks, now i can ship the bin to my vps :)

**Comment by krpdtmnt** [comment]
> Also make sure it's not a debug build (use `-DCMAKE_BUILD_TYPE=RelWithDebInfo` or `-DCMAKE_BUILD_TYPE=Release`)

i did it..
