### ISSUE TITLE
[Bug]: vehicule speed still display on right side for some languages

### ISSUE THREAD

**Issue by fredaudy** [OpenTTD/OpenTTD#12927]
### Version of OpenTTD

14,1

### Expected result

vehicule speed to be  display on left side of the name, for all languages
![vehSpeedDisplayOnLeftSide](https://github.com/user-attachments/assets/6b3cf4e8-75c9-4598-8382-da37742a10c9)

### Actual result

vehicule speed is display on the right side of the vehicule for some languages
![vehSpeedDisplayOnRightSide](https://github.com/user-attachments/assets/f8bd6de2-1984-4e2d-8326-5129fb9724af)

### Steps to reproduce

1. open a vehicule "display" window
2. switch the language from english to afrikkans, french, irish…

**Comment by 2TallTyler** [comment]
The format of this text string is decided by our volunteer [translators](https://translator.openttd.org/). If a language shows the old format, it's because the string has not been updated by the translators for that language — or at least, it was not updated before the release of 14.1.

In other words, this is nothing we can fix, we just have to wait for translators to update strings, and then for a release of OpenTTD to import their updated strings into the game. 🙂
