### ISSUE TITLE
[Bug]: Flatpak, Snap and debian app ids seems to differ

### ISSUE THREAD

**Issue by junalmeida** [OpenTTD/OpenTTD#13028]
### Version of OpenTTD

14.1

### Expected result

Software Centers like KDE Discover should group the app into a single app based on the app metadata ids, consolidating ratings and reviews.

### Actual result

Duplicated entries in software center ui shows up. 

### Steps to reproduce

Open KDE Discover
Search for OpenTTD
See duplicated entries 
![image](https://github.com/user-attachments/assets/f6d69725-04a1-4ce0-ab69-fb9154fc1b2a)

**Comment by PeterN** [comment]
Unlikely to be anything to do with us, we don't create or package Flatpak, Snap or Debian versions.

**Comment by TrueBrain** [comment]
Our official binaries are only published as a tarball; we let other parties do the distributions you mention. But looking by the links you already found those other parties. We would like to leave it between them to resolve this issue.

If there is something we can help here, do let us know. But for now: not our bug :)

**Comment by ghisvail** [comment]
> But for now: not our bug

Well, it sort of is. There was an [effort](https://github.com/OpenTTD/OpenTTD/issues/6490) to upstream the AppStream metadata, but it was abandoned due to lack of motivation. As a result, each downstream packaging effort (such as the one listed here: Flatpak, snap, Debian, but probably others) will provide their own metadata with slight variations. Those variations will result in duplicate entries in software centers such as GNOME Software or KDE Discover.

Solutions are either to get **all** downstream packagers to collectively agree on a common set of metadata, or resume the upstream effort initiated [here](https://github.com/OpenTTD/OpenTTD/issues/6490). I'll let you evaluate which one is easier to achieve.
