### ISSUE TITLE
Orders: Allow Sign-Click same as station-click for vehicle Go To

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#3717]
**_PaulRobinson_ opened the ticket and wrote:**

> In attempting to set the station to go to, if you miss and click on a vehicle in the station, instead of clicking on the station, it copies that vehicle's station list.  While some people like this feature it can be irritating, especially if it's an extremely busy station tat you can't find an empty spot.  I recommend allowing the option of clicking on the station's sign for selecting the station to go to.

**Reported version**: _1.0.0-RC3_
**Operating system**: _Windows_

---

**Comment by andythenorth** [comment]
I do experience the issue described, and it is annoying.

But I think it's TMWFTLB to fix.  Would mean intercepting the click if it's on the sign, and allowing it to fall through to the tile behind if it's not on the sign.

But people mis-click (or this issue would never be raised).  So they're going to mis-click signs too.  Additionally the tile behind might be a completely different station or so. 

Closing, because the proposed fix adds complexity but doesn't really fix the issue.  Also 8 years, no change :)
