### ISSUE TITLE
Use the OS cursor

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#3821]
**_smurfix_ opened the ticket and wrote:**

> The built-in cursor is very sluggish at times; if the lag is > 1/3rd second or so, hitting user interface elements becomes almost impossible.
> 
> Fix: Optionally use the OS cursor to make the interface smoother.

**Reported version**: _trunk_
**Operating system**: _Linux_

---

**Comment by TrueBrain** [comment]
Basically, this is hiding a bug with a solution. The bug is:

Mouse lag can be up to 1/3rd of a second, which makes hitting elements in the interface very hard.

As I somewhat doubt that using the OS mouse changes anything. Especially in 2018, I doubt we have mouse cursors without Hardware acceleration. If they lag behind, the OS cursor most likely will too.

So I am going to close this issue (after 8 years; sorry about that), and I would like to ask anyone to open a new bug ticket if they have mouse-lag like this ticket described.
