### ISSUE TITLE
Assertion error on loading old game

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5232]
**_Moriarty_ opened the ticket and wrote:**

> I have a (very?) old OTTD game that I'm trying to load. I can understand if OTTD can't load it, however it actually crashes out whenever I try and do this one.
> I get an assertion error:
> Line 103, "...build-dir\ottd-nightly-w64bit\src\core/pool_type.hpp: index < this->first_unused.
> 
> r24375

**Attachments**
- [Tax Fiddlers Anonymous, 31st Jul 2056.sav](https://bugs.openttd.org/task/5232/getfile/8436/Tax+Fiddlers+Anonymous%2C+31st+Jul+2056.sav) (159.43 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Afterload() calls UpdateHousesAndTowns()->RebuildTownCaches()->RebuildSubsidisedSourceAndDestinationCache() quite early, way before the subsidy conversion code for savegame version 125.
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5232#comment11307_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Broken in r24180 when RebuildSubsidisedSourceAndDestinationCache() as added to RebuildTownCaches() resp. UpdateHousesAndTowns().
> Commenting out that call makes the savegame load.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5232#comment11308_

**Comment by DorpsGek** [comment]
**_frosch_ closed the ticket.**

**Reason for closing: _Fixed_**

> in r24482

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5232_

**Comment by James103** [comment]
The savegame "Tax Fiddlers Anonymous, 31st Jul 2056.sav" [crashes on load with this log](https://github.com/OpenTTD/OpenTTD/files/3200156/OpenTTD.-.2.zip) on 20190516-master-g24493548da with `Assertion failed at line 433 of d:\a\1\s\src\core\kdtree.hpp: this->Count() > 0`. When I tried to do the emergency savegame, it turned out empty and a Windows-style "OpenTTD has stopped working" message appeared twice.
