### ISSUE TITLE
Industry Directory Window Enhancements

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5575]
**_trainqa_ opened the ticket and wrote:**

> It is cumbersome to find the top producing industry of a certain type.  I suggest the following enhancements:
> \- Tabular format (Name, Production, Transport % )
> \- Filter by Industry
> 
> This would allow to filter to 'Coal', then 'Sort Ascending' by 'Production'

**Reported version**: _1.3.0_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_juanjo_ wrote:**

> There is something similar here: http://www.tt-forums.net/viewtopic.php?f=33&t=56101

**Attachments**
- [industry.png](https://bugs.openttd.org/task/5575/getfile/9080/industry.png) (209.96 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5575#comment12275_

**Comment by andythenorth** [comment]
It's not a bug, and it's not a patch, and it's not someone offering to push a feature request through with advocacy and a pull request.

So I'm closing it, because having an open issue for this is not winning anything :)

(The request is likely to recur anyway, and we don't gain anything from using open issues to track some kinds of feature request, especially the really obvious ones, which this one is).
