### ISSUE TITLE
Vehicles Filter by In Depot

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5576]
**_trainqa_ opened the ticket and wrote:**

> For a large amount of vehicles it can be difficult to find vehicles that are sitting idle in a depot.  This would allow the ability to find those.  Optionally this could be applied to other attributes too.  So that you can filter by negative profit, age is more than 2 years past end-of-life, etc.

**Reported version**: _1.3.0_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_trainqa_ wrote:**

> Whoops.  Reported Version 1.3.0, Type:Enhancement.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5576#comment12265_

**Comment by DorpsGek** [comment]
**_juanjo_ wrote:**

> I wrote something like that, but with many other attributes (possibly far too much attributes).
> Topic: http://www.tt-forums.net/viewtopic.php?f=33&t=56101

**Attachments**
- [vehicles.png](https://bugs.openttd.org/task/5576/getfile/9079/vehicles.png) (234.34 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5576#comment12274_

**Comment by andythenorth** [comment]
I can see the need for this.

However I think the interaction between groups and filters would be confusing.
* are filters preserved when moving between groups or removed (some players will want one behaviour, others will want the other)
* what happens when I drag a nested group with filters applied onto another group?  Do all the vehicles in the group move, or just the filtered vehicles?
* how do the counts in the groups relate to the counts from filter results?
* how to handle player reports that vehicles have 'disappeared' due to a filter being applied? 

All of this is resolvable, but it all needs to be done right, so I think it's TMWFTLB.  Closing, as we need to clarify priorities.

(For where we are now with the group UI, a cleaner solution might be a new type of group with dynamic results driven by rules).
