### ISSUE TITLE
Hotkeys to mute and volume up and down

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6068]
**_Milsa_ opened the ticket and wrote:**

> Please add hotkeys to:
> \- sound mute
> \- sound volume up
> \- sound volume down
> 
> Problem is in main screen. This is process to mute volume:
> \- start game
> \- open jukebox
> \- mute volume
> 
> Or second process is:
> \- open game settings
> \- remove openmsx and opensfx
> 

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
See #6210 also - more hotkeys.

**Comment by TrueBrain** [comment]
Most games I know of don't have hotkeys for sound volume. This is because you mostly either have this on your keyboard, or use the OS for this. I do not see a need or benefit for creating hotkeys for it.

I come to this conclusion mainly because there is only a technical solution in this issue, and not a use case what the problem is we are trying to solve. So I have very little to go on there. So feel free to rebuttal if you have a clear use case which shows it is needed to do this outside the OS.
