### ISSUE TITLE
NewGRF cannot configure purchase prices per wagon

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6581]
**_mb_ opened the ticket and wrote:**

> For running costs, a newgrf may set different base amounts, but for purchase prices, the game does use hard-coded memory locations, e.g. for train engines and train "wagons". This results into a very limited variety, especially because "wagons" covers (more expensive) coaches as well as (cheaper) freight cars.
> 
> In addition, making purchase base cost addresses available to newgrfs would allow to use different base costs with different multipliers, which is not possible ATM.
> 

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
I ran into limitations with purchase cost ranges recently. 
 
To solve this, frosch indicated I should set them via cb 36 rather than property.  This gives a range of ~32000 return cost factors, rather than just 255.  In combination with appropriate base cost factor, I was able to set costs appropriately.

I'm closing this as I think it's very unlikely to be addressed further.  Thanks.
