### ISSUE TITLE
graphical glitch in train detail window

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6586]
**_mb_ opened the ticket and wrote:**

> For articulated vehicles carrying e.g. two different cargo types, the train detail window shows two entries, with only the first one displaying the vehicle sprite. In this case, there´s a weird glitch, i.e., a 2-pixel stripe of background grey being painted over the vehicle sprite, as can be seen in the screenshots. In fact, that weird stripe is painted over the whole window entry, as can be seen by that vanished dark grey line.
> 
> This might be related to other problems with sprite positioning in the diverse vehicle windows, see # 6357. 

**Attachments**
- [glitch_art.png](https://bugs.openttd.org/task/6586/getfile/10736/glitch_art.png) (6.96 KiB)

**Reported version**: _1.7.1_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
This needs a savegame and the relevant grf.  Also the OpenTTD version and platform info.

**Comment by andythenorth** [comment]
Eddi investigated, and believes this was caused by https://github.com/OpenTTD/OpenTTD/issues/2923

Specifically, the attached patch from Eddi might fix it (can't upload a .diff).  This should probably be a gist or PR, but early days eh?

[6586.txt](https://github.com/OpenTTD/OpenTTD/files/1905032/6586.txt)
