### ISSUE TITLE
Fluidsynth music driver

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6611]
**_LordAro_ opened the ticket and wrote:**

> https://www.tt-forums.net/viewtopic.php?f=33&t=57037 by jmak
> 
> Last version attached. Will need updating

**Attachments**
- [0001-fluidsynth-support.patch](https://bugs.openttd.org/task/6611/getfile/10794/0001-fluidsynth-support.patch) (11.11 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by planetmaker** [comment]
The patch's comment style is not entirely consistent in src/music/fluidsynth.cpp. It uses // in 3 places where it should use /* ... */. Otherwise... it probably could be changed to a pull-request, if it works; but it might need adjustment in the build infrastructure, or our tests will pass and builds ship w/o it.
