### ISSUE TITLE
Saving game then loading one of the same name via console, all in the same directory, fails.

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6621]
**_james1101_ opened the ticket and wrote:**

> To Reproduce:
> 1. Save the game normally (with a unique file name). Wait until it is finished. Remember the filename of the saved game file.
> 2. Via console, navigate to the directory where the game was saved at. (if needed)
> 3. Via console, attempt loading the saved game. It should fail.
> 4. Use the ls command via console.
> 5. Load the saved game via console. It should work.

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_james1101_ wrote:**

> FWIW, I'm using OpenTTD Version 1.7.1 running on Win 7 Ultimate, and one possible reason is saved file doesn't get indexed until a file command is executed.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6621#comment14764_

**Comment by nielsmh** [comment]
Can't reproduce in rev. cd966f3 (with some additional music patches).

Steps taken:
1. Start new game, build a few tiles of rail
2. Click Save button, navigate two folders up, delete suggested name, type in `testme`
3. Quit OpenTTD  completely
4. Start OpenTTD again
5. Open console
6. Type `cd ..` twice
7. Type `load testme`
The saved game is loaded without problems.

However one thing I noticed, trying out various things, was that changing directory in console with `cd` and then saving from console with `save filename`, the savegame file was put in the default save game directory, not the directory changed to. I don't know if that's intentional or not.

**Comment by andythenorth** [comment]
Thanks for this.  At the time of writing this appears to be an isolated bug, and hard to reproduce.  We do try to address bugs where they occur frequently and/or are easy to reproduce, but this one doesn't look like we can any go further, so I'm closing it.  Thanks for contributing!
