### ISSUE TITLE
Helicopters can be stopped while descending

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6676]
**_PaulC_ opened the ticket and wrote:**

> Not sure if this is a bug, but it's possible to stop helicopters in mid air as they are descending on a heliport (though not while they are ascending). Also, if you stop a helicopter with a breakdown it is fixed upon restart.

**Attachments**
- [Brundhattan Ridge Transport, 2023-07-20.png](https://bugs.openttd.org/task/6676/getfile/10974/Brundhattan+Ridge+Transport%2C+2023-07-20.png) (79.18 KiB)

**Reported version**: _trunk_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_Samu_ wrote:**

> Happens on these:
> \- Commuter
> \- International
> \- Intercontinental
> \- Helidepot
> \- Helistation
> 
> Doesn't happen on these:
> \- Small
> \- City
> \- Metropolitan
> \- Heliport
> \- Oilfield

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6676#comment14847_

**Comment by DorpsGek** [comment]
**_PaulC_ wrote:**

> Now this is just a thought (and more of a feature request)... Normally when you try and stop aircraft during flight you just get a "Cant stop/start etc etc..." message. Would it not be better to have the aircraft stop when it reaches it's next destination?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6676#comment14848_

**Comment by nielsmh** [comment]
The problem appears to be that the helicopter landing directly at a helipad changes to the HELIPAD1, HELIPAD2, or HELIPAD3 state as soon as it begins descent, instead of using the HELILANDING or HELIENDLANDING state. Those states are handled as if they were already landed in CmdStartStopVehicle. Either the helicopter state machine needs to be fixed, or the logic for start-stop needs to add some exceptions for those landing-at-helipad states.

**Comment by nielsmh** [comment]
This can also happen on airports where the heli lands directly in front of a hangar for servicing, it may then stop midair while descending to the hangar.
