### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [OpenTTD/OpenTTD#6730]
Would you like to add more error handling for return values from functions like the following?
- [fputs](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fputs.html "Put a string on a stream") ⇒ [IniFile::SaveToDisk](https://github.com/OpenTTD/OpenTTD/blob/f84ad5f7c053dc4af3c0fc12bc6584d825a5bf91/src/ini.cpp#L38)
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex") ⇒ [ThreadMutex_pthread constructor](https://github.com/OpenTTD/OpenTTD/blob/6c3902ac41113e6e4a87e0a7e9cc9f96062402c4/src/thread/thread_pthread.cpp#L124)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string") ⇒ [File constructor](https://github.com/OpenTTD/OpenTTD/blob/f84ad5f7c053dc4af3c0fc12bc6584d825a5bf91/src/depend/depend.cpp#L158)

**Comment by TrueBrain** [comment]
I am not really sure what this issue is about. Are you asking if we would like that, and that you are going to make Pull Requests for that? Or are you asking us to make those changes?

I am going to assume it is the first :)

Of course we welcome any PRs that increases the robustness of our software; we would be silly not to. But there is a balance of course (more validation is not always better in terms of maintenance). And some solutions are better than others.

The best thing you can do, if you are interested, is drop by on our IRC channel (irc.oftc.net, #openttd). There you can talk with people like @frosch123 which can help you find the balance of what is worth the effort, and what is not.  For example, detecting `strdup` failed is one thing; but what should you do if it did? Not always an easy question :D

Going to close the issue, as these are more meant for issues; not so great for such dialog; but I do hope you drop by on IRC, as more validation is of course always better :) Thank you!

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?
