### ISSUE TITLE
lzma not detected on Mac OS X after installing via homebrew

### ISSUE THREAD

**Issue by readingsnail** [OpenTTD/OpenTTD#6755]
hitchhiker  ~/Downloads/OpenTTD-master   ./configure
checking awk... awk
detecting OS... OSX
checking build system type... x86_64-apple-darwin17.5.0
checking host system type... x86_64-apple-darwin17.5.0
checking universal build... no
checking build cc... gcc
checking host cc... gcc
checking build c++... g++
checking host c++... g++
checking strip... disabled
checking builtin depend... yes
checking makedepend... disabled
detecting cpu-type... 64 bits
detecting SSE... found
checking static... no
checking unicode... no
using debug level... no
using desync debug level... no
using link time optimization... no
checking OSX sysroot... no (use system default)
checking Allegro... OSX, skipping
checking SDL... OSX, skipping
checking COCOA... found
checking whether to enable the Quartz window subdriver... yes
checking Quickdraw window subdriver... disabled (64 bits)
checking GDI video driver... not Windows, skipping
checking dedicated... not selected
checking console application... not Windows, skipping
checking network... found
checking squirrel... found
checking translator... no
checking assert... enabled
checking zlib... not found
checking liblzma... not found
WARNING: lzma was not detected or disabled
WARNING: OpenTTD doesn't require lzma, but it does mean that many features
WARNING: (like loading most savegames/scenarios and joining most servers)
WARNING: will be disabled.
If you want to compile without lzma use --without-lzma as parameter

already installed xz (lzma) - using homebrew - but OpenTTD's Configure is not detected. 🤔

**Comment by readingsnail** [comment]
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

macOS: 10.13.4-x86_64
CLT: 9.3.0.0.1.1521514116

**Comment by TrueBrain** [comment]
Although OpenTTD tries its best to detect libraries with all the OSes out there with all possible combinations, sometimes it has a hard time detecting it. A few things you can try:

- make sure you have the right lib installed (`liblzma`). You can look on your filesystem to see if you can find it yourself (otherwise the configure system won't for sure :D).
- normally `pkg-config` tells the location of these. Check if he can see `liblzma`.
- you can force it to look in a specific location with `--with-lzma=<location>`, as the `--help` tells you. Then for sure it will look in that folder; so if the files are there, it will pick them up
- it also says it cannot find `zlib`. Do you have your system properly configured that `pkg-config` works, or that OpenTTD can see your library location? `--help` tells you how to add search locations etc.

Hope this helps!

**Comment by TrueBrain** [comment]
According to https://wiki.openttd.org/Compiling_on_Mac_OS_X, what other people wrote who tried what you are trying (but it is somewhat out-dated), under `Homebrew`, it says you need `xz`, `lzma`, and `pkgconfig`. Possibly that also gives you a few breadcrumbs.

**Comment by readingsnail** [comment]
@TrueBrain Thanks, now closing for this, sorry for annoying

**Comment by TrueBrain** [comment]
No problem at all! Let us know if you have any further issues compiling :)

**Comment by andythenorth** [comment]
That OS X wiki page could lose the fink information and get a few other tweaks.  I'm adding this note as a reminder to self.
