### ISSUE TITLE
OpenTTD now available as a flatpak

### ISSUE THREAD

**Issue by ghisvail** [OpenTTD/OpenTTD#6778]
Just to let you guys know that I made OpenTTD available for install as a [flatpak](https://github.com/flathub/org.openttd.OpenTTD) via [flathub](https://flathub.org). The README could be updated to advise the user of this possible cross-distribution alternative for Linux.

The flathub community would be happy to provide commit access to the repository should the upstream developers desire to help maintain it. As far as maintenance is concerned, it should remain a matter of updating the .json file with the path of the release tarball and its corresponding sha256 sum whenever a new release is made available.

Feel free to upstream the AppStream metadata (`.appdata.xml` file), which could be useful for all downstream distributions of OpenTTD on Linux (DEB, RPM, flatpak, snap possibly?)

Addresses a comment in #6734.

**Comment by coverme76** [comment]
Include graphics in OpenTTD.flatpack for offline use as it is based on OSTree ?

**Comment by ghisvail** [comment]
> Include graphics in OpenTTD.flatpack for offline use as it is based on OSTree ?

All [required 3rd party files](https://github.com/OpenTTD/OpenTTD#411-free-graphics-and-sound-files) should already be included in the [flatpak manifest](https://github.com/flathub/org.openttd.OpenTTD/blob/43ab57754875a5ba7dd52405097332b166e15ffe/org.openttd.OpenTTD.json#L126). Could you be more explicit regarding what's currently missing, please?

**Comment by TrueBrain** [comment]
Very cool we are on flatpak! Much appreciated!

We in general always welcome any PR that adds these kind of things, if you are willing to maintain it too :) The main reason we have Debian files, is because we have a single person constantly maintaining it for us (for years at end now :D). If you would be up for that task, that would be much appreciated!

Also you are free to create PRs to mention flatpak (or any other platform) in the appropriate places in the README, and of course on our wiki (https://wiki.openttd.org/).

Thank you again!
