### ISSUE TITLE
OpenTTD causes high CPU usage in 'System' process

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#6850]
Using OpenTTD 1.8.0 on Windows 7 Ultimate 32-Bit, Intel Core™2 Duo CPU T5800 @ 2.00 GHz, 4 GB RAM (3 GB usable), Nvidia GeForce 9600M GS

Up until a few months ago, I was able to run 512^2 maps with high development at moderate fast forward with the specs mentioned up top. Now, those same maps will not run at regular speed, even if the development is reduced significantly. The same specs are maintained since I got the computer years ago. That problem of high CPU usage by System process does not occur when casually browsing sites like Wikipedia or watching YouTube videos.

To Reproduce the high CPU usage, 
1. Start OpenTTD with the following config settings: [openttd.cfg.txt](https://github.com/OpenTTD/OpenTTD/files/2176388/openttd.cfg.txt)
2. Load the following savegame (unpack first): [Trautenberk Bahn GmbH., 1980-07-04.zip](https://github.com/OpenTTD/OpenTTD/files/2176277/Trautenberk.Bahn.GmbH.1980-07-04.zip)
3. Play normally, watching the CPU usage in Task Manager. You should see the 'System' process using 50% of CPU and the game slow down after a few moments. Continuing after that should eventually cause the system to hang, even with no other nonessential processes running. 

For reference I've attached extra files that should help finding the cause of the high CPU usage by the 'System' process while playing OpenTTD.
- [CPU usage over a couple minutes (includes game state plus legend)](https://user-images.githubusercontent.com/37945304/42453130-688a8b2c-8351-11e8-8944-4b32bfcbc857.png)
- [Commands executed since loading the savegame](https://github.com/OpenTTD/OpenTTD/files/2176308/commands-out.log)
- [2 autosaves that occured with desync level 4 on](https://github.com/OpenTTD/OpenTTD/files/2176309/autosave.zip)

Things I've tried to reduce the CPU usage:
- Enable OpenTTD's 8bpp-optimized mode
- Run Auslogics' registry cleaner
- Run CCleaner's registry cleaner
- Run CCleaner's cleaner
- Run Baidu Antivirus' quick virus scan

**Comment by nielsmh** [comment]
Since this might be system-specific, and specific to running a 32 bit build on a 32 bit OS (I don't have any modern-ish 32 bit OS handy), can you check the Processes tab in Task Manager, and enable the "Private working set", "Page faults", and "PF delta" columns?
How large is the working set for the OpenTTD process, and does it generate many page faults? (If Page Faults is rising then PF Delta should also be greater than zero, this indicates that the process is having memory moved into/out of the page ("swap") file.)

**Comment by James103** [comment]
I see that OpenTTD is only using about 70 MB of private working set, but when I run the aforementioned saved game on fast forward, OpenTTD generates hundreds, if not thousands of page faults per second.

**Comment by nielsmh** [comment]
Sorry, I'm not able to reproduce any performance issues with that save. I strongly suspect it's related to some other software running on your system interfering, but if you want to test here's the build I'm testing with: [OpenTTD-fps_meter-28825372c.zip](https://github.com/OpenTTD/OpenTTD/files/2177050/OpenTTD-fps_meter-28825372c.zip)
There's a bunch of changes since 1.8 in this build, and savegames made with it won't be compatible with 1.8, but importantly this has my work-in-progress framerate display (see #6822) patch included. You can try opening it from the Help menu, it might give some hints on whether it's one particular part of the game engine that's slowing down.

**Comment by James103** [comment]
Here are the results of my testing, with both OTTD 1.8.0 and OTTD with fps meter (which is called OpenTTD norev000 internally), and both my config and the default config for OpenTTD.
- OpenTTD 1.8.0, custom config: System process uses a lot of CPU time
- OpenTTD 1.8.0, default config: System process doesn't use much CPU time
- OpenTTD norev000, custom config (stripped down for compatibility): It depends (sometimes uses 50% CPU, sometimes uses less than that)
- OpenTTD norev000, default config: System process doesn't use much CPU time
Based on the results, it's a combination of the changes since OpenTTD 1.8.0, and my configuration settings that may be the cause.

Edit: More test results (this time related to audio output (audiodg.exe):
- OpenTTD 1.8.0: Audio output takes 30-40% CPU time
- OpenTTD plus fps meter: Audio output randomly jumps between 0% and 50% CPU usage, sometimes in between those two values

**Comment by James103** [comment]
The high CPU usage problem is caused by old drivers being used. I've updated the drivers, and the CPU usage has gone down significantly. Because of that, I'm closing this issue with the following reminder: If OpenTTD uses a large amount of CPU resources while it is idle, please update the drivers as soon as possible, that can decrease the CPU usage significantly!
