### ISSUE TITLE
String colour for framerate windows suggestion

### ISSUE THREAD

**Issue by J0anJosep** [OpenTTD/OpenTTD#6864]
Usually in OpenTTD, the string color is usually black. Numbers have a different color (blue, red...), but the color of the unit (if any) matches the color of the number.
So here is a current image of the framerate window (next to a train details window):
![imatge](https://user-images.githubusercontent.com/3152990/43078262-3e34892e-8e8a-11e8-966c-33a34aabbcc7.png)
And I suggest to change it to something like this:
![imatge](https://user-images.githubusercontent.com/3152990/43081217-d184220a-8e91-11e8-8500-15df3f2af19c.png)
I'll wait and see whether this second version is preferred or not before pushing a PR.

**Comment by nielsmh** [comment]
I wanted to have the numbers stand out from the unit, since it's the same unit the entire column down. I think the numbers are harder to read when the unit is colored the same, in this case.

You're right the text ought to be black, and there ought to be a divider line between the top headings and the columns.

**Comment by J0anJosep** [comment]
@nielsmh I prefer using the same coloring rules as in the train details window. Moreover, in the framerate window all the ms are aligned making it easier to spot the numbers. Another option would be to state somewhere that measurements are in ms. That way it wouldn't be necessary to write "ms" 24 times and it would be easier to read all the numbers.
The "divider" is just underlining those words (see company finances window).
