### ISSUE TITLE
CONFIG_RANDOM bug

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#6892]
https://github.com/OpenTTD/OpenTTD/blob/bb086f92403aa70d5756c334df31a65f4b854e39/src/script/script_config.cpp#L39

When I was testing CONFIG_RANDOM feature, I wanted it to randomize between 0 and 1. Turns out that in 42 times it randomized, it always returned 0.
I found the bug to be that line.

Replace max_value to max_value + 1.

`this->SetSetting((*it).name, InteractiveRandomRange((*it).max_value + 1 - (*it).min_value) + (*it).min_value);`

[LuDiAIAfterFix-1 - Cópia.zip](https://github.com/OpenTTD/OpenTTD/files/2353561/LuDiAIAfterFix-1.-.Copia.zip)
Here's an AI for testing. CONFIG_RANDOM feature requires the AI to be started as Random AI.

Start 14 Random AIs of it in single player. It will be naming its company randomly between PASS and MAIL.

PASS is min_value == 0
MAIL is max_value == 1

**Comment by nielsmh** [comment]
"Usually ranges are specified start-inclusive end-exclusive, isn't this a usage error?" was my thought reading this. I had to confirm with the documentation that the `min_value` and `max_value` are actually also used for the UI range, and since you can select all two options in your case, the range specification is not wrong in your configuration code. Ergo, this really is a bug with how the value is randomized.

So uh, I guess my point is, I'd have appreciated if this ticket had also included a short explanation for why this unusual behavior should be correct. (Off-by-one errors are terrible and always require careful explanations.)
