### ISSUE TITLE
selected rail type should be included in game saves

### ISSUE THREAD

**Issue by spiderbit** [OpenTTD/OpenTTD#6903]
If you select let's say electric rail type save the game, and load it on another day it will not be set to the same rail type so you likely place some normal rails before you notice that they are not the current technology you are using on your lines.

So it would be clever to include that in the save.

https://youtu.be/e66zCgyEUC0?t=378

**Comment by James103** [comment]
Can reproduce, steps below

(Using first / last available railway type)
1. Place some track of ethier Electrified or Monorail type.
2. Save game
3. Load game
4. Check default rail type. It does not match either of the rail types you've placed.

(Using most used)
1. Place more track of type A than type B.
2. Select type B.
3. Save game.
4. Load game.
5. Check default rail type. It is type A, since it is the most used.

Proposed solution: 
Add a new value to the setting "Default rail type after new game / game load": "Last selected" which would select the track type that was last selected in the current savegame.

**Comment by spiderbit** [comment]
That probably could be the same for all the other things like roads and also signals?

Lol no there is only one type of road :D but signals can be a problem I think?

**Comment by nielsmh** [comment]
In multiplayer, with multiple players controlling one company, each player building with different railtypes, a new player joins the company: Which railtype does the new player get as default?

**Comment by James103** [comment]
The new player's default railtype would default depending on his/her value for the "Default rail type" setting. The setting values "First available", "Last available", and "Most used" would query the server for the available railtypes and the company's usage amounts, while Last selected would default to "First available".

**Comment by andythenorth** [comment]
Client side UI preferences.  Client config, not savegame.  But then different newgrfs.  So eh.

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
