### ISSUE TITLE
The Debian and Ubuntu builds all depend on shockingly out of date libicu and libpng packages.

### ISSUE THREAD

**Issue by thedarkb** [OpenTTD/OpenTTD#7008]

**Comment by LordAro** [comment]
There are two separate issues here. One is that provided binaries depend on an old version of libpng. This is due to the old compile farm, which hadn't been significantly updated in many a year. The good news is that the new compile farm is very nearly complete (right, @TrueBrain ? ;) ) and all future releases (including nightlies) will fix this issue. See #6916 for any other details, and also https://github.com/OpenTTD/OpenTTD-CF

The other issue is rather harder to solve. OTTD uses libicu to render text (specifically, word wrapping in all languages, especially RTL). However, this part of ICU has been deprecated and removed in newer releases. Currently, other platforms no longer depend on ICU at all, but Linux has no such easy replacement, and ultimately someone needs to invest some time and work out quite what to do about it, whether that's pango, harfbuzz, or something else entirely. See #6922

**Comment by thedarkb** [comment]
Sorry about my tone previously, I think the best method by which this can be fixed is by statically linking libicu52.
