### ISSUE TITLE
OPF ships locked in a reverse-loop

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7244]
## Version of OpenTTD
master-g45ce517105
## Expected result
opf ships should know they can't do a 90 degrees turn after a reverse
## Actual result
opf ships get stuck in a reverse-loop, doing 180 degree turns against an obstacle, reverse, advance a tile, and do 180 degree turn again, heading back against the shore again.
## Steps to reproduce
Load savegame, ships 78, 59, 77, 75, 79, 81, 80.
[Koln Mines Shipping, 1996-12-30.zip](https://github.com/OpenTTD/OpenTTD/files/2877606/Koln.Mines.Shipping.1996-12-30.zip)

**Comment by SamuXarick** [comment]
Offending commit: 6ca637b8c149efe2cb8ccffccbfd98530f633d58

**Comment by J0anJosep** [comment]
Ok. I will fix this one. It is an easy one. Tomorrow you'll have your fix.

**Comment by SamuXarick** [comment]
I had forbid 90 deg for opf rejected, which was doing it the right way :/
https://github.com/OpenTTD/OpenTTD/pull/7070

**Comment by J0anJosep** [comment]
But just to let you know...
I've been trying to develop new features for water transport. OPF just tries to "guess" a path and fails too many times.
I would like to see it removed. It is not good at pathfinding, not only because of 90 deg turns. It is obsolete and in my opinion any second trying to improve it is a wasted second.

The other thing is why 90 deg setting isn't separated into two settings, one for ships and another for trains.

**Comment by PeterN** [comment]
Regarding the last thing, when I was going to do that originally all feedback said just remove it for ships.

**Comment by glx22** [comment]
Indeed "forbid 90°" only matters for trains. Ships can turn on spot.

**Comment by J0anJosep** [comment]
I am trying to develop water features and one of them is making ships avoiding rotation (I like the rotation feature, but I also try to make water routes more interesting for gameplay purposes). That is why I ask to keep this setting for ships.
If there is no intention on improving water transport (as making ships crossing over each other), it can be removed from master.
