### ISSUE TITLE
The currently selected base graphics set is missing 4 sprites. This is despite having the latest OpenGFX 0.5.2.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#7249]
## Version of OpenTTD
OpenTTD 1.9.0-beta2 (and probably later)
OpenGFX 0.5.2 (latest version from Bananas)

## Expected result
No "missing sprites" string in menu.

## Actual result
In the middle of the title menu, there is a string that says:
"The currently selected base graphics set is missing 4 sprites. \n Please check for updates for the baseset."
![image](https://user-images.githubusercontent.com/37945304/52986051-0f980500-33bc-11e9-8973-3e7291445902.png)

## Steps to reproduce
1. Clean install of latest OpenTTD and OpenGFX.
2. Launch OpenTTD.
3. Look for a "missing sprites" string in the title screen.
The same string occurs on OpenGFX 0.5.2, NightGFX 1.1.0, zBase 2015-04-20, and (probably but not tested) aBase 2016-05-17.

## Probable cause
The latest version of OpenGFX does not include the new group livery sprites that were added. Specifically, the "4 [missing] sprites" refer to the group livery sprite for trains, the group livery sprite for road vehicles, the group livery sprite for ships, and the group livery sprite for aircraft. The sprites are here (scaled x3, ignore the grey background): 
![image](https://user-images.githubusercontent.com/37945304/52986565-939ebc80-33bd-11e9-9892-72393b840ead.png)

**Comment by PeterN** [comment]
Yup, it's not been released since 2016, so it absolutely won't contain new sprites...

I believe OpenGFX development still lives at https://dev.openttdcoop.org/projects/opengfx

This is expected and OpenTTD is behaving as designed. OpenGFX is third-party and not maintained by OpenTTD. This is not a bug.

**Comment by James103** [comment]
Thank you for that. I did not realize that OpenGFX is basically no longer actively maintained (besides up to about 5-10 commits per year of translations and bug fixes) since 2016. Closing for the time being...

**Comment by PeterN** [comment]
That's all the maintenance it usually needs, we don't often add sprites these days.

**Comment by ShimmerFairy** [comment]
This is absolutely a bug, because now with 1.9.0-RC1 you're telling people that their graphics are outdated, and then when they try to update their graphics it'll confusingly claim to already be up-to-date. Will this bug still affect people when 1.9.0 comes out?

I know you claim it's a 3rd-party project, but when the official OpenTTD website recommends OpenGFX as the only free option for graphics, I don't think that excuse works. If the latest OpenGFX doesn't have the new sprites, then who does? How are you making use of them in the first place? (No seriously, how?)

**Comment by PeterN** [comment]
Good news, a new OpenGFX has been released which includes these sprites.

**Comment by LordAro** [comment]
Describing OGFX has "3rd-party" was perhaps taking it a little far, but was likely intending to make it clear that the issue is not in OpenTTD itself, as it is a separate project, codewise. However OpenGFX has just been imported into the OpenTTD GitHub organisation, so it can definitely no longer be described as 3rd party :)

To answer your other question - many of the devs, being old and ancient, still prefer (and use) the original TTD graphics set, the extra graphics for which are maintained in the OTTD repo itself, so cannot have any missing sprites
