### ISSUE TITLE
Crashlog truncated with many news messages

### ISSUE THREAD

**Issue by nielsmh** [OpenTTD/OpenTTD#7255]
## Version of OpenTTD
After merge of #6709

## Expected result
Crashlog written in full including the footer `*** End of OpenTTD Crash Report ***`.

## Actual result
File is truncated after a fixed buffer length is exhausted.

## Steps to reproduce
Load a savegame which produces a large number of news messages, for example [gr0_50k_stations63](https://github.com/OpenTTD/OpenTTD/files/2881701/gr0_50k_stations63.zip) used for testing #7235. This game will produce a very large number of station acceptance news messages on the first day of loading. If a crash occurs before these news messages expire from "recent", the crash log is truncated.

**Comment by James103** [comment]
Possible Fix: Depending on the amount of memory left for OpenTTD to allocate and the number of news messages, dynamically calculate and allocate the buffer to writing the OpenTTD crash report, instead of just assuming you will have no more than some number of recent news messages at the time of the crash and allocating a fixed buffer length for the crash report.
