### ISSUE TITLE
No distance between towns/industries options

### ISSUE THREAD

**Issue by perkel666** [OpenTTD/OpenTTD#7378]
In current OpenTTD there is no ability to set minimum distance between towns, industries and industries to towns. Such patches exist so there is demand for it and imho players shouldn't use patches to have such simple game-play modification if they want it.

**Fix:** Add those 3 options to advanced options.

**Reasoning:**
Distance between cities and industries gives ability for completely different game-play style. Like huge maps with scarce amount of cities which are divided by vast distance.
This also fixed one of issues with vanilla OpenTTD where towns like to be very very near each other even on very very big maps which causes them to swallow each other up very quickly and becomes hard to tell which part of city is this town or the other. 

Additionally this fix would really lovely play together with #7377 which would allow OpenTTD networks to work on truly vast scales fit to play on those extra large maps.

**Comment by TrueBrain** [comment]
Although I highly appreciate your enthousiasme of wanting more features in OpenTTD, and I don't disagree, this issue in its current state is hard to accept.

What would really help, if you can supply more information. For example:
- you mention there are patches, but you don't refer to any. This makes it hard to estimate if this is a simple change, or a very difficult.
- you mentioned there is demand for it, but you don't show us how you came to that conclusion. This makes it hard to estimate impact.

With this information, it allows us to balance your request. What would be even better, if someone makes any of these patches into Pull Request. This is exactly why we have Pull Requests, as that would allow anyone to come up with a patch, and offer it to us to include in OpenTTD.

Hopefully you can elaborate a bit more on this, and even better, make a Pull Request out of it ;)

Tnx!

**Comment by perkel666** [comment]
Patch thread and discussion:
https://www.tt-forums.net/viewtopic.php?t=33625

Unfortunately all of those patches are for old versions and i don't think any of them actually adds that option into UI.

As for demand as long as there is actual discussion or to point where patches are made it means someone wants to have such ability. This also means a lot of other people who don't know that such a thing could be possible would also maybe try to use it.

Imho "issues" isn't really great way to ask for such things. There is "projects" but that has nothing in it and your own thread about ideas is closed.

**Comment by nielsmh** [comment]
Github's "projects" are basically just a way to organise tickets into categories, they don't really do anything helpful for our workflow. In particular, a project is not a discussion board, and discussion is the main thing required here. 

Or make a proof of concept implementation, maintain it as a pull request, and work towards a stable feature that may some day be merged.

**Comment by TrueBrain** [comment]
Oef, that indeed is an old patch thread :) That doesn't really show interest tbh ;) But okay, I will read this as that you would like this added, which is a fair request; 1 or N, in the end, someone wants it :)

As mentioned in #7377, GitHub indeed is a bad place to talk about these things. That is why our [CONTRIBUTING.md](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md) suggests using the forums for it.

More on topic, turns out I have some good news: this is already possible via NewGRFs! For example via https://newgrf-specs.tt-wiki.net/wiki/Action0/Industries#Callback_flags_.2821.2C22.29 . So possibly we don't even need an Option for it, just a NewGRF that does it!

In general, I think what we try to say: we have 100 ideas, but mostly we need people making them in Pull Request so we can talk about it, and accept them if we approve. So again, I really appreciate the ideas, but sadly GitHub is not the platform for it. But again, we are still looking here for what a good workflow is; for now it is the forums! (but sadly, you cannot vote on forums threads to see how much request there is for a certain thing ..).

Either way, going to close this ticket for now, as I don't think anyone will implement this in the next year as an option, even more given it is possible via NewGRFs.

Thank you again.
