### ISSUE TITLE
Suggestion: Diagonal bridges and tunnels

### ISSUE THREAD

**Issue by gbomfim** [OpenTTD/OpenTTD#7404]
1.9.0

Suggestion: Diagonal bridges and tunnels

No result

No reproduce

Is it possible?

**Comment by TrueBrain** [comment]
Thank you for your suggestion!

The best place to make suggestions is either our [forum](https://www.tt-forums.net) or IRC. For more information about either or how to make suggestions, please see https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests.

I am going to close this issue now; not because I think the suggestion is bad, but because sadly this is not the place for suggestions. I hope you understand!

**Comment by gbomfim** [comment]
Ok
