### ISSUE TITLE
Vehicle waiting at station affects cargo age rating even if it did not pick up cargo

### ISSUE THREAD

**Issue by PeterN** [OpenTTD/OpenTTD#7430]
## Version of OpenTTD

master-g21d9e87b4, but affects any version for about 12 years.

## Expected result

Cargo age rating should be affected only if cargo is picked up.

## Actual result

A vehicle waiting at a station will reset the time since pickup despite not actually loading. 

## Steps to reproduce

This can be seen more clearly by setting a long timetable wait time for the vehicle, so that it is still waiting long after it is full. This also happens if a very long train enters a very short station, so that the vehicle will be delayed a long time.

I believe the issue is caused by 8ef0cbbdf5bf72d2901d8afb898aee5e8d601d01 which resets the days_since_pickup (renamed since to time_since_pickup) for a cargo regardless of whether the cargo was picked up or not.

That commit was a fix for two issues #1139, #1143 which suggests that cargo rating and thus cargo delivery to stations was not working properly but I don't know all the details.

Possibly if the algorithm is fixed there's some kind of chicken & egg situation with station rating and therefore cargo loading. However, this is so old it may not be applicable any more. I haven't had much chance to look further into it.

A possible solution may be to revert the change (unknown side affects, but seems most correct) or perhaps only reset the timer once per station visit instead of every possible loading loop.

**Comment by PeterN** [comment]
This was buried away on the forums for over a year, but it seems people knew about it but didn't consider reporting an actual bug.

https://www.tt-forums.net/viewtopic.php?p=1200089#p1200089

**Comment by EgyLynx** [comment]
Are youre test version 1.9.0 that think ?

**Comment by MingweiSamuel** [comment]
#1143 seems to describe pretty well why it was changed.
Cargo is only delivered to the top 2 serving stations by highest ratings. So a 3rd station gets no cargo. Before 8ef0cbb a reset only happens when "there's goods waiting at the station, and the vehicle has capacity for it". Since no cargo gets delivered to 3rd it can never reset the `time_since_pickup` and the rating stays low, feedback loop.

I made a possible fix below which only resets time_since_pickup iff "the vehicle has capacity for it".
Its still a question whether this is a bug or a feature since its been in the game so long.. with this simple fix you could still possibly cheese the system by have a train load -> transfer over and over at the station

Another option could be to only trigger the reset when a train begins to load, not during the process

**Comment by Hexus-One** [comment]
If a player attempts the load- transfer cheese as you suggested then the station rating will suffer anyway from the amount of cargo waiting at the station, so i think that won't be an issue :)

**Comment by MingweiSamuel** [comment]
That is a good point. Cheese will still provide a temporary boost. And there would be other ways to cheese, but at a certain point just playing as intended is easier.

Small side note, the title of this issue should probably be changed to something like "Vehicle waiting at station affects cargo *pickup time rating* even if it did not pick up cargo" since "cargo age" is a different unrelated thing afaik
