### ISSUE TITLE
Autorenew vehicle option to Basic settings

### ISSUE THREAD

**Issue by Wahazar** [OpenTTD/OpenTTD#7525]
Autorenew option is under "Expert" category, thus is not visible by default.
According to large number of new user questions I propose to move this option to 
the "Basic" category.

**Comment by nielsmh** [comment]
That, or combine it with the autoreplace functionality.

**Comment by nielsmh** [comment]
https://github.com/OpenTTD/OpenTTD/blob/e4414471dd10c3afebc49f3cc7c51f76852b08e0/src/autoreplace_cmd.cpp#L57-L58

So is it really only by convention that you're not allowed to autoreplace with the same model? I'd personally be happy to have "selective autorenew" that way. There should probably be a guard that only allows when-old autoreplace with same model, so you don't have vehicles renewing every time they visit a depot.

**Comment by giordy** [comment]
This feature is very important, in my opinion. Imagine this scenario, which just happened in a game I'm playing:

- money is **very** tight because of inflation, infrastructure maintenance, etc...
- my company owns
  - 40 trucks model A
  - 50 trucks model B
  - 20 trains model T (very expensive)

Let's say that the 50 trucks model B work very well for me and I need to keep using them: they still have great reliability and they have the cargo capacity that I need. 

As it is now, I simply have no easy way to renew them because:

1. if I enable auto-renew in the settings, the game will also replace trains and other vehicles (f.e. trucks model A) that I might not want to renew right now because I want to upgrade them to some newer model, dismiss the route or because I want to save the money for other things. Quite a few times a train being unexpectedly automatically renewed destroyed my finances.
2. if I don't enable auto-renew, I'm forced to waste a lot of time in manually renewing 50 trucks by sending them to the depot and manually buying new ones, copying orders, etc... The job is even more tedious because I cannot even do it all at once since my finances are tight. Also tracking down all the vehicles is extremely tedious.

Please implement this.
