### ISSUE TITLE
Too many statues/fountains are built in town centers.

### ISSUE THREAD

**Issue by Ben79487** [OpenTTD/OpenTTD#7651]
## Version of OpenTTD
OpenTTD 1.9.2 on x64 Windows 8.

## Expected result
Town would build a couple statues/fountains here and there in the central districts, still predominantly building other buildings

## Actual result
Disproportionate amount of statues/fountains in the center of town. 

## Steps to reproduce
Start game in 1950. Make a bus system so a town will grow quickly.
In a couple years, you'll start to find lots of statues/fountains in the central districts.

## Pictures
Note the **entire block** of statues and fountains near the coastline.
![Chinston Transit Corporation, 28th Nov 1956](https://user-images.githubusercontent.com/52835868/61152288-dceec600-a49c-11e9-8e6b-50566f690122.png)

**Comment by nielsmh** [comment]
Unfortunately this probably classifies as "by design". The default town buildings simply don't have enough building types for the inner zones in the earlier years.
I can't tell for sure, but it also looks like your screenshot is taken in Sub-arctic climate, which definitely has fewer building types available than the Temperate climate, further exaggerating the issue.

**Comment by andythenorth** [comment]
Similar issue occurs with theatres before about 1930 
<img width="800" alt="theatres_eh" src="https://user-images.githubusercontent.com/1780327/64081431-b3ae2180-ccf8-11e9-93bf-ea133e614a1e.png">

**Comment by TrueBrain** [comment]
As mentioned, this is by design, how ever sad that might be. There is not really a lot we can do about that :(
