### ISSUE TITLE
Crash on multiplayer

### ISSUE THREAD

**Issue by realrecordzLab** [OpenTTD/OpenTTD#7734]
## Version of OpenTTD 1.90
I'm trying to find new servers on macOS 10.13.6 but every time it will crash and I need to restart the game. Is there any fix?

**Comment by nielsmh** [comment]
The 1.9.3-RC1 version currently up at https://www.openttd.org/downloads/openttd-releases/testing.html fixes the crash bug, however there aren't any servers running that version just yet. We'll probably release 1.9.3 stable in a few days (or maybe even earlier).

You can also browse the servers via http://servers.openttd.org/ to find the IP address of one you want to try, and then connect directly.

Closing this ticket since the bug itself is solved.
