### ISSUE TITLE
export map into picture

### ISSUE THREAD

**Issue by mpavlase** [OpenTTD/OpenTTD#7813]
Hi all,

I've just created a patch (just ugly proof of concept) that do export map into plaintext format + another script to convert that exported format into ordinary bitmap picture (PNG).

Create plain-text export of rail tiles of map:
https://github.com/mpavlase/OpenTTD/tree/map-export

Python script to visualise:
https://github.com/mpavlase/openttd-map-export

**Comment by LordAro** [comment]
Hello! This looks like it could be quite interesting, but unfortunately I can't really tell what it is? How is it a benefit over the existing screenshot facilities (standard, zoomed & whole map)

Rather than exporting to an external file for another tool to interpret, we'd probably want it to write the images directly

**Comment by telk5093** [comment]
It looks like the [```minimap``` command](https://www.tt-forums.net/viewtopic.php?f=33&t=42845) which already exists in JGRPP.
(Exporting map into a image file is quite benefit to show to users (via website) how server is going.)

**Comment by mpavlase** [comment]
Thanks for pointing me to minimap - it basically does the same thing: export map into bitmap. I'm not so skilled in C++, so that's why I used Python to produce actual picture.

My patch persist game projection and main motivation was to get a plan of all rail tiles to be able it print on paper afterwards (in example).

**Comment by nielsmh** [comment]
I think for producing map images and network illustrations a better general approach would be to somehow wrap OpenTTD as a library, so you can use the original code to load and process the map data for whatever purpose, instead of inventing a new file format that would have to be maintained on both producer and consumer end.

**Comment by andythenorth** [comment]
Thanks for this.  Visualising the map in new ways is cool, but it doesn't really relate to the core game :)

Therefore I'm closing it as we try to keep the issue count low for OpenTTD, it helps us focus on things that are important and fun. Feel free to discuss in irc or request re-opening if you disagree. Thanks for contributing!
