### ISSUE TITLE
Negativ Integer values for GRF Parameters crashes the game

### ISSUE THREAD

**Issue by spnda** [OpenTTD/OpenTTD#7836]
## Version of OpenTTD
Unknown. Issue exists in 1.9/master and JGR. Probably exists in older versions aswell.

## Error
When a GRF Parameter has negativ integer values, clicking on the dropdown crashes the game.

![Assertion Error](https://cdn.discordapp.com/attachments/442748131898032138/645287362208858122/unknown.png)

## Reproduce
Example GRF to reproduce:
[grf.zip](https://github.com/OpenTTD/OpenTTD/files/3854457/grf.zip)

Link to the NML issue: https://github.com/OpenTTD/nml/issues/57

**Comment by planetmaker** [comment]
It shouldn't crash.
Yet, parameters are by design unsigned integer; thus a NewGRF allowing negative numbers is going beyond the specs of allowed value ranges. See https://newgrf-specs.tt-wiki.net/wiki/Action14#Allowed_value_range_.28.22INFO.22_-.3E_.22PARA.22_-.3E_.3Csetting-number.3E_-.3E_.22LIMI.22.29

The default values (for limits) are "0" resp. "2^32 - 1". 

Changing the interpretation of parameters to be signed requires a change and extension to the specs - or all existing NewGRF parameters would be interpreted wrongly

**Comment by Eddi-z** [comment]
Sounds like a signed/unsigned conversion bug going on. The value stored in the GRF should not be read as a signed integer, no matter what the author thought he put in there. but the dropdown seems to treat it as a signed value, which would mean even if the author set 2^32-1 as value, it would still trigger this bug

also... what would a dropdown with 2^32 entries even look like?

**Comment by glx22** [comment]
https://github.com/OpenTTD/OpenTTD/blob/7e22f243ed3b324df3da9dba5594c14b4e6794a0/src/newgrf_gui.cpp#L377-L382

  | min_value | 4294967295 | unsigned int
  | max_value | 1 | unsigned int
so of course the list is empty

**Comment by Eddi-z** [comment]
ah, so there's a guard missing for min < max (don't trust the GRF/author)
