### ISSUE TITLE
Cannot insert new order

### ISSUE THREAD

**Issue by jkjkjkjkjk** [OpenTTD/OpenTTD#7881]
## Version of OpenTTD
1.9.3.
Just "Can't insert new order ..." without further explanation: 
![image](https://user-images.githubusercontent.com/16571133/71549588-39e52680-29c0-11ea-9aec-b66855fadca0.png)

## Steps to reproduce
[Bugfix Transport, 13th Jul 2273.zip](https://github.com/OpenTTD/OpenTTD/files/4007484/Bugfix.Transport.13th.Jul.2273.zip)
Open save, switch to company no. 9,  select train no. 35, now try to add order to "West Raffhythe Airport" station. It is possible to add order to any other train station (even new), but not to "West Raffhythe Airport".
Found this issue (https://github.com/OpenTTD/OpenTTD/issues/6968), but I do not think it is related to it. Maybe some issue with airport closing?

**Comment by nielsmh** [comment]
This is a known bug in 1.9.3 (and that version only), same cause as #7789.
The workaround is to make sure the tile below the station sign belongs to the station in question, otherwise you can't make orders to the station.

It's unlikely we will release a fixed version of 1.9.3, since version 1.10 is getting closer. The bug is fixed in current beta versions, and if you prefer to stay on 1.9.3 you can also try e.g. the CityMania Client which should be fully compatible gameplay-wise, just has some UI changes.
