### ISSUE TITLE
Conflict in financial data.

### ISSUE THREAD

**Issue by autobus22** [OpenTTD/OpenTTD#7965]
## Version:
1.9.3

## Expect Result:
I expect to be getting consistent accurate financial statements about how my vehicles are performing.

## What is occurring instead:
I am receiving conflicting information on the performance of my vehicles and lines and how much they are making/losing. 

## How to reproduce?
It appears to occur any time I play in this version, both with and without various NewGRF's on, Both on servers and in Singleplayer. (The specific save does use a few NewGRF's and is a save from playing on multiplayer.)

![what2](https://user-images.githubusercontent.com/60402018/73291952-7f845180-4201-11ea-8a1c-fc987b935ee4.png)
![what](https://user-images.githubusercontent.com/60402018/73291953-7f845180-4201-11ea-81d2-18554fb46139.png)

[BUGGED.zip](https://github.com/OpenTTD/OpenTTD/files/4123916/BUGGED.zip)

**Comment by nielsmh** [comment]
Are you using any cargo transfer, either via explicit orders or via cargodist? If you do, do you have any feeder share greater than 0% set?

As far as I remember, the Finances statement uses the actual income and running costs of vehicles, while the vehicle list window (group display) uses the per-vehicle _profit this year_ figure which includes feeder share adjustments.
The feeder share adjustment is entirely "fake income", only the final delivery has real income, the transfer incomes are bookkeeping-tricks to make it look like the intermediate legs in the journey are contributing directly to the company profits.

**Comment by autobus22** [comment]
Yes, I do use cargodist: Practically all my services are feeders or have feeders. 

The thing is: If that is why this is happening, then shouldn't we expect the actual income from the finances statement to be lower or identical in all cases: not higher as is happening with my road vehicles?

Thanks for the help. 

Allthough: That's really annoying that you basically get conflicting income amounts that don't add up. :/

**Comment by frosch123** [comment]
There are 3 problems with comparing these numbers:
1. If you sell/crash vehicles, they will be removed from the vehicle list, and no longer be included in the list and its sum.
2. Refitting vehicles manually counts as running cost in the economy window, but does not affect the vehicle's profit. This is different to refitting via orders, which does affect the vehicle profit.
3. The already mentioned problem with transfers:
    * The economy window shows the profit after the final delivery.
    * The vehicle list shows the profit of partial deliveries, the cargo may still be in transit in other vehicles.
    * These two numbers can differ in both directions by the total of your transport volume.
      * Cargo that was transported by some vehicles in the previous year, but finally delivered this year, will be added in total to the economy window, but only partially to the vehicle list (the rest was already accounted the previous year). This effect dominated in the beginning of the year.
      * Cargo that was transported by some vehicles this year, but has not yet reached its final destination, will be added to the vehicle list, but not yet to the economy window. The effect replaces the previous effect throughout the year.

Would these things explain the "big" difference in the amounts in your game?

About fixing:
* (1) and (3) result in valid differences. I wouldn't know how this should be accounted differently.
* About (2): I guess manual refitting should count as construction cost?

**Comment by TheMowgliMan** [comment]
I have also had this problem (in the newest OpenTTD 13.0). This is a major issue in my game as it makes it seem that I should have huge profit margins, rather than barely scraping by. See the image attached. Like other people who've reported this issue, my game has CargoDist on asymmetric (Or symmetric with low return rate, I don't remember) for passengers, which is my primary cargo.

![OpenTTD 13 0 2_27_2023 6_13_00 PM](https://user-images.githubusercontent.com/96443213/221711308-cdf76081-42d9-4718-98e6-a788640a4155.png)

**Comment by TrueBrain** [comment]
Going to close this issue, as I think [this comment](https://github.com/OpenTTD/OpenTTD/issues/7965#issuecomment-579906500) gives more than enough reasons why those values don't add up.

And although I acknowledge the reporting of financial state isn't perfect, OpenTTD just isn't the game that closes their books every year, where credit and debit balances out. To reiterate, money can be invisible if you:

- Sold a train in that year
- Have transfers where credit distribution isn't fair
- Do (automatic) refitting on trains in that year

If anyone has a game without any of that, and still sees a big discrepancy between the amounts, do let us know, with a savegame, so we can analyse it further. But with the information we currently have, it just seems to be that the difference is because of how OpenTTD tracks these numbers, and the financial window is presenting the correct number :)
