### ISSUE TITLE
Text in cheat menu window is excessively dramatic

### ISSUE THREAD

**Issue by PikkaBird** [OpenTTD/OpenTTD#8034]
The options found in the Ctrl-Alt-C cheat menu window are valid solutions to several gameplay issues (otherwise, why would we have them?), but some users are put off using these options by the overly dramatic text in the window, which reads, in English:

"Warning! You are about to betray your fellow competitors. Keep in mind that such a disgrace will be remembered for eternity".

This text should be removed, so that more sensitive players do not feel it is "wrong" to use these options.

**Comment by LordAro** [comment]
Why is it not "wrong" to use these options in a normal game?

**Comment by Wolfolo** [comment]
I would just write that the usage of the cheats will be recorded in the savegame (what's currently on all the tooltips).
The plane crash cheat should be a setting, it's a play style rule.
The tooltip should explain what the cheat mean, some of them are a bit cryptic.

**Comment by alistaircarscadden** [comment]
> 
> 
> Why is it not "wrong" to use these options in a normal game?

Because it is a sandbox game, and it is not wrong to play it as you desire. You are free to make a scenario where you start with extra cash, so you shouldn't feel "disgraceful" to use a cheat if it is what you wish to do.

A player seeking out cheats knows what a "cheat" is for, and this isn't a competitive game.

Edit: Also, I think the text is cute. It reminds me of the Minecraft delete save "for eternity (or a really long time)" text. I think the first part is fine "You are about to betray your fellow-" where the word "competitors" could be changed to something more passive. The second sentence "Keep in mind that such a disgrace will be remembered for eternity" is not necessary.

**Comment by TinCanTech** [comment]
I think the _warning_ should be in Gold and Red Flashing letters.
