### ISSUE TITLE
AI estimated costs are 0 for commands that fail while returning a cost

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#8045]
## Version of OpenTTD
1.10.0-RC1
## Expected result
Get the estimated cost
## Actual result
Gets 0 as cost
## Steps to reproduce
AIVehicle.CloneVehicle is a command where estimating costs, while the company doesn't have enough money to clone the vehicle, returns the cost for purchasing the vehicle, and a failed error.
Due to failing, the script engine doesn't even adds the estimated cost, as per the following code...

https://github.com/OpenTTD/OpenTTD/blob/55e81d39737ccf7d7bbcca92d997ac4db862176d/src/script/api/script_object.cpp#L331-L346

Estimated CloneVehicle cost as a human company returns a cost, but for a script, it returns 0.

**Comment by TrueBrain** [comment]
If a `DoCommand` fails, the cost can be non-zero (internally), but it has no meaning what-so-ever. For `CloneVehicle` it might be okay, but we have other commands where it is not even close to the true cost (example `BuildRoadDepot`). Basically, a `DoCommand` only guarantees the cost is correct if it returns a success code. Otherwise, it strongly depends on the command what it means.
So for an AI, the cost should be kept zero if the command failed, as it would confuse AI writers otherwise, as they may jump to the wrong conclusion. Only under certain circumstances it would be the correct costs, but most of the time it would be either zero or any number between zero and the true cost.

So on that basis, this ticket is invalid and can be closed.

But, between the lines, I read that you mean that `CloneVehicle` cannot be estimated when the cloning would cost more than the money you have. Where most commands return you the estimation no matter if you have the funds or not, `CloneVehicle` errors out, and withholds you the information how much you are short.

This is a problem specific for `CloneVehicle`, and not so much a generic problem. Some commands cannot predict their cost without influencing the game-state (`RemoveLongRoad`, `FoundTown`, `ClearArea`, `LevelLand` and `CloneVehicle`, to be really exact about it). All these functions solve it in such a way that the cost can be estimated, except for `CloneVehicle`.

`CloneVehicle` checks manually, no matter if you are estimating or not, if you have the money to pay for the cloning. And this seems to be the real bug here, and the one you (tried to) report.

Which leaves us with two ways to solve this problem:
1) don't check for money when estimating,
2) change `CloneVehicle` to use the same system as the other exceptions.

While 1) is easiest, 2) removes an exception to the exception. But 2) also makes the most impact in how things are handled. After looking at the code carefully, 1) seems to be the better way, and one could even make the suggestion the other 5 should be converted to this method too. But that is for another day.
