### ISSUE TITLE
Escape button should open a game menu

### ISSUE THREAD

**Issue by aha999** [OpenTTD/OpenTTD#8059]
## Version of OpenTTD
OpenTTD 1.10.0
## Expected result
When the Esc button is pressed, it would be expected that a game menu would open 
## Actual result
Pressing Esc button doesn't do anything

**Comment by LordAro** [comment]
Which game menu? We have several

**Comment by aha999** [comment]
a game menu that would have a classic game menu design with options like save, load, quit, settings.....

**Comment by LordAro** [comment]
Perhaps it should, but we don't have one of those, so it'd be rather difficult to do so. Perhaps we should have one? Perhaps it should open up another of the existing windows (save game?).

But until then, this issue is too vague and too much like a suggestion. Contributions are appreciated as ever.
