### ISSUE TITLE
Add option to (de)couple wagons at stations in Orders list

### ISSUE THREAD

**Issue by GrupoDO** [OpenTTD/OpenTTD#8084]
Hi!  Many european trains are composed from wagons from diferent countries that makes a unique train. For example, the EN 476 Metropol /456/406 is a train that runs from Budapest Keleti to Warszawa Wschodnia and pick ups passenger carriages at several stations such Breclav (CZ), Bohumin (CZ) and Krakow (PL) and drop off carriages to other directions

I think that would be great a feature to make this couples and decouples at stations.

**Comment by nielsmh** [comment]
You are not the first to ask for this. There are two reasons it doesn't exist, one is that it would be technically very difficult to implement and get working reliably. The other is that making a good user interface for it that would also allow the player to handle all the unfortunate situations that can occur will be a massive challenge in itself. (What if one train is late, and as a result something else has dropped off cars at a platform and now blocks the path, and there's nothing around to move those cars out of the way? OpenTTD isn't well suited for that kind of micromanagement.)

Someone did implement a prototype two years ago, see this forums thread: https://www.tt-forums.net/viewtopic.php?f=33&t=83374

I'm closing this ticket because it won't serve any purpose being open. If you want this to happen you will have to actively help out those trying to develop the feature, and raise it to the quality it would need to get merged in.
