### ISSUE TITLE
Swedish translation issue in the performance rating window

### ISSUE THREAD

**Issue by DonaldDuck313** [OpenTTD/OpenTTD#8092]
In the first row in the performance rating window, "vehicles" gets translated to Swedish as "vägfordon", which means "road vehicles". This is confusing since the rating includes any type of vehicles, not just road vehicles. It should just say "fordon", not "vägfordon".

![enter image description here](https://i.stack.imgur.com/5wYWV.png)

**Comment by sheepo99** [comment]
Hello,

I would recommend you to sign up as a translator if you wish to fix this issue yourself. We're always on the look out for native speakers willing to lend a hand. Usually you can sign up [here](https://translator.openttd.org/), but because formal requests always take time to process, you can just [join us on IRC](https://wiki.openttd.org/IRC_channel) and ask about helping with translation. :)

**Comment by Yexo** [comment]
As explained to way to fix this is to either contact the current Swedish translators or sign up as one yourself. Either way, translations are not handled via GitHub, so we cannot resolve this here.
