### ISSUE TITLE
Feature: Map tooltips

### ISSUE THREAD

**Issue by minexew** [OpenTTD/OpenTTD#8094]
There is a [community patch](https://www.tt-forums.net/viewtopic.php?t=75069) by adf88, based on earlier work by MJP, that adds tooltips for map objects like industries and towns.

If I turned it into a pull request, would there be interest in merging it into OpenTTD master?

![screenshot](https://i.imgur.com/AOOTJ5I.png)

**Comment by andythenorth** [comment]
These will be interesting for industries that have 16 in / 16 out cargos :)

**Comment by sheepo99** [comment]
I do not agree with this. Tooltips should remain an exclusive part of the GUI tools, not a label to map objects. It also introduces a clear redundancy because this is what clicking twice on a map object to summon the object window literally is for. My suggestion would be to introduce an advanced setting that would allow object windows to pop automatically upon hovering the mouse above them.

**Comment by minexew** [comment]
Preferably, this would be done as an installable "add-on" via the scripting API (like WoW does with Lua), but I don't think any UI functions are exposed to scripts at this time.

**Comment by MiguelHorta** [comment]
Novapolis/citymania in their client have something similar but fairly more readable. 
![TheDude_client_changes](https://user-images.githubusercontent.com/20793664/80092078-112e0180-855a-11ea-9b6d-a248becca932.png)


It does breaks the expected tooltips' visual style, not sure if that is acceptable.

**Comment by 2TallTyler** [comment]
Years late, but I'd be interested in such a PR. It's included in JGRPP so you could potentially upstream it more easily from there.

Anyone can feel free to open a PR for this, but for now I'll close the issue now that it's been answered, to keep the issue tracker down. 🙂
