### ISSUE TITLE
Loading old TTD save crashes game (station / oil rig related)

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#8108]
## Version of OpenTTD
Release: 1.10.1
Nightly: 20200426

## Expected result
In both versions, the savegame loads correctly.

## Actual result (Release):
The game loads normally, but crashes after a few days if you demolish the bridge located at tile 0x299A (154, 41).
Crash log (after demolishing everything): [crash_oil_rig_1.zip](https://github.com/OpenTTD/OpenTTD/files/4573793/crash_oil_rig_1.zip)
Crash log (after demolishing bridge at 0x299A): [crash_floating_train.zip](https://github.com/OpenTTD/OpenTTD/files/4573929/crash_floating_train.zip)

Additionally, demolishing the bridge at tile 0x4181 (129, 65) causes the train on it to perpetually say "No Power".

## Actual result (Nightly): 
The game asserts here:
https://github.com/OpenTTD/OpenTTD/blob/fde28ec0b0b85451bfa80345d2b45e92ddba1655/src/station_cmd.cpp#L4205
This is called during the station-based tileloop at https://github.com/OpenTTD/OpenTTD/blob/57553cd8098ac003b3d5df6b9778214e6933c5d7/src/saveload/afterload.cpp#L945
Crash log: [crash_oil_rig_nightly.zip](https://github.com/OpenTTD/OpenTTD/files/4573795/crash_oil_rig_nightly.zip)

## Steps to Reproduce
1. In a release version, load the attached savegame.
2. Pause the game.
3. Give yourself a few billion.
4. Demolish everything.
5. Wait up to 30 days.
6. Crash

1. In a nightly version, load the attached savegame.
2. Crash

## Savegame
[#3601 - TRT01.zip](https://github.com/OpenTTD/OpenTTD/files/4573788/3601.-.TRT01.zip)

**Comment by SamuXarick** [comment]
I commented out the assert, and I get a crash about "vector iterators incompatible", when loading the savegame, here:

https://github.com/OpenTTD/OpenTTD/blob/fde28ec0b0b85451bfa80345d2b45e92ddba1655/src/saveload/afterload.cpp#L2196-L2210

At the part where it says `if (remove) { DeleteAnimatedTile(*tile); } else { tile++; }`,
It iterates the first time. Then `iter++` at the line just down there, is not called. because `remove `is `true`. So it then crashes with iterator incompatible next loop. PS: Only crashes in debug build, not release build.

**Comment by SamuXarick** [comment]
The floating train crash requires Settings > Limitations > When paused allow: All actions.
