### ISSUE TITLE
Autoreplace does not report failures due to refittability

### ISSUE THREAD

**Issue by giordy** [OpenTTD/OpenTTD#8153]
## Version of OpenTTD
1.10.1
## Expected result
When I'm setting some vehicles to be replaced with some policy (either immediately or when they're old) I expect them to be replaced
## Actual result
Sometimes it happens that some vehicles get "stuck" indefinitely and never get replaced.

## Steps to reproduce
1. Load the save game attached: [bugboats.sav.zip](https://github.com/OpenTTD/OpenTTD/files/4639447/bugboats.sav.zip)
2. The first company has some "Clipper" ships that are 38 years old. They are set to be replaced immediately but they never get replaced.

**Comment by andythenorth** [comment]
Are they getting serviced?  

A possible cause for this is vehicles unable to find a depot.

**Comment by giordy** [comment]
Some of them go to depot to refit and other ones pass close to the depots so they should have chances to enter for maintenance.

I also tried to send them manually but they never get replaced. Dozens of other ships (even on the same route I think) got replaced correctly but these ones are stuck somehow.

It happened as well in another game to a friend of mine, this time with road vehicles.

**Comment by nielsmh** [comment]
I traced through the code, it turns out the autoreplace fails (silently) because the replacement vehicle can not be refitted to the correct cargo types required for the vehicle's current cargo or any refit order the vehicle has.
For example, company 1 ship 3 has an order to refit to passengers (order 7), but the replacement vehicle (Little Cumbrae Freighter) can not carry passengers.

The bug here isn't that the replacement fails, but that you don't get any feedback why it fails.

**Comment by James103** [comment]
So the message would be something like "Autorenew failed on Ship 3 ... Could not refit vehicle" plus an optional "to all cargoes" in the case of refit orders?

**Comment by nielsmh** [comment]
There's two cases to report really. Ideas for error messages:
- New vehicle can not carry {cargo} *(currently carried cargo)*
- New vehicle can not carry {cargo} as required by order {index} *(refit check for orders)*

A bonus feature would be to check all orders for refit-compatibility instead of bailing on first failure.

This is where the check happens:
https://github.com/OpenTTD/OpenTTD/blob/e31def197f3e15bf5b3c31c6f9ad53b3d1232e2d/src/autoreplace_cmd.cpp#L295-L297

**Comment by Chr12t0pher** [comment]
Happy to try and tackle this one! I've added a string and put it into `CommandCost` so it displays a failure message:

![image](https://user-images.githubusercontent.com/10013655/82841923-a0b72f00-9ecf-11ea-8db3-cf3f79ccf5ae.png)

For more information we'll have to modify the variables that are passed to the string template, I can see this is done here:

https://github.com/OpenTTD/OpenTTD/blob/c972a63c8cbee7fa8d6d5af2cbbecb8c75ee561a/src/vehicle.cpp#L1058-L1067

Should I be adding some extra logic here to set a third parameter (cargo type) if the error message is my new one? Seems like there's a couple of conditionals for building the message depending on the error here already.

Made a barebones save for easier testing too - [bugboats.zip](https://github.com/OpenTTD/OpenTTD/files/4678745/bugboats.zip)

**Comment by glx22** [comment]
Feel free to open a PR @Chr12t0pher, will be easier to discuss with the code
