### ISSUE TITLE
Consider upgrading to C++17

### ISSUE THREAD

**Issue by fsimonis** [OpenTTD/OpenTTD#8200]
## Context
OpenTTD currently requires C++17 for the visual studio compiler and C++11 for other compilers.
It may be a good idea to upgrade the required standard to C++17 altogether.

## Upsides
* Uniform requirement to prevent developers on Windows to accidentally commit code that requires C++11 or 14.
* Keeping up with the standard is always a good idea
* Opens-up more options to simplify and clean-up the code with
  * additional tools for locking
  * generic lambdas for saner STL usage
  * if/for initializer to reduce variable scopes
  * nested namespaces _in case of future adoption_

## Downsides
* Lifts the compiler baseline for most relevant features:
  *  GCC 7 
  * Clang 4 (5 for class argument deduction) 
* Drops support for
  * [Debian stretch (oldstable)](https://packages.debian.org/stretch/g++)
  * _Consequently_ [Ubuntu 16.04 LTS](https://packages.ubuntu.com/xenial/g++), which reaches end of standarad support in April 2021.

_edit: clarify relationship of ubuntu and debian packages_

**Comment by embeddedt** [comment]
> Drops support for Ubuntu 16.04 LTS, which reaches end of standarad support in April 2021.

You can actually get a newer GCC version on Ubuntu 16.04 from this [official PPA](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test). It's quite stable; I used it till I upgraded to 18.04 and never had any issues.

**Comment by fsimonis** [comment]
> You can actually get a newer GCC version on Ubuntu 16.04

The OpenTTD Debian package would than depend on a package from a ppa. The package is imported from the Debian repository, thus depending on a Ubuntu ppa is not possible.

Simply dropping future updates would probably be the most straight-forward solution, but this has to be decided by the maintainers.

**Comment by techgeeknz** [comment]
We could always hold off until Debian finally gets around to upgrading to C++20 (sometime around 2030) :grin:

FWIY, I am running Debian 9.12 as a templateVM in QubesOS R4.0; and that uses GCC 6.3.0.
I also have available GCC 7.3.1 in the default Fedora 26 templateVM, assuming I can figure out how to install the build dependencies; but I much prefer Debian.

The practical upshot of this, I guess, is that if you want stuff tested against various different compilers on different versions of Debian or Fedora; I can probably do that. QubesOS makes it ridiculously simple to create and spin up a new VM for whatever purpose (even including "disposable" VMs, which are automatically destroyed as soon as they are closed), so it would be no trouble at all to compile the source against multiple different configurations; each in its own unique, clean environment.

**Comment by fsimonis** [comment]
The purpose of this issue is to lift the minimum C++ version to further modernize the baseline.

Testing with the newest compilers is independent of this. I don't have an insight on the testing side of things.

**Comment by TrueBrain** [comment]
Very similar to #8201, and I won't repeat that whole story: we are constantly evaluating if switching to C++17 or higher is worth the effort. It is not something we will do "because we can", but it will only happen if someone puts in the work to use C++17 features that are considered an improvement and worth our while. We have seen that with the bump to C++11, and that cycle will repeat itself :)

So any Pull Requests that use C++17 which cannot be done as clean and nice in C++11, will be considered and might be the reason to switch. Till then, C++11 works just as well :) (well, and C++14 for MSVC, as .. MSVC is always the odd duck :P) If you had anything specific in mind with writing this issue, feel free to open a (draft) Pull Request, and we can talk it over!
