### ISSUE TITLE
Vehicle lists "Manage list" options inconsistent

### ISSUE THREAD

**Issue by SHADOW-XIII** [OpenTTD/OpenTTD#8206]
## Version of OpenTTD
1.10.2

## Expected result
"Manage list" option should give possibility to replace vehicles and possibly option to save all vehicles to a new list

## Actual result
"Manage list" option in "Station vehicles" list is fairly limited
"Manage list" option in "Shared orders" list also limited as above

## Steps to reproduce
It's possibly a feature request but vehicle lists are inconsistent depending how they are open.

When opening a station window, there's button on the bottom to open all vehicles that use this station, ie. all trains, all road vehicles etc. It shows a new window with a list of those vehicles and button (drop down) with "Send for Servicing" and "Send to Depot".
The vehicles list showing "Shared Orders" vehicles (accessible from Orders window, with small button on the right) is also limited same as "Station vehicles" list

The "Manage List" options should be expanded, ie. to "Save as a new vehicle list" and "Replace vehicles" (like in a Vehicles list (accessible from the top/menu button).

![image](https://user-images.githubusercontent.com/15386111/83974227-b1aa6c00-a8e3-11ea-9191-cb433a02d43d.png)

![image](https://user-images.githubusercontent.com/15386111/83974231-b96a1080-a8e3-11ea-8e79-3f3a471a323d.png)

**Comment by SHADOW-XIII** [comment]
as per discord chat, adding vehicles to a new group might have been done in: https://github.com/JGRennison/OpenTTD-patches/commit/ca9f6411cce7dbabaa2224ba58bb68acd6fd5848

not sure about "Replace vehicles" option

**Comment by danuker** [comment]
I agree that replacing vehicles from the "Shared orders" or from a station list would be very useful in-game.

This is because, when upgrading trains to a dual-headed locomotive, I want to see the trains that would fit in my newly-expanded stations.

If this is difficult to program due to the dynamic nature of the orders, I would also appreciate a "create group" option, to make the list of vehicles static.

**Comment by 2TallTyler** [comment]
Replacing vehicles from shared orders isn't possible because autoreplace can only be done for actual groups, that you can see in the groups menu. I think allowing this for implicit groups that don't show up in the groups menu would be confusing, since you couldn't easily find it -- in the groups menu, groups with autoreplace enabled have an icon. Outside that, you'd have to find the right vehicle or remember what station contained the list...which sounds like a nightmare to me. 

That said, #10890 added a dropdown option to create a new group from an implicit group, which was one of the requested features and will make the desired action much easier. As such, I am going to close this issue. As always, if someone disagrees, feel free to re-open. 😃
