### ISSUE TITLE
Crash while maximizing the window on first run after compilation

### ISSUE THREAD

**Issue by oss-vineet** [OpenTTD/OpenTTD#8213]
## Version of OpenTTD
20200609-master-gee570e1b6d

## Expected result
Program shouldn't crash

## Actual result
Program crashes

## Steps to reproduce
After cloning from the repository and compiling (followed the instructions in COMPILING.md) on my Raspi 4 4GB running Raspbian OS 32-bit, I opened the game and got the pop-up about downloading graphics. So I click yes, and while it was downloading, I maximised the window and that caused it to crash. Could it be a memory error or because the graphics weren't installed yet, it had that behaviour? Because the next time I opened it, the graphics suddenly appeared and the game ran just fine. Anyway, the log is attached as follows

[crash.log](https://github.com/OpenTTD/OpenTTD/files/4755321/crash.log)

**Comment by techgeeknz** [comment]
Are you able to reproduce this? If so, can you attach the output of running the program with "-d1"?

It seems like this could be caused by a bug in one of the SDL video drivers, but there is not enough in the crash log to ascertain when the crash is happening.

**Comment by techgeeknz** [comment]
It could also be that you just "got lucky" by causing the window to be invalidated at an inopportune moment. Either way, reproducing the crash with debug logging enabled will be very helpful for tracking down and fixing the culprit.

**Comment by TrueBrain** [comment]
Hi @vineet131 ,

Did you have time to try this with `-d1` enabled?

I cannot reproduce this problem in a similar setup, and I tried really hard ... I am really sorry. It really does mean we need more information.

For now I am going to close this issue; not because I don't believe there is no bug here, but because we haven't heard back from you in several months. If you can still reproduce this with `master` (and I would really appreciate it if you can try), please reopen this issue and we take a further look!

Thank you!
