### ISSUE TITLE
Passwords not autosaving

### ISSUE THREAD

**Issue by quinm0** [OpenTTD/OpenTTD#8303]
## Expected result
When the dedicated server has completed an autosave, upon restart all companies should then be loaded in with their passwords 
## Actual result
When the dedicated server has completed an autosave, upon restart all companies are loaded in without their company passwords
## Steps to reproduce

1. Start server
2. Connect as client
3. Create company and set a password
4. Wait until the server restarts
5. Disconnect client and stop the server
6. Start the server
7. Connect to server as created company
8. Observe company does not require password

**Comment by glx22** [comment]
Not saving passwords is intended.

**Comment by quinm0** [comment]
Oh, interesting. 
Why is that? I have to restart my server host sometimes and wiping all my friends passwords is kind of not great.

**Comment by James103** [comment]
I think it's a possible security risk. Someone could download the save game off of the server (using their local client), extract the passwords out of it, and then if they're quick enough, use them to join companies and do evil things that way.

**Comment by quinm0** [comment]
Oh, that's fair. 
Would it be possible to save the passwords in a separate file on the server host? 
Then the clients could just authenticate against that and the passwords wouldn't be downloaded in the autosave

**Comment by nielsmh** [comment]
Yes, some servers may want to publish the current game state as a download in some form, and if the passwords were saved either directly in the savegame file, or as a separate file next to it, there would be a large risk of the passwords being leaked. While everyone ought to understand that OpenTTD company passwords are not secure, you never know what kind of personal information someone might use as a password, so better safe than sorry.

The real solution, which would require a ton of new work and infrastructure, would be a way of having persistent client identities, so a client can prove who the player is to the server in some way, and the server can then grant the client something in the game (like control of a company).
If that was in place, the server would be able to store a list of player fingerprints that have access to each company instead of using company passwords, and that would be secure.

**Comment by quinm0** [comment]
I'm not 100% familiar with any of this code. I cloned the project and tried to read through to gain some understanding, but that didn't work out.

But I'm curious why there'd need to be persistent client identities. I understand why we can't save passwords in the savegame file. But to create an extra step between the server password and joining a company feels like it could be done away from the rest of the application. It's just shifting the storage of the password and then checking against it when someone joins a company. No complicated fingerprinting. Just enter your password like you do today. If it's set up that way then peoples companies aren't unprotected in the case of a server reboot. The fingerprinting isn't a bad idea, but it does "require a ton of new work and infrastructure"

Like I said, I have no context about the project and I'm still trying to learn. But My curiosity has gotten the best of me :) 
Thanks for time :+1: Sorry if my idea doesn't make sense

**Comment by TrueBrain** [comment]
Your idea does make sense, just needs a bit more nuance in order for it to work :) Storing passwords of other people locally is a huge security risk, and not one we should encourage :)

But fear not, we have been looking into this. It resulted in a draft of an addition we are considering for OpenTTD: https://github.com/OpenTTD/OpenTTD/discussions/8420

This should solve your issue too :)

For now I am going to close this issue if you don't mind, as this is not a bug (but working as intended). Hopefully soon, but not likely in our next (1.11) release, we have resolved this issue for you :)
