### ISSUE TITLE
Sorting of produced cargo for industries with multiple products are inaccurate

### ISSUE THREAD

**Issue by no1wafer** [OpenTTD/OpenTTD#8316]
## Version of OpenTTD
1.10.3

## Expected result
In Industries dialog, when doing Sort by Production on Produced cargo such as Oil, Livestock, and Grain, the sort order is exact for that product.

## Actual result
The sorting is approximately in order
![image](https://user-images.githubusercontent.com/24205715/94223887-965f7d00-ff23-11ea-929b-3e9a71b6c27a.png)

## Steps to reproduce
Open Industries dialog, set Sort by to Production, change Produced cargo to Oil, Livestock, Grain, or Passenger

**Comment by stormcone** [comment]
This is caused by how the production sorter works. It takes into account the total amount of produced cargoes.
(1,000 litres of oil = 1 item, 1 passenger = 1 item, 1 tonne of coal = 1 item)
For example:
Tudningstone Oil Rig produces 336,000 litres of oil and 12 passengers, in total 348 items
Munford Oil Rig produces 342,000 litres of oil and 6 passengers, in total 348 items
Canley Oil Rig produces 315,000 litres of oil and 30 passengers, in total 345 items

**Comment by no1wafer** [comment]
Thanks for the reply.
I can understand that if I choose "All cargo types" the sorter combines the two cargoes, but shouldn't it just look at whatever is chosen when only one of them is selected?
Thanks!
