### ISSUE TITLE
Automatically create folder

### ISSUE THREAD

**Issue by donno2048** [OpenTTD/OpenTTD#8327]
## Expected result
I expect the software to ask me where to put external files or to put it in the default installation folder
## Actual result
When I launch the exe it creates an _OpenTTD_ folder in my PC without asking me where to put it

**Comment by Eddi-z** [comment]
you haven't installed many games in the last 20 years, did you?

**Comment by Eddi-z** [comment]
Slightly longer explanation:

installation folders are protected and can only be modified with administrator privileges. And since you should not play games with Administrator access, games have adapted to save user data in one of two places:

1. "Documents", where the user might see it (e.g. if he's looking for screenshots he just made, or wants to add mods)
2.  "Appdata", where most users never ever look.

also, most users would never change the default locations, so asking for them would annoy more people and help almost nobody.

if you want to change the default locations where files are saved, there is a section in the readme about that.

**Comment by donno2048** [comment]
Oh, thanks for the explanation...
