### ISSUE TITLE
HTTP endpoint for online content

### ISSUE THREAD

**Issue by a-gierczak** [OpenTTD/OpenTTD#8334]
Hey guys!

Excuse me for not using the template, but I don't really have a bug to report, just want to ask for some technical guidance.
I'm currently developing a web dashboard for managing a dedicated OpenTTD server. Thought it'd be neat to have a feature where one could install NewGRFs directly from the dashboard because as far as I know currently the easiest way to install GFRs involves installing them on the desktop client and copying files & configuration to the server.

I've looked into [network_content.cpp](https://github.com/OpenTTD/OpenTTD/blob/13cc8a0ceec90def39cbcb84135a0bf039793a6f/src/network/network_content.cpp) and for my understanding, it looks like it's fetched via raw TCP packets. I've been wondering if there's any HTTP version or API exposed by `https://content.openttd.org/` or other resources? And are you guys are okay with consuming this content by third-party apps?

**Comment by TrueBrain** [comment]
We have an open issue at bananas-api repo (https://github.com/OpenTTD/bananas-api/issues/29), with the request to add download URLs to https://bananas.openttd.org , which would allow you to download BaNaNaS content via de web. This would also allow any third-party to download these files and put them in the right place, if they like.

Sadly, this issue currently isn't being worked on, so there currently is no way of downloading BaNaNaS content over HTTPS in any sane and/or legit way. The OpenTTD client uses both a custom TCP protocol, but also HTTP (without the S), as OpenTTD client doesn't have an SSL library. Using this HTTP for third-party I would strongly advise against; both as it is not meant for third-party apps, but also because it is HTTP-only.

So for now I am going to close this issue; not because I don't agree that this functionality is useful, but because we have an open [ticket](https://github.com/OpenTTD/bananas-api/issues/29) for this already. You could however, if you like, leave your use-case there so it gets more priority to fix. And, of course, if you feel up to it, we would love contributions on these repositories to add functionality like this.
