### ISSUE TITLE
Airports: Improper aircraft movement when the northernmost airport tile is not part of the layout

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#8437]
## Version of OpenTTD
Current master (2c8c6d42).

## Expected result
Aircraft movement is as expected when the northernmost airport tile (lowest tile index corner of the airport layout bounding rectangle) is not part of the airport layout.

## Actual result
Aircraft movement is not as expected when the northernmost airport tile (lowest tile index corner of the airport layout bounding rectangle) is not part of the airport layout.

An airport layout with this property is OpenGFX Airports 0.5->Hub->Intercontinental->Rotated 180°.
See attached savegame.

Observed issues include:
1. If the height of the aforementioned tile is not equal to that of the rest of the airport, the aircraft will land and subsequently taxi/etc. at that height. This may be above or below the ground level.
2. Helicopters landing at helipad 2 in the OpenGFX Airports 0.5->Hub->Intercontinental->Rotated 180° airport layout trigger an assertion failure due to Vehicle::tile being set to the aforementioned tile upon landing, where a MP_STATION tile is required.

## Steps to reproduce
See attached savegame.
For sub-issue 1, observe the movement of aircraft 7 and 8.
For sub-issue 2, press the "go" button for aircraft 1 to 6, and observe the subsequent assertion failure when the aircraft next come to land.
[Airport Testing Ltd, 2010-02-28.sav.zip](https://github.com/OpenTTD/OpenTTD/files/5743791/Airport.Testing.Ltd.2010-02-28.sav.zip)

**Comment by James103** [comment]
I can't open the save file when downloading from Google Chrome 87, as the browser forces you to delete the file because "it is dangerous" with no way to keep the file.

Edit: The above behavior was because I had Safe Browsing on. Affected users may need to disable Safe Browsing for a brief moment in order to download the save game.

**Comment by JGRennison** [comment]
> I can't open the save file when downloading from Google Chrome 87, as the browser forces you to delete the file because "it is dangerous" with no way to keep the file.

I'd suggest using a different browser if the behaviour can't be disabled.

**Comment by LordAro** [comment]
Making some progress on this

Bug 1 is fixed here - https://github.com/LordAro/OpenTTD/commit/b427f300c8eddc3d1c065f2d562c856257b50b95

Bug 2 is proving more tricky. Some notes of things I've found so far:
* Bug actually exists for all second (and third?) heliports, just only matters for the rotated airport with a missing tile at the top
* Helicopter has to actually descend to the heliport to trigger the bug - a helicopter taxiing to the heliport isn't enough.

**Comment by LordAro** [comment]
I'm by no means certain of this, but I *think* this boils down to the "reuse" of `AMED_SLOWTURN` for flight and turning on the ground.

The first helipad of the intercontinental has some sort of offset - so the helicopter has to move a bit before loading/unloading, and its `tile` attribute is set to its actual tile position.

The second does not have any offset and it lands directly on the helipad. This means that for some reason that I'm not clear on, the vehicle's `tile` is set to the tile of the airport, rather than its actual position.

This appears to be the case for the majority of helipads (I've not tested them all), it's just that this one for the intercontinental is the exception. This only matters for the (rotated) intercontinental airport due to it being non-rectangular

**Comment by JGRennison** [comment]
From doing a bit of printf debugging, the assignment of the airport tile to the vehicle is here: https://github.com/OpenTTD/OpenTTD/blob/master/src/aircraft_cmd.cpp#L952-L953

`tile` is assigned from `st->airport.tile` at the start of the function.

The landing altitude in `z` could also be wrong for the same reason as the first sub-issue.

If it's not an oil rig, setting x and y from v->x_pos and v->y_pos and recalculating tile from that looks like it would work.

```
		if (st->airport.type != AT_OILRIG) {
			x = v->x_pos;
			y = v->y_pos;
			tile = TileVirtXY(x, y);
		}

		/* Vehicle is now at the airport. */
		v->tile = tile;
```
stops the crash, but I'm not sure whether that's really valid/sensible.
