### ISSUE TITLE
Profit for each vehicle in vehicle lists aren't being updated regularly

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#8575]
## Version of OpenTTD
OpenTTD 20210114-master-g4f5990fa26
## Expected result
Profit this year for each vehicle in the list of vehicles should update at short intervals
## Actual result
Profit this year isn't updated on its own, only when switching groups or filter criteria.
## Steps to reproduce
Open list of vehicles, notice profit this year besides each vehicle.
![Unnamed, 1950-04-18](https://user-images.githubusercontent.com/43006711/104741669-6c83cd80-5741-11eb-8b08-4cde5eed73ba.png)

**Comment by LordAro** [comment]
Does it update if you move the window?

**Comment by SamuXarick** [comment]
Nope

**Comment by LordAro** [comment]
Yup, looks like vehicle group profit is calculated when the window is opened/initialised, rather than "live"

https://github.com/OpenTTD/OpenTTD/blob/0e62a398c7f03ae0bb75980d97dab3f72ecfb26c/src/vehicle_gui.cpp#L1541-L1543

https://github.com/OpenTTD/OpenTTD/blob/0e62a398c7f03ae0bb75980d97dab3f72ecfb26c/src/vehicle_gui.cpp#L207-L217

**Comment by andythenorth** [comment]
Introduced in https://github.com/OpenTTD/OpenTTD/commit/584df548f1bdfa27482aa995d151542abe4f0bca

**Comment by 2TallTyler** [comment]
Closed by #8715 (but somehow not actually closed at that time).
