### ISSUE TITLE
Goods not able to split to multiple destinations from one station

### ISSUE THREAD

**Issue by WhitePassRanger** [OpenTTD/OpenTTD#8592]
## Version of OpenTTD
1.10.3

## Expected result
Obtain goods from one station and deliver to multiple stations

## Actual result
Once a new route is set for goods from "Holbeach West" station, then the waiting goods become unavailable and will no longer load.  Goods that are unloadable appear to increase and very little is available to load.

## Steps to reproduce
Make any route to transport goods to another station regardless of method and may only get one or two cycles before they will enter "Holbeach West" and will no longer load.

## More info

This is a very weird glitch.  I first attempted to switch some of the goods that were piling up at this station to another town in the area to reduce what was waiting.  I used trucks in a spread-station truck depot that had been connected decades earlier, and as soon as I did, the trucks would not load and the trains would no longer load.  I went back to an older save and tried again.  I decided to try trains from the same station that I was already removing them from.  As soon as I did, the trains would not load, I switched the type of car they were loading into and I got one trip before they stopped working.  And once they stopped the other trains that used to load fine stopped loading.  I sold off the ones that didn't load and bought new ones with new orders and different cars and only got one trip before they also stopped loading.  I suspect I will have to use a separate station to pickup goods, but it has never been an issue before.

Let me know if there is any other information I can provide or if you have any other questions!  I appreciate the help and love playing this game, thank you in advance for all your help and the work you do!

Matt Craig

[Maverick's V8 Logistics 2 saves before and after.zip](https://github.com/OpenTTD/OpenTTD/files/5832882/Maverick.s.V8.Logistics.2.saves.before.and.after.zip)

**Comment by Eddi-z** [comment]
i think your trains take too long to load, then the link can time out and prevent further cargo being allocated for this route, until you manually send a train on the route.

you might want to try removing "full load" until you get a more even distribution between the two target stations

**Comment by LC-Zorg** [comment]
December 11, 1967 - this is the date of your save
January 11, 1968 - a month later, Cargidist divided production between the available stations.
It was enough to wait. ;)

This is not unknown behavior. Unfortunately, this is how cargodist works. The more vehicles and different connections you have, the more time it takes to update your connections and redistribute loads.

Yes, this is a problem, although it mainly concerns... the interface, and more precisely how the station window shows information. A lot of players don't know at all that the game can set destinations for payloads (only from stations to which there is a connection). It is enought to just go to the reddit vanilla server and see how the players build connections. I don't know if you know. If so, I suppose you might have missed the sort selection option.

In the default setting, you can see how much cargo is currently waiting at the station, and after pressing the **+** icon you can see in which direction this amount is waiting and through which stations (next +).
![Cargodist 1](https://user-images.githubusercontent.com/67662046/106071261-504f3b80-6106-11eb-9fff-eb8730f06fe1.png)

But you can also change the sort option to "planned" and then you will see in what proportions the load is divided between stations - these are constant values ​​(they change, but only when updating cargodist charts or when you delete a station - the label must disappear).
![Cargodist](https://user-images.githubusercontent.com/67662046/106071271-56451c80-6106-11eb-9979-d1e1b268d686.png)

**I believe there are at least two issues to be solved here:**
1. Reconstruction of the station window so that the information about the direction and planned quantity in the case of the cargodist turned on are visible on the top as default.
2. Forcing a faster cargodist update for the station or cargo where the connection was changed or added.

**Comment by WhitePassRanger** [comment]
Thanks LC-Zorg!

In all the years I've played, I have not ran into this!  I will make some changes and keep going.  Thanks for taking the time to look into it and taking the time to explain it.
