### ISSUE TITLE
Female CEOs might get the title of “Businessman” or “Chairman”

### ISSUE THREAD

**Issue by Wuzzy2** [OpenTTD/OpenTTD#8601]
## Version of OpenTTD
1.9.3

## The situation
In the highscore list and in company list (trophy icon), each player is awarded a title like “Engineer”, “Magnate”, “Tycoon”, and so on, based on their performance.

## Expected behavior
Each title is either gender-neutral or matches the gender of the company CEO (remember, players can choose the gender of the CEO).

## Actual result
If you're playing a female CEO, you might get the title of “Chairman” (`STR_COMPANY_LEAGUE_PERFORMANCE_TITLE_CHAIRMAN`) or “Businessman” (`STR_HIGHSCORE_PERFORMANCE_TITLE_BUSINESSMAN`).

## Suggested solution
The simplest solution I can think of: Change these titles to something gender-neutral: “Chairperson”, “Businessperson”. Wikipedia knows both these words, so they are probably fine.

**Comment by Ohrer** [comment]
No

**Comment by auge8472** [comment]
Because the game knows the gender of the manager I propose gender dependent strings for the manager title. IMHO …person reads unnatural even the terms may exist.

**Comment by 2TallTyler** [comment]
In the US, the trend has been toward gender-neutral titles rather than simply changing the suffix "-man" to "-woman." For example, here's [a document](https://apastyle.apa.org/6th-edition-resources/pubman-ch03-00.pdf) by the American Psychological Association (the "APA" in APA Style citations) listing Guidelines for Unbiased Language.

Gender-neutral language also benefits folks who are non-binary and don't identify as either gender.

"Businessperson" sounds natural to me, but an alternative to "Chairperson" is simply "Chair."

While I don't know how many players ever encounter the highscore list and company rankings (I never use them myself), I see no reason not to make this trivially easy and painless change.

**Comment by Eddi-z** [comment]
I'm not a native English speaker, so i will not take a side in this matter, but "fixing" this just for the English language will not suffice. So what is needed is a concept so that each language can decide on its own whether to use split or unified names.

Each language can already define grammatical genders, which may or may not include "male" and "female" genders, sometimes more. so we could let each language define which biological gender is mapped to which grammatical gender, and then the language could use the existing `{G ...}` syntax to split the names if necessary, or we could split the names in the base language, potentially forcing languages that don't distinguish between genders to duplicate the names

**Comment by Wuzzy2** [comment]
@Eddi-z: I'm not sure if this is the right way to go. Because "Businessman" and "Chairman" are only two titles from many possible other titles you can get. The majority of awarded titles is already gender-neutral ("Tycoon", "Magnate", "Engineer", etc.), I don't know if any translator is currently struggling with translating those (please enlighten me if there *is* a struggle).

But adding special treatment just for two words only because they currently happen to have "-man" inside in English might be overkill and overcomplicate things.

**Comment by ldpl** [comment]
@Wuzzy2 Idk about other languages but in Russian pretty much every word is gender-specific and those titles all translated as -man, basically. Luckily that's not as much of an issue in Russian as it is in English, at least not yet.

**Comment by telk5093** [comment]
There is no gender-specific translations in Korean about this issue :)
