### ISSUE TITLE
Assertion failed at line 582

### ISSUE THREAD

**Issue by maaaaaaaaaad** [OpenTTD/OpenTTD#8606]
Error Message:
Crash on Launch - "Assertion failed at line 582 of user/runner/work/openTTD/openTTD/scr/newgrf_house.cpp:IstitleType(title, MP_House)

## Version of OpenTTD
1.11.0-beta1

[crash.log](https://github.com/OpenTTD/OpenTTD/files/5863703/crash.log)
![crash](https://user-images.githubusercontent.com/39970290/105651604-52ef2e00-5e85-11eb-80a1-a1e6708c9758.png)
[crash.sav.zip](https://github.com/OpenTTD/OpenTTD/files/5863706/crash.sav.zip)

**Comment by TrueBrain** [comment]
Most NewGRFs are on BaNaNaS, except two.

WAS can be found here:
http://bundles.openttdcoop.org/worldairlinersset/push/v7673-2125/

newshipsw.grf can be found in the openttdcoop grfpack:
http://blog.openttdcoop.org/files/downloads/grfpacks/

A bit more readable backtrace:

```
#3  0x00007ffff72abf36 in __GI___assert_fail (assertion=0x5555564b2409 "IsTileType(tile, MP_HOUSE)", file=0x5555564b2130 "/projects/OpenTTD/OpenTTD/src/newgrf_house.cpp", line=582, function=0x5555564b23d0 "void DoTriggerHouse(TileIndex, HouseTrigger, byte, bool)")
    at assert.c:101
#4  0x0000555555e574fb in DoTriggerHouse (tile=6031629, trigger=HOUSE_TRIGGER_TILE_LOOP_TOP, base_random=107 'k', first=false) at /projects/OpenTTD/OpenTTD/src/newgrf_house.cpp:582
#5  0x0000555555e57795 in DoTriggerHouse (tile=6031628, trigger=HOUSE_TRIGGER_TILE_LOOP_TOP, base_random=0 '\000', first=true) at /projects/OpenTTD/OpenTTD/src/newgrf_house.cpp:620
#6  0x0000555555e57887 in TriggerHouse (t=6031628, trigger=HOUSE_TRIGGER_TILE_LOOP_TOP) at /projects/OpenTTD/OpenTTD/src/newgrf_house.cpp:628
#7  0x0000555555e571ff in NewHouseTileLoop (tile=6031628) at /projects/OpenTTD/OpenTTD/src/newgrf_house.cpp:546
#8  0x0000555555fac3dc in TileLoop_Town (tile=6031628) at /projects/OpenTTD/OpenTTD/src/town_cmd.cpp:524
#9  0x0000555555dcbb64 in RunTileLoop () at /projects/OpenTTD/OpenTTD/src/landscape.cpp:831
```

**Comment by TrueBrain** [comment]
The problem is that there is an airport on a 2x2 house.

This building:
![image](https://user-images.githubusercontent.com/1663690/105699094-1ebc5180-5f07-11eb-8cd9-609e63650c0d.png)

Is also here:
![image](https://user-images.githubusercontent.com/1663690/105699134-2c71d700-5f07-11eb-948f-a6164fadef7f.png)

(use Land Area Information in case you don't trust me :P)

So in a tile-loop, it walks all the tiles of the house to update the graphics, finds that there is an airport, not a house, on parts of the tile, which causes this crash.

**Comment by TrueBrain** [comment]
The good thing is, it is only that building that is an issue. I can fix the savegame, but as I am missing a single NewGRF, that is currently of little use to you (as there will be a world of other issues because of the missing NewGRF if I would be to save this).

I am really unsure how this situation happened, as it should be impossible for it to happen. Possibly this happened during changing / upgrading of NewGRFs, which happened a lot in this savegame (PS: what a massive savegame, holy crap :D).

1.10.3 won't crash on this, as the validation checks are disabled in those builds. Only in test-builds we have them enabled, causing this crash.

I am tempted to write this off as a one-off ... I will see if I can dig up the missing NewGRF and post a fixed savegame for you.

**Comment by TrueBrain** [comment]
Found the GRF. As promised, a fixed savegame:

[crash8606-fixed.zip](https://github.com/OpenTTD/OpenTTD/files/5866354/crash8606-fixed.zip)

I hope I did everything correctly .. I had the same AIs, same NewGRFs and everything. I demolished the building that was causing the crash. This set you back for ~2.8 million in your currency .. I hope you are okay with that ;) You should be able to load this savegame with 1.11.0-beta1 now, and continue where you left off.

I am going to close this issue now, as I believe the bug was caused by changing of NewGRFs, and that a building changes properties. Either way .. really hard to trace back. We will keep our eyes open if this happens for other people too.

Tnx for the report, and feel free to reach out if the attached savegame is not what you expected; it is always possible I forgot something silly and now the AIs won't load or something similar .. just let me know, and I will look at it :)

For now: enjoy OpenTTD! :)
