### ISSUE TITLE
Tram button is visible even if useless

### ISSUE THREAD

**Issue by Wuzzy2** [OpenTTD/OpenTTD#8621]
## Version of OpenTTD
1.11.0-dev

## Expected result
In default games, the "build tramway" button is hidden because it's useless (no trams). It is not even grayed out, it isn't there at all.

## Actual result
In default games, the "build tramway" button is always visible, but useless. This is annoying.

## Steps to reproduce
1. Start a default game
2. Look at the toolbar

**Comment by TrueBrain** [comment]
This is by design; it shows people trams are possible, but not available in this game.

The same holds for all other types: buttons are always there, and if you click them, you will see if there is anything you can build. For example, starting a game in year 0, still shows the Rail button, but the listing will all be greyed out.
