### ISSUE TITLE
Inconsistencies with "scoring year"

### ISSUE THREAD

**Issue by Wuzzy2** [OpenTTD/OpenTTD#8625]
## Version of OpenTTD
1.11.0-dev

## Background
There is a setting in which you can change the "scoring year", i.e. the year that, when it is over, triggers the rating of your company and showing of the highscore screen.

## Problems
However, the rating screens all assume the "rating year" is 2050.
The highscore table shows "companies that reached 2051", always. Also the "Daily News" newpaper always shows the date "December 31, 2050".

So if you set the scoring year to anything else than the default, the scoring and highscore table show incorrect dates.

**Comment by James103** [comment]
Likely related to https://github.com/OpenTTD/OpenTTD/pull/7747#issuecomment-536368868

**Comment by TrueBrain** [comment]
This is a long outstanding bug (as in, 10+ years old). Basically, the date is part of the graphics, not text. So fixing this means we have to fix the graphics in every baseset, including the original. Every baseset is free to put this on another position (and they do), making a solution to this infinite more complex.

I do not think this problem is worth fixing, and might as well be mentioned in `known-bugs.txt`. It is a lot of work for very very little gain. Once every blue moon someone mentions it, but those reports are years apart .. I am fine accepting this as a known-issue.

Any other devs with another opinion?

**Comment by LC-Zorg** [comment]
Not a dev, just only player, but...

The easiest way* would be to keep the graphic form and shorten the title to "Top companies"
The player will know how they got there. ;)

Of course, it would be more interesting to change the scoring method to make it more reliable and interesting. However, for the window would be good - perhaps in a completely different form - to contain saves as well as other information - perhaps it could be a reworked loading window.

**Comment by nielsmh** [comment]
Well you *could* make a way for a baseset GRF to supply a set of digit sprites for 0-9 and some coordinates for where to paste them onto the newspaper image to generate a custom one...

**Comment by Wuzzy2** [comment]
> This is a long outstanding bug (as in, 10+ years old).

No. This only became a bug "recently", when the "scoring year" beame configurable, which got into master at Dec 29, 2019. It was not a bug before that, because the "scoring year" was hardcoded.

Also, this is actually 2 bugs in one. First, it's the year inthe highscore list, which is NOT a graphic. So this is definitely fixable. Second is the newspaper date, which is more annoying indeed.

I think one way to fix the newspaper would be to just remove the date from the newspaper altogether, and "overdraw" it in the original graphic. That would at least remove the complexity of dealing with fonts.

**Comment by Wuzzy2** [comment]
If you wonder what to do with OpenGFX and/or existing NewGRFs: Don't do anything in OpenTTD. That's the trick! Just ask the graphics authors to remove the date from the image manually. No technical change needed at all. The only technical change would be an "overdraw" for the original graphic.

**Comment by TrueBrain** [comment]
> 
> No. This only became a bug "recently", when the "scoring year" beame configurable, which got into master at Dec 29, 2019. It was not a bug before that, because the "scoring year" was hardcoded.
>

You are correct. You used to be able to configure it, but people complained about the highscore too much, so it got removed :P Only to be reintroduced years later .. we have cycled with OpenTTD :D
But this is what I mean, long outstanding bug .. we have been trying to fix this for years now, just nobody ever has :D

> 
> Also, this is actually 2 bugs in one. First, it's the year inthe highscore list, which is NOT a graphic. So this is definitely fixable. Second is the newspaper date, which is more annoying indeed.
>

You are correct, we should be able to fix this one. Sorry, I blindly assumed you meant the newspaper .. people always complain about the newspaper :D

> 
> I think one way to fix the newspaper would be to just remove the date from the newspaper altogether, and "overdraw" it in the original graphic. That would at least remove the complexity of dealing with fonts.
> If you wonder what to do with OpenGFX and/or existing NewGRFs: Don't do anything in OpenTTD. That's the trick! Just ask the graphics authors to remove the date from the image manually. No technical change needed at all. The only technical change would be an "overdraw" for the original graphic.

"overdraw" would be a pretty big hack, but besides that: currently, different basesets have the date on different locations. So not only would we need to fix that the current date is on the image itself, but also we need a way for the location to be different. This is really a lot of work for such a small gimmick feature.
And we cannot just say: basesets have to fix it! As that is not how we roll .. we tend to care for our community, and those that contributed to it. So that doesn't really fly ;)
As always, we will accept Pull Requests for this, but I really doubt it is worth the effort, honestly. But again, my own opinion :D

**Comment by LordAro** [comment]
Close and document in known_issues.txt ?

**Comment by Wuzzy2** [comment]
Note at least a part of this issue is uncontroversial and could be fixed: The year in the highscore screen. This is a text, not baked-in into the image, unlike the big newspaper.

**Comment by Wuzzy2** [comment]
@LordAro: I don't think this is a proper bugfix.

Now the highscore table will show e.g. "Companies that reached year 2020” but it might not be true if the setting had a different value before. For example, if you finished in year 2051, get a highscore, and then changed the "ending" year tto 2020 afterwards, and look at the highscore list again, it will be wrong again, because that one company didn't finish at year 2020, but in 2051.

I suggest to change the title of the highscore list entirely, to just “Best companies” without any year.

> for a part of the game that fewer than 1% of players ever see.

I doubt this percentage.
