### ISSUE TITLE
Road and Tramway Catenary Drawn Incorrectly / Unsorted

### ISSUE THREAD

**Issue by supermop** [OpenTTD/OpenTTD#8647]
## Version of OpenTTD
1.10.3

## Expected result
"Rear" Catenary sprites are drawn behind other items, such as vehicles.

## Actual result
The rear sprites are drawn over any vehicle on the tile, leading to poles, etc. appearing over the vehicle.  As Road/tram catenary has no means of defining a bounding box size or position, there is no means the draw the sprites in the correct order. 

![pole](https://user-images.githubusercontent.com/65552890/107099603-1a821500-67e0-11eb-8a26-ff1eef935970.PNG)
![pole boxes](https://user-images.githubusercontent.com/65552890/107099607-1ce46f00-67e0-11eb-9e1c-cdf235a5141f.PNG)

Providing for bounding boxes, or forcing the "rear" sprite to always be under all others would fix this.

## Steps to reproduce

1. Build a default tramway, or use an NRT NewGRF to build a road or tramway that has overhead catenary. 
2. Run any road vehicle along the far lane of the road. 
3. When the vehicle passes in front of part of the catenary (pole etc), the catenary sprite is visible over the vehicle sprite.

**Comment by supermop** [comment]
Maybe it would be most expedient to just ignore bounding boxes and force all catenary_back sprites to be drawn under any vehicles?

**Comment by TrueBrain** [comment]
As a reminder to who-ever picks this up: some GRFs, like `CZTR TRAM SET` draw the catenary from both sides.

**Comment by TrueBrain** [comment]
I gave it a spin to fix, as can been seen by the above PR, but .. I found out that there are some .. special choices made for trams :) Basically, some sprites in OpenGFX have pylons on both sides of the track. In general, for isometric games, if you have a single sprite that has to go both over and under another sprite, there is no correct way of sorting that. Unless OpenTTD has tricks up its sleeve to deal with these situations (my knowledge about this is severely lacking, so I hope someone else can fill in that gap), there is no answer to this problem.

So I am afraid you will have to deal with this problem a bit longer ... sorry :(

Edit: okay, gathered more information. Turns out the idea is that the back sprite draws the pylons, but the front sprite does this again for the pylons in the front. This is currently not done in OpenGFX, which was confusing me. It is fine that the back sprite has the pylon too, of course, but the front sprite should at least have it. Otherwise it is indeed an impossible situation for sorting .. but if the idea is that both have them, nothing is wrong here. It is just that OpenGFX got it wrong.
The `tramtracks.png` in our source tree does seem to get it right, so there is that.
