### ISSUE TITLE
Wrong distance between signals with «Drag signal distance» 

### ISSUE THREAD

**Issue by Rau117** [OpenTTD/OpenTTD#8797]
## Version of OpenTTD
Any with drag signal option

## Expected result
Signal every N or N-0.5 tile
Tested by drag signal distance = 1, 2 and 3, but works for any
Expected gaps marked with green and yellow rails
![1 manual](https://user-images.githubusercontent.com/47086324/109619159-7de63500-7b49-11eb-9350-e81302c3a04f.png)
![2 manual](https://user-images.githubusercontent.com/47086324/109619164-80488f00-7b49-11eb-809d-d618825f8ee1.png)
![3 manual](https://user-images.githubusercontent.com/47086324/109619172-82125280-7b49-11eb-81c4-162cb0f73b79.png)

## Actual result
Signal each N tile on straight track and each N+0.5 if gap contains diagonal tiles
Red tracks – gap over expections.
![1 auto](https://user-images.githubusercontent.com/47086324/109619440-d4537380-7b49-11eb-9e31-7d217cdf4fde.png)
![2 auto](https://user-images.githubusercontent.com/47086324/109619502-e7664380-7b49-11eb-9487-4e3943e414a8.png)
![3 auto](https://user-images.githubusercontent.com/47086324/109732635-96e4f980-7bce-11eb-9420-ae7899dff7bd.png)

## Steps to reproduce
Build some random connected tracks without juctions, get signals menu, change «Drag signal distance» in signals menu (let it be N) and build signals with ctrl+drag. Then count pieces of tracks between each signal. Straight piece of track = 1, diagonal (track on corner of tile) = 0.5. You must get N-1 on straight tracks and N-0.5 if gap contains diagonal pieces.

For common players it's not a problem, but when network contains a lot of trains with tight flow (openttdcoop style) any unexpected gap can be bottleneck of all network. For now the only solution is manually build every signal on diagonal track.
_Multicolored tracks is PURR NewGRF, it has absolutely no effect on the placement of signals_

**Comment by ldpl** [comment]
I'll try to paraphrase the issue as I understand it. 

Because of how signals are placed in OpenTTD it's not always possible to keep a consistent signal gap where straight tracks connect with diagonal ones. So what signal placer does is making gap half a tile larger when turning from straight to diagonal and half a tile smaller when turning back. And while shortening the gap is usually not an issue, suddenly enlarging the gap is as it stops trains that were happily following others before it. 
![Screenshot from 2021-03-02 13-47-40](https://user-images.githubusercontent.com/413570/109637525-f3f49700-7b5d-11eb-8369-bd36d01f501b.png)

So a fix, in this case, would be to make the signal placement tool shorten the gap in all cases where it couldn't keep the gap consistent.

BTW. It even enlarges the gap needlessly sometimes:
![Screenshot from 2021-03-02 13-59-59](https://user-images.githubusercontent.com/413570/109639067-cad50600-7b5f-11eb-9920-167410fafe3a.png)

**UPD** It seems that another part of this issue is that the straight track piece has a logical length of 192 units while the diagonal one 128 (256 for two halves). And signal placer uses the visual gap instead of the logical one.

**Comment by Rau117** [comment]
It is possible to fix this by using the «pieces of track» instead of visual (idk) or logical (192 and 128… steps per track) and rename this setting to something like «Tiles/space/distance/gap between signals» plus decrease the displayed value by 1. Thus, the gap should be considered as a normal straight piece = 1, diagonal = 0.5 and if there is no way to make the gap = 1, make it = 0.5 (like the yellow tracks at expected images).

It is also not possible to fit even a 0.5 tile train in the expected 1 (actually 0) "drag signal distance".
![изображение](https://user-images.githubusercontent.com/47086324/109733542-55554e00-7bd0-11eb-8a1a-ab1a75ce94dc.png)

This seems to be a misunderstanding in naming, which is even worse in other languages. Like «Draging signal distance = 1», but what is the unit of measure and how it counts?

**Comment by LC-Zorg** [comment]
In the case of signals every 1, it won't look good. :/
It would be necessary to move the signals that stand on the inside of the field towards its center in order to keep equal distances. This, in turn, might not look great with some NewGRFs adding other signaling.

I would see a solution for maintaining traffic flow other than not the best looking compaction of signals.
A train entering the section at the end of which there is a red light of a block or pre-signal, would immediately start braking, which would be gentler and spread over the entire section. As a result, on the one hand braking would look much more natural, and on the other hand, slowing down instead of suddenly stopping the train would make the traffic smoother.
