### ISSUE TITLE
Console command "exec" can stack overflow and crash (bypassing crash handler)

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#8851]
## Version of OpenTTD
openttd-20210226-master-gaf326753a9-windows-win64

## Expected result
Console command `exec` should have a recursion limit when it recursively calls itself, similar to in #7969.

## Actual result
In `openttd-20210226-master-gaf326753a9-windows-win64`:
The game crashes, presumably due to a stack overflow and/or too many file handles open. `crash.dmp` is generated with a file size of 0 bytes. `crash.log` and `crash.png` are not generated.

In `openttd-jgrpp-0.40.3-windows-win64`:
The console command aborts with `ERROR: script file not found` even though the file exists and was able to be accessed recursively using `exec`. This may be because there were too many files open by the same process at once.

## Steps to reproduce
1. Create a file with the path `C:\Users\user\Documents\OpenTTD\recursion.txt` and the contents as follows:
```
exec C:\Users\user\Documents\OpenTTD\recursion.txt
```
(replace `user` with your Windows user name)

2. Launch OpenTTD.
3. Run the console command: `exec C:\Users\user\Documents\OpenTTD\recursion.txt`
4. Either crash or abort with `ERROR: script file not found`.

**Comment by TrueBrain** [comment]
Besides no protection for recursion, there is another issue when you run `exec` from a script: when ever the inner script stops, so does the outer script. Example:

`test.script`
```
echo begin
exec test2.script
echo end
```

`test2.script`
```
echo test2
```

Run a dedicated server and execute: `exec test.script`. Output:

```
begin
test2
```

This is because there is only a single global to indicate a script is still being parsed. So one can only use `exec` to hand off from one script to the other.

I am surprised nobody ever reported that issue, as it is a pretty big limitation. But maybe that says a lot about how many people use `exec` and scripts in general.
