### ISSUE TITLE
Stadiums don't occupy 4 tiles

### ISSUE THREAD

**Issue by wouternolten** [OpenTTD/OpenTTD#8854]
## Description
There are two bugs which probably are part of the same issue:
1.  Stadiums should occupy 4 tiles. In a past game, I've seen a lot of stadiums which occupy 1,2 or 3 tiles (see screenshots). Unfortunately I haven't seen if these stadiums are created like this, or if the city itself tries to remove a square. 
2. A player can remove one tile, and only that tile of the stadium gets removed. When someone tries to remove 1 tile of a stadium, the whole stadium should be removed. 

It looks like it's only in this scenario [Netherlands_Custom.zip](https://github.com/OpenTTD/OpenTTD/files/6133501/Netherlands_Custom.zip)

## Screenshots:
![image](https://user-images.githubusercontent.com/6116775/111006021-47e85280-838c-11eb-8226-da5e216e791c.png)
![image](https://user-images.githubusercontent.com/6116775/111006059-56cf0500-838c-11eb-898a-2577194930e6.png)
![image](https://user-images.githubusercontent.com/6116775/111006256-c47b3100-838c-11eb-81b2-18cf648ef3dd.png)

## Version of OpenTTD
1.11.0-beta2. Haven't noticed it before this version, so it's possible that the bug was introduced in this beta.

## Expected result
- Stadium uses 4 tiles
- Deleting one tile should remove the entire stadium

## Actual result
- Stadium uses 3 tiles. 
- Only one tile gets deleted

## Steps to reproduce
- Open scenario 
- Try to remove one tile of a stadium

**Comment by TrueBrain** [comment]
I looked into your scenario, and found a few things:

With 1.11.0-beta1 recently this scenario was changed to also include `Town and Industry - UK Houses`. When you change NewGRFs of an existing savegame / scenario, a warning is presented to you that there could be some weird effects because of this action. And this is exactly what happened here.

This GRF takes over some internals of housing, one of which meaning that stadiums are no longer considered a 2x2. This normally is not a problem at all, as if you generate a new game with the GRF loaded, no stadiums are ever placed. This only happens if you add this GRF with an already existing game. This could very well be a bug in the GRF btw, I did not investigate that further.

Sadly, changing NewGRF in an existing savegame is not a scenario we support, as there are a gazillion things that can go wrong (and also the reason we show this error message):
![image](https://user-images.githubusercontent.com/1663690/111025664-e5bc3b80-83e5-11eb-8e3e-6e3063ce647a.png)
So there is little I can do for you here.

One of the things you could do, is either remove the GRF again (and hope it didn't place new houses with it), revert back to the scenario as it was before the NewGRF got added (so the version before 1.11.0-beta1), or see if you can contact the author of the NewGRF and figure something out. This of course gives no guarantee one of the other added NewGRFs will cause issues.

This in the assumption you were working on this scenario yourself; otherwise you could ask the author of the scenario to look into this, of course.

Sorry for the bad news; but this is sadly enough exactly why we advise against changing NewGRFs for running games. I fully understand that for Scenarios this can be very annoying, but because of the way NewGRFs interact with the game, not something we can prevent from happening (when NewGRFs are changed for an existing game; we do prevent a lot of problems when creating a new game with issues NewGRFs might generate).

----

Technical details:

Loading this save gives these two warnings:
```
[2021-03-13 10:21:17] dbg: [grf] FinaliseHouseArray: tai_uk_houses-gamma1/tai_uk.grf defines house 36 with different house size then it's substitute type. Disabling house.
[2021-03-13 10:21:17] dbg: [grf] FinaliseHouseArray: tai_uk_houses-gamma1/tai_uk.grf defines house 37 with different house size then it's substitute type. Disabling house.
```

Gamelog shows this change:
```
[2021-03-13 10:26:04] dbg: [gamelog] Revision text changed to 1.11.0-beta1, savegame version 289, not modified, _openttd_newgrf_version = 0x1b086d64
[2021-03-13 10:26:04] dbg: [gamelog] Tick 1280: GRF config changed
(..)
[2021-03-13 10:26:04] dbg: [gamelog] Added NewGRF: GRF ID 44442411, checksum (..), filename: tai_uk_houses-gamma1/tai_uk.grf (md5sum matches)
(..)
```

Removing the GRF makes Stadiums a 2x2 again.

**Comment by wouternolten** [comment]
Wow, thanks so much for this answer, very clear. Now I know to be a little more careful with the message.
