### ISSUE TITLE
Can't find bus timetables

### ISSUE THREAD

**Issue by Frontrider** [OpenTTD/OpenTTD#8927]
## Version of OpenTTD
1.1.0
## Expected result
From a reddit thread I got called out for calling the ui bad (I'm not the only one). So I'll start reporting ui issues (issues that prevent me from actually playing the game so it is from an extremely surface level perspective). I see that it's c/c++, that I won't touch.

Now the actual suggestion to make the game more usable:
A timetable button on the road vehicle's window would make it streamlined, because I still can not see where it is, and the window of the vehicle is a good entry point for that.
![image](https://user-images.githubusercontent.com/6755034/113344799-d881d500-9331-11eb-843f-450f232f64cc.png)

**Comment by LordAro** [comment]
Are you looking for orders, or the timetable window?

Orders are the arrow icon on the right side of the vehicle window - hover the mouse over things! Almost everything has tooltips explaining what they are and extra hidden features you might not find otherwise!

Timetables can be found from the orders window, in the top-right of the window. Alternatively, ctrl+click the orders icon.
(Timetables are an advanced feature that are very... awkward in their current form, so making them even more prominent (right now) is probably not all that desirable)

As this isn't a bug report as such, I'm going to close it, further questions are welcome on the [forum](https://www.tt-forums.net/viewforum.php?f=55)
