### ISSUE TITLE
Object selection window button doesn't appear lowered after clicking on it

### ISSUE THREAD

**Issue by perezdidac** [OpenTTD/OpenTTD#8939]
## Version of OpenTTD

1.11, but 1.10 as well and probably before that.

## Expected result

The select object window button stays lowered until the object selection window is closed.

## Actual result

The select object window button immediately raises after clicking on it.

## Steps to reproduce

1. Start a game with NewGRFs that include objects (i.e. Fridaemon objects)
2. Open the terraform/landscape toolbar
3. Click in the Object selection window (transmitter icon)
4. Observe actual result and not expected result

## Notes

I've done some work to trying to fix it but still not completely fixed.

**Comment by nielsmh** [comment]
Can't reproduce, the Select Object button raises after click for me in 1.11.0.

**Comment by perezdidac** [comment]
> Can't reproduce, the Select Object button raises after click for me in 1.11.0.

That is the problem, I expect it to stay lowered just like the rail station button for instance.

**Comment by 2TallTyler** [comment]
I think this is intended behavior. The rail toolbar only allows one tool to be open at a time, so if you have the station tool open (with its button lowered) and then open the depot tool, the station tool closes and its button raises.

In the terraform toolbar (which includes the object button), clicking the Trees or Objects buttons causes that tool window to open. But those windows are not exclusive: other windows can be open at the same time. For this reason, it wouldn't make sense to keep either of these buttons lowered when that tool is open.

In my mind, this is an intentional behavior and not a bug nor an inconsistency.
