### ISSUE TITLE
Unable to abandon/quit

### ISSUE THREAD

**Issue by wlfbck** [OpenTTD/OpenTTD#8949]
I know this must sound like a joke, but i'm simply unable to abandon the game or quit. See the screenshot, the tooltip for the floppy symbol says "save game, abandon game, quit". Only saving is possible. And i don't see any other way to exit the game from here. Obviously i can alt+f4 out, but that can't be the intended way right? Especially since i just want to go back to the main menu.

![grafik](https://user-images.githubusercontent.com/1621804/113523347-a8436c00-95a7-11eb-8a60-304337f43518.png)

## Version of OpenTTD
Latest (1.11.0)
## Expected result
Being able to quit.
## Actual result
Not being able to quit.
## Steps to reproduce

1. Start a new game.
2. Click floppy symbol
3. No way to quit appears, just save.

**Comment by nielsmh** [comment]
You need to click and hold the mouse, and drag down to the Abandon or Quit, then release the mouse button.

**Comment by wlfbck** [comment]
Oh wow, okay. Thanks. I guess that makes sense for touchscreen, but maybe add a toggle to the options which is off by default on platforms which are not android/ios? Or have it popup on hover under those OS?

edit: To clarify, i didn't even see the popup menu which is shown on hold, since it is visible for such a short amount of time on a normal click.

**Comment by nielsmh** [comment]
The interface is actually designed for mouse use, but it isn't very modern, true. But just changing it to require two clicks to select any items from a drop-down menu will also make the interface worse, since several of the main toolbar buttons depend on having a single-click "smart" choice. Especially the Build Rail and Build Road buttons let you choose between different rail and road types (when they are available), but a click on just the button will select the last used type. Similarly, you typically save your game between 3 and 10 times more often than you leave it, so it makes sense to have it on a single click action. But there might be other ways to make it more discoverable for new players without forcing old players to break their habits.

**Comment by wlfbck** [comment]
Makes sense. Maybe something like an info popup on the very first launch of the game?

**Comment by LC-Zorg** [comment]
I've been playing a bit online lately, and indeed the problem recurred quite a bit.
Currently it is not a problem, but I didn't like this "press, hold and select" solution for quite a long time. It is not popular solution, and therefore it is also not intuitive. OTTD is probably the only game/program I know of with such a solution. In fact, wherever there are additional options hidden under an icon or button, pressing it opens a new window or list. So for some new players it can be troublesome.

Perhaps the solution could be to add an option to speed dial a feature. When turned on, the game would behave as it does today. When disabled, pressing the icon would open the list and require an additional click - it would work just like selecting the order. Except, pressing anywhere else would close the list.

Another option would be to change the concept where pressing an icon would always open a list or an additional icon bar.
![Icon bar instead of list](https://user-images.githubusercontent.com/67662046/113633458-4b11ee00-966d-11eb-881f-c2adb320156b.png)

I think that something like this would be even more convenient than the current solution.

**Comment by LordAro** [comment]
Working as intended
