### ISSUE TITLE
There is no way to toggle play/stop music in the title screen

### ISSUE THREAD

**Issue by telk5093** [OpenTTD/OpenTTD#9059]
## Version of OpenTTD
1.11.1

## Description
If you stopped background music inside the game, there is no way to play it again in the title screen (first screen that the game is run)
I know that the volume gauge has been implemented in the game option window recently.
I have thought that it would be better there were simple control buttons in the game option window like this:
![image](https://user-images.githubusercontent.com/10726524/115190423-f2d5f400-a122-11eb-828c-ce288a5f9c82.png)

## Expected result
N/A, maybe there were a button to toggle play/stop background music

## Actual result
There is no way to play again in the title screen. User must start new/loaded game to play BGM again.

## Steps to reproduce
1. Stop playing background music
    ![image](https://user-images.githubusercontent.com/10726524/115190045-67f4f980-a122-11eb-8b86-22f8831ba010.png)
2. Abandon the game and go out to the title screen.
    ![image](https://user-images.githubusercontent.com/10726524/115190601-3fb9ca80-a123-11eb-8843-b8246ee46644.png)
3. There is no way to play again, even at the Game option window.

**Comment by nielsmh** [comment]
I remember it as I had wanted music to always play on the title screen, regardless of whether it was stopped in-game or not, but there were arguments that the player had stopped music because they didn't want music, so it should stay stopped.

Best idea I can think of without cluttering the interface with even more buttons would be to just always start the music playback when a music set is selected (and it has a title tune).
