### ISSUE TITLE
I never get the new trains after 1980- but i get all plains, boats and cars

### ISSUE THREAD

**Issue by fearlezz77** [OpenTTD/OpenTTD#9237]
## Version of OpenTTD
1.11.2

## Expected result
to be able to buy new trains, but they aren not on the veiclelist

## Actual result
when i get to 2020 i have only one trainset to buy, who brakes down all the time

## Steps to reproduce
have NO idea

**Comment by auge8472** [comment]
I assume, that the newer rail vehicles are electric locomotives and your depots are unelectrified. That way the new locos will not show up in the buy menu.

You can check the situation by opening the companies train-list-window and clicking the button "available trains". There the newer locos should be shown there because *this* list contains the vehicles of all track types whereas the list in a depots buy menu is restricted to the matching track type.

If my assumption is right, all you have to do is electrifiyng your depots and rail network(s). Click and hold the "build railway track" button and you will encounter the track-type-list. When you opened the build menu of the matching track type you have access to the convert tool (far most right button of the build menu). With this function you can convert the rail type tile by tile or in an rectangle (click, hold and pull).

**edit:** The same situation will occur, when the new tracktypes monorail and maglev will be introduced.

**Comment by TrueBrain** [comment]
@fearlezz77 : did the above help you out? Would love to get your feedback on this :) Tnx!

**Comment by LordAro** [comment]
A common issue with new players, but assumed working as intended
