### ISSUE TITLE
Change "unload" to default to "unload and leave empty"

### ISSUE THREAD

**Issue by HelmiMUC** [OpenTTD/OpenTTD#9265]
## Version of OpenTTD

OpenTTD version 1.11.2
Windows 10 20H2 (19042.985)

## Expected result

in the vehicle order list when i press the button "unload all" i expect "unload all and leave empty" for the highlighted order

## Actual result

i press the button "unload all" and the text on the highlighted order means (unload and load)

## Steps to reproduce

mark an order
press the button "unload all"
now the text behind the highlighted order means "unload and load".

To "unload and leavy empy":
mark an order
press the button "transfer"
then press the button "unload all"
now the text behind the highlighted order means "unload and leave empty"

**Comment by FLHerne** [comment]
This isn't a bug, orders have always worked this way.

There's no reason "unload" should imply "no loading" -- the unloaded passengers will in most cases be accepted by the station and not stay to be reloaded. The reason "Transfer" sets "no loading" by default is that the transferred passengers remain on the station and would be reloaded otherwise, which would be confusing and unintended in most cases.

Another way to set "Unload and leave empty" is to press "unload all" and then select "no loading" in the list of loading options. This is rarely actually needed, but might avoid surprises in case a new industry opens or so.

**Comment by embeddedt** [comment]
@HelmiMUC If you would prefer it to work the way you described, you would need to apply [this patch](https://www.tt-forums.net/viewtopic.php?t=59611) to your copy of OpenTTD. [Here](https://github.com/embeddedt/OpenTTD-modded/commit/5ae8a44b588fec6e0e7b3c86b1cc7422f0ca3bab) is the line to change in more modern OpenTTD versions.

**Comment by Andrew350** [comment]
> There's no reason "unload" should imply "no loading"

Is there ever a situation where setting explicit "unload" orders makes any sense without also setting "leave empty" (or at least some other flag)? Does anyone actually set "Unload and take cargo" orders in a useful way?

Maybe I'm just missing a usecase here, but I've never found the current default useful. The only time it makes any sense is at something like a passenger station where you want to deliver and pick up the same type of cargo, but that's already the default behavior without setting that flag. "Unload and take cargo" seems to me to be completely redundant, whereas "unload and leave empty" is actually useful in preventing cargo from being loaded onto the vehicle when it isn't wanted.

I can kind of imagine that "unload and take cargo" exists to make (new) people feel good about setting such behavior explicitly, but it seems unnecessary to be the default unload setting considering it doesn't seem to do anything different than simply setting no extra conditions at all.

**Comment by TrueBrain** [comment]
Personally, I agree, and I fall for this every time I play the game. I click "unload", and I see the train going back and forth loaded all the time .. turns out in range of the "unload" station was also an industry that could generate what-ever I was unloading .. so it is now happily loading it .. going nowhere.

I too fail to understand in what scenario you would want "unload & take cargo". To me it feels like if anyone would want that, it for sure is the exception, not the rule.

Personally, I consider the "Full Load" and "Unload" button as buttons to say: take cargo from this station ... and bring it to that station. So basically setting up a one-way cargo stream. For passengers I do not set either, as I want it two-way (which is the default). Currently, "Full Load" does the part of the leg as I expect .. but "Unload" doesn't.

So yeah, I vote we change the default to be "Unload & leave empty".
