### ISSUE TITLE
[Bug]: desync after joining server

### ISSUE THREAD

**Issue by ecolortest** [OpenTTD/OpenTTD#9458]
### Version of OpenTTD

1.11.2, macos 10.13.6

### Expected result

should not desync after joining server

### Actual result

get desync from server after 30 second joining the server

### Steps to reproduce

1. join reddit.com/r/OpenTTD 1 - Vanilla
2. after joining, 30 seconds later then desync

**Comment by James103** [comment]
I joined the server you mentioned, waited for a couple minutes, and did not desync in the meantime. The server has probably reset to a new game", making this issue invalid (expired / out of date).

"Reddit servers reset approximately every 22 hours if running with default 1950-2050 games at 1x time speed.

**Comment by ecolortest** [comment]
> I joined the server you mentioned, waited for a couple minutes, and did not desync in the meantime. The server has probably reset to a new game", making this issue invalid (expired / out of date).
> 
> "Reddit servers reset approximately every 22 hours if running with default 1950-2050 games at 1x time speed.

its was desync, not an world reset

**Comment by James103** [comment]
As of the time of writing, the server `reddit.com/r/OpenTTD 1 - Vanilla` has [permanently closed](https://www.reddit.com/r/openttd/comments/orze4l/all_good_things_and_their_endings/), making this issue invalid unless it can be reproduced on a different server.

**Comment by TrueBrain** [comment]
Sadly, without a savegame, this is really difficult for us to debug. Let alone confirm the problem is fixed :)

If this happens in the future, we would greatly appreciate a savegame (the game makes a `netsave` emergency save on desync), so at least we have something to work with. Ideally, we also have the savegame from the server, but that might be harder to obtain :)

In short, I really do appreciate you bringing this to our attention, but as it is, this is not actionable :( Sorry .. but in positive news, recently we did find a desync bug with MacOS clients .. hopefully that was causing this issue too :)
