### ISSUE TITLE
[Crash]: Game crashed out of nowhere

### ISSUE THREAD

**Issue by Jeems4727** [OpenTTD/OpenTTD#9459]
### Version of OpenTTD

1.11.2

### Steps to reproduce

1. I was just looking around and seeing if I could put an airport serving a town somewhere or a cargo line.
2. The game gave me a error message that said something like "Not enough memory"? idk i have a bad attention span although this happened like minutes ago.
3. Then the game crashed and gave me the game failure message
4. it was made in 1950 and was 1024 by 1024

also it wouldnt let me send the crash.dmp file

### Upload crash files

[crash.log.zip](https://github.com/OpenTTD/OpenTTD/files/6910290/crash.log.zip)
[crash.sav.zip](https://github.com/OpenTTD/OpenTTD/files/6910295/crash.sav.zip)

**Comment by LordAro** [comment]
>The game gave me a error message that said something like "Not enough memory"

That's exactly what happened - your system completely ran out of memory and so OTTD was unable to continue (and crashed)

**Comment by Jeems4727** [comment]
> > The game gave me a error message that said something like "Not enough memory"
> 
> That's exactly what happened - your system completely ran out of memory and so OTTD was unable to continue (and crashed)

thanks i was really confused about what happend at the time.

**Comment by James103** [comment]
How much RAM do you have on your computer?

**Comment by Jeems4727** [comment]
My laptop has 4GB of ram with around 1.5gb available. OpenTTD can run fine
though. I guess at the time I just had too many chrome tabs open

**Comment by TrueBrain** [comment]
Given the error, it is most likely indeed that your system ran out of memory. Chrome does tend to do that :P

There is not much we can do here, sadly enough. A system out of memory presents a real challenge to every game .. best we can do we did: tell you your system is out of memory and .. hope for the best :D

I hope you didn't lose much progress because of this. But for now, I am going to close this ticket. If it happens again while you are sure the system was not out of memory, to let us know!
