### ISSUE TITLE
[Crash]: Assertion failed on "Fund new industry" when no industries exist

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#9546]
### Version of OpenTTD

12.0 beta 2 Windows 10

### Steps to reproduce

1. Install and activate the [feature disabler NewGRF](https://bananas.openttd.org/package/newgrf/47572121), making sure that the parameters are set to remove all industries.
2. Start a new game.
3. Click on industry button > "Fund new industries"
4. The game asserts here:
https://github.com/OpenTTD/OpenTTD/blob/7469f00c5b8d0dc5cc2034eb9dc91c6e8721ac03/src/industry_cmd.cpp#L121-L125

### Upload crash files

[crash.zip](https://github.com/OpenTTD/OpenTTD/files/7136473/crash.zip)

**Comment by nielsmh** [comment]
Starting a game without any industry types available is odd, but I suppose it's a valid game possibility, at least as long as there are some town buildings available that accept and produce some cargo. There can also be situations where all industries are not buildable right now because of year restrictions. So the industries handling should handle the situation where there are no industry types available and no industries on the map, and the situation where there are no industry types available but the map does contain some industries.
