### ISSUE TITLE
[Bug]: refresh rate doesn't work with vsync

### ISSUE THREAD

**Issue by YouYouTheBoxx** [OpenTTD/OpenTTD#9614]
### Version of OpenTTD

OpenTTD 12.0

### Expected result

Fps have to lock to the choosen refresh rate.

### Actual result

Fps are locked to 60Fps when using VSync either using a bigger refresh rate than 60 or a lower refresh rate too.

### Steps to reproduce

Nothing special. Just make turn VSync ON and set a refresh rate upper than 60Hz or less than 60Hz too.

**Comment by TrueBrain** [comment]
Vsync locks the refresh-rate to the display (as that is what vsync means: go in sync with my display). So I do not think the bug is that the FPS doesn't change when vsync is on and you change the refresh-rate. I think the bug is you can change the refresh-rate when vsync is on. That shouldn't happen, I guess.

Something to investigate further, also in what is possible and not :)
