### ISSUE TITLE
[Bug]: In English (AU) language, "Show tooltips" setting says the unit of time is seconds when it should be miliseconds

### ISSUE THREAD

**Issue by VisibleReality** [OpenTTD/OpenTTD#9657]
### Version of OpenTTD

1.12.0

### Expected result

![image](https://user-images.githubusercontent.com/37581230/138810512-44b77a59-69a5-4ae3-b090-5cdae31cdebc.png)
The setting shows the correct unit of milliseconds in English (UK) 

### Actual result

![image](https://user-images.githubusercontent.com/37581230/138810317-9544dbc7-e97d-4d7b-9ae9-b1834c6f9d9e.png)
Setting claims the delay is in seconds in English (AU)

### Steps to reproduce

1. Select English (AU) as your language in Game Options
2. Go to Settings > Interface > General
3. The setting "Show tooltips" will have the wrong unit.

**Comment by James103** [comment]
This can be fixed in the translation itself.
1. Request access to translate English (AU): https://github.com/OpenTTD/team/issues/new?assignees=&labels=request_access&template=translator_en_AU.md&title=%5Ben_AU%5D+Translator+access+request
2. Once the request is approved, follow the directions to access eints.
3. Use eints to make the following change:
```diff
- STR_CONFIG_SETTING_HOVER_DELAY_VALUE                            :Hover for {COMMA} second{P 0 "" s}
+ STR_CONFIG_SETTING_HOVER_DELAY_VALUE                            :Hover for {COMMA} millisecond{P 0 "" s}
```

**Comment by LordAro** [comment]
Fixed via translator. Will be in next nightly/translator commit
