### ISSUE TITLE
[Bug]: Long server name sometimes forces Online Players window to be very wide

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#9697]
### Version of OpenTTD

12.0 / 12.1 Win10

### Expected result

You can significantly reduce the width of the window. Saving window size works.

### Actual result

The width of the window varies almost each time the game is started and gives the impression of being random. Very often this width is senselessly large and cannot be reduced. Sometimes changing the language unlocks the possibility of reducing the width. Saving the window size doesn't work.

The minimum width of the window after entering the server
![Senselessly big window](https://user-images.githubusercontent.com/67662046/141700150-26570fd1-71df-4b66-8e18-4b9b25a8cb3e.png)

The minimum width of the window after closing the game and re-entering the server
![Narrower window after changing the language](https://user-images.githubusercontent.com/67662046/141700157-3b01e6df-7017-4245-a719-0ef5081bd689.png)

This method doesn't always work.

### Steps to reproduce

The situation is repetitive, but I don't see the key. The problem seems to arise after trying to save the window size.

**Comment by James103** [comment]
This may be caused by the length of the server name being a limiting factor in the width of the online players window. Some servers put extra info in the server name, which inflates the length of said server name.

To confirm this, will you please try the following?
1. Start and/or join a server with a very long name.
2. Attempt to reproduce the bug to show that the long name increases the minimum width of the window.
3. Start and/or join a server with a very short name.
4. Attempt to reproduce the bug to show that the short name is not as much of a factor in determining the minimum width of the window.

**Comment by LC-Zorg** [comment]
As you can see above, these two screenshots are from the same server, which actually has a long name. And as you can see, this doesn't the reason to prevent the window from reducing the width.
