### ISSUE TITLE
[Bug]: It is not possible to transfer vehicles sharing orders between groups (using Ctrl+drag doesn't work)

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#9702]
### Version of OpenTTD

since 12.0, Win10

### Expected result

You can use Ctrl+  drag to move groups of vehicles sharing orders between groups - as it was in 1.11.2 and earlier.

### Actual result

Using Ctrl+ has no effect and it is not possible to move whole groups of vehicles between created groups in the vehicle list window.
To put 200 vehicles into the newly created group, you must move each vehicle separately.

### Steps to reproduce

1. Create a simple but long road connection between the two cities
2. Buy dozens of vehicles to handle this connection
3. Create a group in the vehicle list
4. Try to put these several dozen vehicles in a new group

**Comment by Rau117** [comment]
_Another great unlisted change…_
Now you must hold down left mouse button on a vehicle, then drag it to the group, hold down the CTRL, and release the mouse button. Works, but inconvenient.

**Comment by LC-Zorg** [comment]
Seriously?! This is nonsense. Is it an accident at work or a deliberate act?

**Comment by Rau117** [comment]
Well, they deliberately removed «signal by default» setting without discussion and ignore any question about it… 

Here the situation seems to be similar - everything works as intended.

Now ctrl + click on the transport opens… a very seful menu - the tasks of this vehicle. 

And in order to somehow avoid bugs (which will need to be fixed), they simply removed the ability to hold down the CTRL and make several groups.

But this is just a guess. Remove one, but add another ... It’s like an _effective manager_ or _marketer_ has appeared in the OpenTTD team.

**Comment by LordAro** [comment]
No, this is a bug

**Comment by 2TallTyler** [comment]
When I try it, holding Ctrl before I click on a vehicle does nothing and the vehicle won't drag. If I click and drag, then hold Ctrl and release over the new group, it moves properly.

**Comment by LordAro** [comment]
Change was made in #9325
You are indeed able to drag vehicles sharing orders into a single group while holding ctrl if you press ctrl after you start dragging

https://github.com/OpenTTD/OpenTTD/blob/fc58ed9987a24785213a24c8c5d27f3b39c156ae/src/group_gui.cpp#L748-L762

However, the behaviour of having to press ctrl *after* starting dragging is a bit confusing, I wonder if we might be able to improve that... @btzy , any thoughts?

**Comment by frosch123** [comment]
The different behavior of ctrl+click depending on "group by" is weird to me.
How about something like
* Ctrl+Singleclick: Select group + start dragging
* Ctrl+Doubleclick: Show order window (independent of "group by")

On the other hand, ctrl+drag only makes sense if "group by" is set to "none". So it could also depend on the "group by" option:
* "none": Ctrl+click starts dragging.
* "shared orders": Ctrl+click shows orders.

**Comment by LC-Zorg** [comment]
Yes, I've already found it. This feature is definitely not supposed to work that way. Not only does it break players habits, but the new method is not consistent with anything else in the game. Wherever Ctrl + is used, the player presses Ctrl first and never the other way around. Changing this behavior in every other situation is not at all intuitive. Once this way, sometimes this way. No... I don't mean to be rude, sorry, but I have a very bad opinion about it.

I can see three methods to fix this:
**1. Restore known behavior when grouping is disabled.** For most players, everything will be the old way and just like everywhere else. When someone uses grouping by orders, then Ctrl + click will open the orders window as intended by that PR, and using Click + Ctrl will allow you to move a group of vehicles. For me that would be okay, but for others it can still be confusing.
**2. Undo the change and instead add an icon that would open the orders window**
![Orders in vehicle list window](https://user-images.githubusercontent.com/67662046/142084937-77f8d8c9-8e6e-4af4-9547-199de15b914e.png)

It can be done in such a way that this window shows some of the orders (first > second > maybe third), so that in many situations you will not even have to open the orders window.

**3. Removing this change and forgetting about the problem** - rather weak as the function is generally not bad.

>Ctrl+Doubleclick: 

I don't like double click ;) But maybe it won't be bad here. Certainly better than now.

**Comment by btzy** [comment]
I agree that this is a bug.  However, it seems that before this change, users still need to be holding down Ctrl when *releasing* the mouse button - it's just that previously, the Ctrl key did nothing special when depressing the mouse button (except scrolling the UI to the current vehicle's group), so the same dragging mode starts whether or not the Ctrl key was already pressed when the mouse button is depressed.  Arguably, the original behaviour was also awkward since it requires Ctrl to be pressed when releasing the mouse button, but not when depressing the mouse button.

I think the simplest fix for now is to implement @frosch123's second suggestion - to restore the old behaviour when not grouping by shared orders.  It should just be switching the order of the if statements around those few lines of code.  I don't quite like double clicks either - such functionality is generally non-discoverable via normal gameplay, and this steepens the learning curve.

In the long run, though, having a separate button to open the order list makes a bit more sense, since using 'Ctrl' for two totally different actions is probably confusing.  It's reasonable to want to open the order list even if not grouped by shared orders.

**Comment by btzy** [comment]
I now see why this bug arose.  The behaviour that @LC-Zorg wants is, and has been, only ever triggered by holding down Ctrl on _release_ of the mouse button.  If you hold down Ctrl on _pressing down_ the mouse button, it selects that vehicle's group in the group GUI.  However, previously, whether or not Ctrl is pressed while pressing down the mouse button, the drag-and-drop function is initiated.

Selecting the vehicle's group in the group GUI doesn't make sense when the dropdown is set to shared orders, since two vehicles sharing the same orders can be from different groups.  Hence, the group GUI selection behaviour was removed if the dropdown is at shared orders, but the (desirable) behaviour of continuing to initiate drag-and-drop was inadvertently removed too.

**Comment by btzy** [comment]
Actually, @LC-Zorg, I noticed you have the group-by set to shared orders, so you should do the drag-and-drop without pressing Ctrl.  This is because you're already dragging the entire shared order group when using the shared orders view.  It is not possible to move individual vehicles when using the shared orders view.

**Comment by Rau0x75** [comment]
> 
> 
> No, this is a bug

ookey, sorry that I am so actively reacting to removed «signal by default».I just want to know if this is also a bug, or was deliberately removed to reduce the number of settings. I asked many times but my question was constantly ignored.
Please unban my prev. account, I will delete unpleasant comments.

**Comment by LC-Zorg** [comment]
>Fix: Revert old behaviour in group GUI when not using shared orders #9704

Thanks! :)
If you were planning to add this button in the future, especially for both lists, then of my suggestions I think the "or" would be better.
Especially showing an excerpt of orders could be useful. The problem could be that the windows of planes and ships show otherwise. I leave it for thought. ;) Thanks.

Issue to close, I suppose

**Comment by btzy** [comment]
> The problem could be that the windows of planes and ships show otherwise.

What do you mean?  Planes and ships show a little order list on their panels, as well as a tiny black triangle to indicate the current order.  Afaik there is no special onclick handler bound to that list right now.

**Comment by LC-Zorg** [comment]
>What do you mean? Planes and ships show a little order list on their panels

This is a potential, not actual issue if you wanted to add a button to the orders window as I shown above at the bottom part. Then it would be good to standardize the way of showing orders for all types of vehicles. If you ever wanted to go that way, of course.

**Comment by btzy** [comment]
I see, yeah, it would need to be standardized if we do that.  I'm not privy to the design decisions behind making planes and ships display their order list though; maybe someone else here knows.
