### ISSUE TITLE
[Bug]: the ability to select the default signal has disappeared

### ISSUE THREAD

**Issue by LEB0VSKI** [OpenTTD/OpenTTD#9705]
### Version of OpenTTD

1.12

### Expected result

previously, it was possible to select the default signal in the settings. it was very convenient.

### Actual result

there is no such possibility now. by default, pbs is always selected. it's very annoying

### Steps to reproduce

go to settings and you won't find anything there

**Comment by FLHerne** [comment]
This is an intended change from #8688:

> Settings > Company > Cycle through signal types now defaults to Path signals only, and the option for Block signals only has been removed.

That said, I also miss this setting because I prefer the default being 2-way PBS -- for someone building a mix of 1-way and 2-way PBS, the newly hardcoded default of 1-way is very bad because it means going around the whole cycle to get 'back' to 2-way.

In the original PR @ldpl [questioned](https://github.com/OpenTTD/OpenTTD/pull/8688#issuecomment-788457364) removing this setting too, and its removal seems to have unforeseen side-effects (#9631).

I think discussion of this got a bit buried in the larger signal change, it might be worth reconsidering.

**Comment by 2TallTyler** [comment]
I think storing the last-used signal type in a config file and initializing the signal GUI with it selected, is a better path forward than simply re-adding the removed setting. I don't plan to create such a PR, but would support one.

**Comment by LC-Zorg** [comment]
Basic question: Why was this setting removed?

**Comment by FLHerne** [comment]
With the old signals hidden, it would be confusing if the default signal was one that wasn't visible to the user otherwise.

What @2TallTyler suggests makes sense; in that case a signal can't become the default unless the user has previously selected it through the GUI.

**Comment by LC-Zorg** [comment]
>storing the last-used signal type in a config file and initializing the signal GUI with it selected

This solution seems not bad in terms of the reported problem. However, there remains a problem with the fact that switching between different versions of the game every time changes the settings of the available signaling and the need to correct them. Does this solution also close this problem? I have a doubt. I'm wrong?

**Comment by JGRennison** [comment]
> > storing the last-used signal type in a config file and initializing the signal GUI with it selected
> 
> This solution seems not bad in terms of the reported problem. However, there remains a problem with the fact that switching between different versions of the game every time changes the settings of the available signaling and the need to correct them. Does this solution also close this problem? I have a doubt. I'm wrong?

If you need to use multiple versions like this, I'd suggest that you make use of the -x switch as necessary, or just use a different config file per version.
This is by no means the only setting which is not present in all versions/variants of OpenTTD.

**Comment by LC-Zorg** [comment]
> This is by no means the only setting which is not present in all versions/variants of OpenTTD.

Surely, but it's the only one that causes such problems, and I don't just mean your version of the game (though that's the main case), but older versions as well.

>If you need to use multiple versions like this, I'd suggest that you make use of the -x switch as necessary, or just use a different config file per version.

So far I'm the only one writing about it, but I don't think I'm the only one dealing with this bug - that's not the best suggestion. Never heard of the "-x" switch. I don't really know what you are writing about and I don't think it will be helpful for others either. I admit that this problem is current especially now, but even in the long run it will exist - creating new problems is not a good method of solving others.

I would prefer this problem to be really solved, not just fragmentarily. Maybe it can be done differently without adding back the setting?

**Comment by FilmBoy84** [comment]
I too have found the change infuriating

More than once now I have returned to a game and built a new line or station and forgot to change the signal type from 1-way PBS to 2-way PBS as it once defaulted to

Then had to spend an age re-signalling everything from 1-way PBS as the number of trains screaming that they cannot find a path into xxx station increases (especially easy to miss the difference on NewGRFs where there is little visual discrepancy between the types such as Timberwolf's Modern PBS lights)

If there is a reluctance to add back in a setting for a default, i support 2TallTyler's request for it to be made "last signal type used" that is stored
