### ISSUE TITLE
[Bug]: macos m1: Launching from steam starts the intel version

### ISSUE THREAD

**Issue by wrenger** [OpenTTD/OpenTTD#9710]
### Version of OpenTTD

12.1

### Expected result

I've seen that OpenTTD has a universal version for macos, which can also be installed by Steam.
The Problem is that the game Starts as intel (emulated over rosetta 2) when launched from Steam. When the OpenTTD.app is launched directly from Finder, it starts in arm mode as expected. I'm not sure if this is a Steam Problem or something went wrong on your side (like packaging the old non-universal steam api... [release notes](https://store.steampowered.com/news/group/4145017/view/2984186817523157398)).

PS: M1 MacBook Air, Steam Build: 13.10.21

### Actual result

OpenTTD starts in `intel` mode, not arm (`Apple`).

### Steps to reproduce

1. Launch the game from the Steam Library
2. Open the `Activity Monitor.app` and look for the OpenTTD.app (which is displayed as `intel` not `Apple` in the Kind column).

**Comment by glx22** [comment]
I think it's related to how steam launches games, and I guess steam is still an intel only app.

**Comment by TrueBrain** [comment]
Sadly, nothing we can do about this. Steam launches in Intel mode, and as such all games Steam launches do too. Despite us shipping an Universal build (as you found out).

Only when Steam ships an universal build this will resolve itself. Till that time, better to start the game from Finder. Sorry ...

PS: we don't use the SDK, so that is not relevant to us. It helps native games work with the SDK, but still requires launching from Finder .. sad times.

Going to close this issue now, as really there is nothing we can do about it :(
