### ISSUE TITLE
[Bug]: Can't change resolution on retina screen

### ISSUE THREAD

**Issue by pleasejustgo** [OpenTTD/OpenTTD#9717]
### Version of OpenTTD

latest 12.1

### Expected result

I expect to be able to change resolution.

### Actual result

I'm new to this game. I just discovered it recently from someone. So I installed the mac version of the game and immediately everything is too small. I change the resolution to something other than the default 1680x1020 or whatever and the window becomes smaller. When I drag the window to make it larger the resolution automatically changes back. Already a sign of failure. Then In full screen mode, when I change the resolution the game screen becomes smaller with black borders. Is there any way to just change the resolution??
Macbook pro 15" 2015, M370x graphics. macos 10.14.6. Retina screen 2880x1800. Pls, thanks.

### Steps to reproduce

see above

**Comment by nielsmh** [comment]
Try changing the GUI size and Font size options (just below Resolution setting) to 2x scaling.

**Comment by LC-Zorg** [comment]
> Try changing the GUI size and Font size options (just below Resolution setting) to 2x scaling.

This is helpful, but it doesn't solve all problems - first of all, the view of the gameplay is getting farther away as the resolution increases. Also, in my opinion, the GUI and fonts x2/x4 don't look good, have distorted proportions (GUI) and don't match the style of the game.
I also think that due to the fact that OTTD is a pixelart game, smooth resolution change will not look good here. In version 1.8.0 and possibly earlier (?), the game resolution was adjusting to the screen resolution and it didn't look good - everything was blurry.

Open both at 100/200% enlargement to see the difference.

1.8.0
![OTTD 1 8 0](https://user-images.githubusercontent.com/67662046/143791218-5abfd46a-7fb1-4c07-ba2c-360e5f80531b.png)

1.9.2
![OTTD 1 9 2](https://user-images.githubusercontent.com/67662046/143791226-bb5fbc18-26a4-4fe7-882c-696df144b082.png)

What I think might make sense is to add an option to zoom everything x2 (with original interface and fonts preserved). I have been playing at 1440x900 resolution for several years and I believe it was optimal for this game. Enlarging everything in the case of the resolution of 2880x1800 would have the same, very good effect. This option would be just as useful, or even more useful, for even higher resolutions. In the future, when the screen resolutions will be even greater, it will be possible to add options x3 (5K), x4 (8K) etc. I don't know if it is simple, but in any case zooming the game image works very well and efficiently.

**Comment by andythenorth** [comment]
Thanks for reporting.  There are lots of ways to adjust OpenTTD zoom, UI scale and font to suit your preferences.

Low likelihood of this one getting 'fixed'.
