### ISSUE TITLE
[Crash]: Can't start game with CityGrowthLimiter GS

### ISSUE THREAD

**Issue by Thundo54** [OpenTTD/OpenTTD#9720]
### Version of OpenTTD

12.1 (compiled on RaspberryPi), aarch64 (RP3B+)

### Steps to reproduce

1. Open Scenario Editor
2. Configure GS CGL 
3.  Save scenario
4.  Start game with new scenario
5.  Save game to run in on Raspberry Pi
6.  Start game on RPi3B+ with command `/opt/openttd-12.1/build/openttd -D -g /root/.openttd/save/autosave/mygame.sav`
7. Crash while starting game (as dedicated server)

### Upload crash files

[crash.zip](https://github.com/OpenTTD/OpenTTD/files/7612391/crash.zip)

**Comment by glx22** [comment]
Please attach your savegame.

**Comment by frosch123** [comment]
I reproduced this, here is a simple scenario that uses 'CityGrowthLimiter v6'
[cgl.zip](https://github.com/OpenTTD/OpenTTD/files/7612549/cgl.zip)

The bug is triggered by the script in town.nut during static initialisation:
```
class Town {
        ...
        paxRequired = GSController.GetSetting("min_transport_pax");
        ...
}
```
* The script wants to read some script configuration setting during loading of the scenario.
* OpenTTD is not yet finished loading the scenario and actually thinks it still is in the main menu (GM_MENU).
* OpenTTD then tries to use the new-game script configuration, instead of the one from the scenario. (this is already wrong)
* However, this new-game script configuration is not available on dedicated servers, so OpenTTD crashes.

The underlying issue in OpenTTD is actually pretty severe:
* When loading savegames/scenarios, AI and GS are started inside the saveload code:
    * AIPLChunkHandler::Load
    * GSDTChunkHandler::Load
* At this point of time, the savegame is not yet completely loaded, AfterLoad did not run yet, ... so the gamestate is still incomplete or even invalid.
* AI/GS code running at this time get in contact with all kind of invalid data. (static initialisation, script's Load() method)

I think to fix this, loading AI/GS needs to be changed significantly:
* AIPLChunkHandler::Load and GSDTChunkHandler::Load have to store the raw script data in some temporary location.
* Loading and starting AI/GS must wait until the end of AfterLoad, when the gamestate is ready.

**Comment by James103** [comment]
I can reproduce this with a custom AI specifically made for this, so it is not just limited to the provided Game Script and save game.
Crashing save: [test_9720.zip](https://github.com/OpenTTD/OpenTTD/files/7612576/test_9720.zip)
AI being used: [Test AI #9720.zip](https://github.com/OpenTTD/OpenTTD/files/7612578/Test.AI.9720.zip)

When run with `-D ::1 -g path\to\the\above\save.sav`, OpenTTD version 6953df7b5e crashes during load with:
`Assertion failed at line 94 of D:\a\OpenTTD\OpenTTD\src\ai\ai_config.cpp: strcmp("start_date", name) == 0`

Crash log: [crash.zip](https://github.com/OpenTTD/OpenTTD/files/7612579/crash.zip)
