### ISSUE TITLE
[Bug]: Servers Offline?

### ISSUE THREAD

**Issue by Shituation** [OpenTTD/OpenTTD#9821]
### Version of OpenTTD

12.1 / Windows 10

### Expected result

Are all servers offline?
https://servers.openttd.org/

Also my dedicated server says: "timeout while connecting to coordinator.openttd.org:3976" 
(I thought 3979 and 3978 where the only used ports)
Anyways, opening 3976 doesn't make difference.

### Actual result

all servers offline

### Steps to reproduce

all servers offline

**Comment by nielsmh** [comment]
No? The server browser works fine for me, both on the web and in-game, and I can connect to the listed game servers too.

Can you check what IP address `coordinator.openttd.org` resolves to on your dedicated server? (You can use the ping command to check that, for example.)

**Comment by Shituation** [comment]
I see.. must be on my side then. Thanks

**Comment by Shituation** [comment]
Pinging coordinator.aws.openttd.org [3.127.79.215] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.

**Comment by TrueBrain** [comment]
Ping to our infrastructure never works, for nobody. So that is not surprisingly.

If you like, you can try reaching https://server.coordinator.openttd.org/ in a browser. If you can, the problem is most likely some firewall between you and us that prevents non-http traffic from flowing. In that case there is little we can do.

If you cannot, it means you cannot reach our infrastructure at all. Which is a bit unusual. If you like, you could share your IP with us, so we can trace it from our end. A website like https://www.whatismyip.com/ will tell you what your IP is. If you don't want to share it publicly (which I can fully understand), feel free to email it to truebrain at openttd dot org.

**Comment by Shituation** [comment]
Thanks, but I can confirm now that its an ISP side problem so nothing to get alarmed.
