### ISSUE TITLE
[Crash]: In server list

### ISSUE THREAD

**Issue by luk3ZPL** [OpenTTD/OpenTTD#9871]
### Version of OpenTTD

latest 12.2

### Steps to reproduce

1. Open Multiplayer/server list
2. Type: CZ
3. Minimize game to taskbar
4. Wait for a few minutes

### Upload crash files

![crash20220430110342](https://user-images.githubusercontent.com/4522457/166103269-3884e15b-5ea7-4070-b62a-093ea3596458.png)
[crash20220430110342.log](https://github.com/OpenTTD/OpenTTD/files/8596762/crash20220430110342.log)
[crash20220430110342.zip](https://github.com/OpenTTD/OpenTTD/files/8596766/crash20220430110342.zip)

**Comment by glx22** [comment]
The crash happens outside openttd, it's in `ig8icd64.dll` (intel opengl driver I guess)

**Comment by James103** [comment]
Try running OpenTTD with: `openttd -v win32`. If that fails, please post the resulting crash log.

**Comment by luk3ZPL** [comment]
> The crash happens outside openttd, it's in `ig8icd64.dll` (intel opengl driver I guess)

Can I send some data to Intel somehow to inform them about the problem with drivers ? I'm using latest for i7 5500U from 2021.

**Comment by luk3ZPL** [comment]
Is this the same crash ?
[crash20220504155142.log](https://github.com/OpenTTD/OpenTTD/files/8622063/crash20220504155142.log)
![crash20220504155142](https://user-images.githubusercontent.com/4522457/166721730-c9b395d4-c69f-48f9-ac9e-254d57b5f1b4.png)
[crash20220504155142.zip](https://github.com/OpenTTD/OpenTTD/files/8622064/crash20220504155142.zip)

Next time I'll try to run with openttd -v win32 (I'm changing my shortcut now).

**Comment by glx22** [comment]
Yes crash is inside intel driver.
You can also set `videodriver` to `win32` in openttd.cfg.

**Comment by TrueBrain** [comment]
As mentioned, a crash inside the Intel driver. Nothing we can actually do about that, other than to suggest to not use hardware acceleration.

In 14.0 we addressed this issue partially: if we notice the game crashed due to a driver failure, we will not be using hardware acceleration. It is not perfect yet, but at least should somewhat prevent these issues.

Going to close this up for now; feel free to reopen if it resurfaces with the nightly / upcoming 14.0.
