### ISSUE TITLE
[Crash]: Console command `clear` can stack overflow and crash

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#9977]
### Version of OpenTTD

e9507e7ffa on Windows 10, 64-bit

### Steps to reproduce

1. `debuglevel 9`
2. Wait a few minutes or until a few ten-thousand lines are logged to the in-game console.
3. `clear`
4. Crash

Alternatively,
1. Create a file with the name `a.txt` and the contents as follows:
```
exec a.txt
exec a.txt
exec a.txt
```
2. Run `exec a.txt`
3. Run `clear` (or just wait)

Doing this in master bypasses the crash handler, while doing the same in JGRPP 0.48.1 crashes properly. The crash files from the latter are attached.

### Upload crash files

The following crash report was done on JGRPP 0.48.1: [crash-20220825T204753Z.zip](https://github.com/OpenTTD/OpenTTD/files/9428214/crash-20220825T204753Z.zip)

Doing the same in vanilla generates only `crash.dmp`, whose file size is 0 bytes.

**Comment by nielsmh** [comment]
https://github.com/OpenTTD/OpenTTD/blob/e9507e7ffa295672724c5f473fbf7bb8d6cce536/src/console_gui.cpp#L409-L412
https://github.com/OpenTTD/OpenTTD/blob/e9507e7ffa295672724c5f473fbf7bb8d6cce536/src/console_gui.cpp#L115-L123
https://github.com/OpenTTD/OpenTTD/blob/e9507e7ffa295672724c5f473fbf7bb8d6cce536/src/console_gui.cpp#L63-L72

Who thought a linked list was a good structure for a potentially very long list of output?
This also has the side effect that scrolling back gets slower and slower the further back you go, because it has to walk the entire list backwards to find the line indexes to show.
